local e={
  BlockSizeInBytes=2e5,
  NumBlocks=8,
  States={
    {
      StateName="MgoTitleUI",
      PackagePath="/Assets/mgo/pack/ui/MgoTitleUI.fpk",
      Layouts={
        {FilePath="/Assets/mgo/ui/LayoutAsset/ui_title/ui_title_alpha.uilb",LayoutName="MgoTitleUI",DrawPriority="TITLE_LOGO",FontTableIndex=0,UseParentCamera=false}
      }
    },
    {
      StateName="MgoBriefingScreenUi",
      PackagePath="/Assets/mgo/pack/ui/MgoMissionBriefingScreenUi.fpk",
      Layouts={
        {FilePath="/Assets/mgo/ui/LayoutAsset/ui_briefing/ui_briefing.uilb",LayoutName="uil_briefing_screen",DrawPriority="SORTIE_MENU",FontTableIndex=0,UseParentCamera=false},
        {FilePath="/Assets/mgo/ui/LayoutAsset/bonus_popup/UI_bonus_pop.uilb",LayoutName="uil_briefing_popup",DrawPriority="SORTIE_POPUP",FontTableIndex=0,UseParentCamera=false}
      }
    },
    {
      StateName="MgoSurvivalWinUi",
      PackagePath="/Assets/mgo/pack/ui/MgoSurvivalWinUi.fpk",
      Layouts={
        {FilePath="/Assets/mgo/ui/LayoutAsset/bonus_popup/UI_svvl_pop_win.uilb",LayoutName="uil_survival_win",DrawPriority="SORTIE_POPUP",FontTableIndex=0,UseParentCamera=false}
      }
    },
    {StateName="MgoSpectatorUi",PackagePath="/Assets/mgo/pack/ui/MgoSpectatorUi.fpk",
      Layouts={
        {FilePath="/Assets/mgo/ui/LayoutAsset/ui_spactator/ui_spectator_layout.uilb",LayoutName="uil_spectator_layout",DrawPriority="PAUSE_BG",FontTableIndex=0,UseParentCamera=false}
      }
    },
    {StateName="MgoRoundEndUi",PackagePath="/Assets/mgo/pack/ui/MgoRoundEndUi.fpk",
      Layouts={
        {FilePath="/Assets/mgo/ui/LayoutAsset/ui_winlose/ui_winlose.uilb",LayoutName="MgoRoundEndUi",DrawPriority="PAUSE_BG",FontTableIndex=0,UseParentCamera=false}
      }
    },
    {StateName="MgoLevelUpUi",PackagePath="/Assets/mgo/pack/ui/MgoLevelUpUi.fpk",
      Layouts={
        {FilePath="/Assets/mgo/ui/LayoutAsset/ui_levelupnotice/ui_levelupnotice.uilb",LayoutName="uil_level_up",DrawPriority="PAUSE_BG",FontTableIndex=0,UseParentCamera=false}
      }
    },
    {StateName="MgoCharacterModificationUi",PackagePath="/Assets/mgo/pack/ui/iDroid/idroid_child_character_create.fpk",
      Layouts={
        {FilePath="/Assets/mgo/ui/LayoutAsset/id_customize/id_customize_layout.uilb",LayoutName="uil_idroid_character_modify",DrawPriority="IDROID_CHARACTER_MODIFY",FontTableIndex=0,UseParentCamera=false}
      }
    },
    {StateName="MgoRoundStartUi",PackagePath="/Assets/mgo/pack/ui/MgoRoundStartUi.fpk",
      Layouts={
        {FilePath="/Assets/mgo/ui/LayoutAsset/ui_roundStart/ui_roundStart.uilb",LayoutName="uil_round_start",DrawPriority="PAUSE_BG",FontTableIndex=0,UseParentCamera=false}
      }
    },
    {StateName="MgoCustomizeUI_Common",PackagePath="/Assets/mgo/pack/ui/MgoCustomizeUI_Common.fpk",Windows={
      {WindowName="MgoCustomizeUI_Common",
        Layouts={
          {FilePath="/Assets/mgo/ui/LayoutAsset/id_customize_new/id_customize_common_layout.uilb",LayoutName="MgoCustomizeUI_Common",DrawPriority="IDROID_CHARACTER_MODIFY",FontTableIndex=0,UseParentCamera=false}
        }
      },
      {WindowName="TppUiMenuTitleCallback",
        Layouts={
          {FilePath="/Assets/tpp/ui/LayoutAsset/tpp_common/UI_common_layout.uilb",LayoutName="UI_mb_cmn_layout_uil",DrawPriority="IDROID_CHARACTER_MODIFY",FontTableIndex=0,UseParentCamera=false}}}
    }
    },
    {StateName="MgoCustomizeUI_Character",PackagePath="/Assets/mgo/pack/ui/MgoCustomizeUI_Character.fpk",Dependency="MgoCustomizeUI_Common",
      Layouts={
        {FilePath="/Assets/mgo/ui/LayoutAsset/id_customize_new/id_customize_pt1_layout.uilb",LayoutName="MgoCustomizeUI_Character",DrawPriority="IDROID_CHARACTER_MODIFY",FontTableIndex=0,UseParentCamera=false}
      }
    },
    {StateName="MgoCustomizeUI_Loadout",PackagePath="/Assets/mgo/pack/ui/MgoCustomizeUI_Loadout.fpk",Dependency="MgoCustomizeUI_Common",
      Layouts={
        {FilePath="/Assets/mgo/ui/LayoutAsset/id_customize_new/id_customize_pt2_layout.uilb",LayoutName="MgoCustomizeUI_Loadout",DrawPriority="IDROID_CHARACTER_MODIFY",FontTableIndex=0,UseParentCamera=false}
      }
    },
    {StateName="MgoCustomizeUI_Info",PackagePath="/Assets/mgo/pack/ui/MgoCustomizeUI_Info.fpk",Dependency="MgoCustomizeUI_Common",
      Layouts={
        {FilePath="/Assets/mgo/ui/LayoutAsset/id_customize_new/id_customize_pt3_layout.uilb",LayoutName="MgoCustomizeUI_Info",DrawPriority="IDROID_CHARACTER_MODIFY",FontTableIndex=0,UseParentCamera=false}
      }
    },
    {StateName="MgoLoadingUI",PackagePath="/Assets/mgo/pack/ui/MgoLoadingUI.fpk",
      Layouts={
        {FilePath="/Assets/mgo/ui/LayoutAsset/id_additional/ui_id_bg_black.uilb",LayoutName="uil_loading_bg",DrawPriority="__GAME_FADE",FontTableIndex=0,UseParentCamera=false}
      }
    },
    {StateName="MgoBetaWatermarkUi",PackagePath="/Assets/mgo/pack/ui/MgoBetaWatermark.fpk",
      Layouts={
        {FilePath="/Assets/mgo/ui/LayoutAsset/ui_debug/ui_debug.uilb",LayoutName="uil_watermark_layout",DrawPriority="PAUSE_BG",FontTableIndex=0,UseParentCamera=false}
      }
    },
    {StateName="MgoKillScreenUi2",PackagePath="/Assets/mgo/pack/ui/MgoKillScreenUi2.fpk",
      Layouts={
        {FilePath="/Assets/mgo/ui/LayoutAsset/ui_Killscreen_new/UI_Killscreen_new.uilb",LayoutName="uil_killscreen_layout",DrawPriority="PAUSE_BG",FontTableIndex=0,UseParentCamera=false}
      }
    },
    {StateName="MgoRespawnUi2",PackagePath="/Assets/mgo/pack/ui/MgoRespawnUi2.fpk",
      Layouts={
        {FilePath="/Assets/mgo/ui/LayoutAsset/ui_respawn_new/ui_respawn_new_layout.uilb",LayoutName="uil_respawn2_layout",DrawPriority="PAUSE_BG",FontTableIndex=0,UseParentCamera=false}
      }
    },
    {StateName="MgoMissionResultsUi",PackagePath="/Assets/mgo/pack/ui/MgoMissionResultsUi.fpk",
      Layouts={
        {FilePath="/Assets/mgo/ui/LayoutAsset/ui_missionResult/ui_missionResult_layout.uilb",LayoutName="uil_mission_result_screen",DrawPriority="PAUSE_BG",FontTableIndex=0,UseParentCamera=false}
      }
    },
    {StateName="MgoHudUI",PackagePath="/Assets/mgo/pack/ui/MgoHudUi.fpk",Windows={
      {WindowName="MgoRulesetTicker",
        Layouts={
          {FilePath="/Assets/mgo/ui/LayoutAsset/hud_combatticker_l/hud_combatticker_l_layout.uilb",LayoutName="uil_ruleset_ticker",DrawPriority="ANNOUNCE_LOG",FontTableIndex=0,UseParentCamera=false}
        }
      },
      {WindowName="MgoCombatTicker",
        Layouts={
          {FilePath="/Assets/mgo/ui/LayoutAsset/hud_combatticker_new/hud_combatticker_new_layout.uilb",LayoutName="uil_combat_ticker",DrawPriority="ANNOUNCE_LOG",FontTableIndex=0,UseParentCamera=false}
        }
      },
      {WindowName="MgoWorldMarker",
        Layouts={
          {FilePath="/Assets/mgo/ui/LayoutAsset/hud_objectivemarker/hud_objectiveMarkerSet.uilb",LayoutName="uil_obj_marker",DrawPriority="WORLD_MARKER",FontTableIndex=0,UseParentCamera=false},{FilePath="/Assets/mgo/ui/LayoutAsset/hud_buddymarker/hud_buddymarker_layout.uilb",LayoutName="uil_buddy_marker",DrawPriority="WORLD_MARKER_CHARA",FontTableIndex=0,UseParentCamera=false}
        }
      },
      {WindowName="MgoRulesetUi",
        Layouts={
          {FilePath="/Assets/mgo/ui/LayoutAsset/hud_ruleset_layout/hud_ruleset_layout.uilb",LayoutName="MgoRulesetUi",DrawPriority="TELOP_TEXT",FontTableIndex=0,UseParentCamera=false}
        }
      },
      {WindowName="MgoDisplayTimer",
        Layouts={
          {FilePath="/Assets/mgo/ui/LayoutAsset/hud_timer/hud_timer.uilb",LayoutName="MgoDisplayTimer",DrawPriority="ANNOUNCE_LOG",FontTableIndex=0,UseParentCamera=false}
        }
      },
      {WindowName="MgoInterrogationUi",
        Layouts={
          {FilePath="/Assets/mgo/ui/LayoutAsset/ui_cqc_progress/ui_cqc_progress_layout.uilb",LayoutName="ui_cqc_progress_layout",DrawPriority="ACTION_ICON",FontTableIndex=0,UseParentCamera=false}}}
    }
    },
    {StateName="MgoHudUI_2",PackagePath="/Assets/mgo/pack/ui/MgoHudUi_2.fpk",Windows={
      {WindowName="EquipCross",Graph={FilePath="/Assets/tpp/ui/GraphAsset/StageGame/Player/lmenu/ld_layer/equip_cross.uigb"}},{WindowName="cqc_action_icon",Graph={FilePath="/Assets/tpp/ui/GraphAsset/StageGame/Player/action_icon/cqc_action_icon.uigb"}}
    }
    },
    {StateName="MgoHudUI_3",PackagePath="/Assets/mgo/pack/ui/MgoHudUi_3.fpk",Windows={
      {WindowName="HeadMarker",Graph={FilePath="/Assets/mgo/ui/GraphAsset/StageGame/marker/ld_marker/headmark_marker.uigb"}},{WindowName="damage_dir",Graph={FilePath="/Assets/tpp/ui/GraphAsset/StageGame/damage_dir/damage_dir.uigb"}}
    }
    },
    {StateName="MgoHudUI_4",PackagePath="/Assets/mgo/pack/ui/MgoHudUi_4.fpk",Windows={
      {WindowName="MgoObjectiveNotice",
        Layouts={
          {FilePath="/Assets/mgo/ui/LayoutAsset/hud_objective_new/hud_objective_new.uilb",LayoutName="uil_objective_notice",DrawPriority="PICK_UP",FontTableIndex=0,UseParentCamera=false}
        }
      },
      {WindowName="MgoMinimapUi",
        Layouts={
          {FilePath="/Assets/mgo/ui/LayoutAsset/hud_minimap_layout/hud_minimap_layout.uilb",LayoutName="uil_minimap_layout",DrawPriority="ANNOUNCE_LOG",FontTableIndex=0,UseParentCamera=false}
        }
      },
      {WindowName="MgoScoreUiNew",
        Layouts={
          {FilePath="/Assets/mgo/ui/LayoutAsset/ui_roundResult/UI_roundrslt_new_layout.uilb",LayoutName="uil_score_new",DrawPriority="PAUSE_BG",FontTableIndex=0,UseParentCamera=false}
        }
      },
      {WindowName="MgoHitSign",
        Layouts={
          {FilePath="/Assets/mgo/ui/LayoutAsset/hud_hitsign/hud_hitsign.uilb",LayoutName="uil_hit_sign",DrawPriority="SIGHT_STRONG_HUD",FontTableIndex=0,UseParentCamera=false}
        }
      },
      {WindowName="notice_dir",Graph={FilePath="/Assets/tpp/ui/GraphAsset/StageGame/damage_dir/notice_dir.uigb"}}
    }
    },
    {StateName="MgoHudUI_4_freeplay",PackagePath="/Assets/mgo/pack/ui/MgoHudUi_4_freeplay.fpk",Windows={
      {WindowName="MgoObjectiveNotice",
        Layouts={
          {FilePath="/Assets/mgo/ui/LayoutAsset/hud_objective_new/hud_objective_new.uilb",LayoutName="uil_objective_notice",DrawPriority="PICK_UP",FontTableIndex=0,UseParentCamera=false}
        }
      },
      {WindowName="MgoMinimapUi",
        Layouts={
          {FilePath="/Assets/mgo/ui/LayoutAsset/hud_minimap_layout/hud_minimap_layout.uilb",LayoutName="uil_minimap_layout",DrawPriority="ANNOUNCE_LOG",FontTableIndex=0,UseParentCamera=false}
        }
      },
      {WindowName="MgoPartyScreenUI",
        Layouts={
          {FilePath="/Assets/mgo/ui/LayoutAsset/id_additional/id_PartyScreen.uilb",LayoutName="uil_party_screen",DrawPriority="PAUSE_BG",FontTableIndex=0,UseParentCamera=false}
        }
      },
      {WindowName="MgoHitSign",
        Layouts={
          {FilePath="/Assets/mgo/ui/LayoutAsset/hud_hitsign/hud_hitsign.uilb",LayoutName="uil_hit_sign",DrawPriority="SIGHT_STRONG_HUD",FontTableIndex=0,UseParentCamera=false}
        }
      },
      {WindowName="notice_dir",Graph={FilePath="/Assets/tpp/ui/GraphAsset/StageGame/damage_dir/notice_dir.uigb"}}
    }
    },
    {StateName="EulaUi",PackagePath="/Assets/mgo/pack/ui/EulaUi.fpk"}}}MgoUi.CreateController(e)
