--IHGenUnfoundReferences.lua
--GENERATED by IHTearDown BuildMockModulesFromReferences
--references from IHGenModuleReferences that werent found in live session
local this={
  CaptureCage = true,
  Demo = {
    playerPartsType = true
  },
  Fox = {
    HungUp = true,
    StrCode32l = true
  },
  Game = {
    DEBUG_AddScript = true
  },
  GameObject = {
    NULL_IDdem = true,
    SpecialActionEnd = true
  },
  HighSpeedCamera = true,
  MotherBaseConstructConnector = {
    SetContainerGimmickList = true
  },
  Player = {
    DEBUG_PlaceAround = true,
    NotifyChangedPlayerRailAction = true,
    UnSetPause = true
  },
  PlayerCamoType = {
    NONE = true
  },
  PlayerType = {
    MGO_MALE = true
  },
  TppBullet = {
    ClearBulletMark = true
  },
  TppEquip = {
    BLA_mgs0_miss2 = true,
    BLA_ms01 = true,
    BL_IT_TimeCigarette = true,
    BL_SWP_Grenade = true,
    BL_SWP_Magazine = true,
    EPQ_None = true,
    EQP_DD_210000 = true,
    EQP_DD_210102 = true,
    EQP_DD_210113 = true,
    EQP_DD_210123 = true,
    EQP_DD_210214 = true,
    EQP_DD_210301 = true,
    EQP_DD_210401 = true,
    EQP_DH_210500 = true,
    EQP_DH_210602 = true,
    EQP_DH_210603 = true,
    EQP_DH_210604 = true,
    EQP_DH_210704 = true,
    EQP_DH_210801 = true,
    EQP_DH_210901 = true,
    EQP_DW_220002 = true,
    EQP_DW_220003 = true,
    EQP_DW_220004 = true,
    EQP_DW_220102 = true,
    EQP_DW_220103 = true,
    EQP_DW_220104 = true,
    EQP_DW_220202 = true,
    EQP_DW_220203 = true,
    EQP_DW_220204 = true,
    EQP_DW_220301 = true,
    EQP_DW_220303 = true,
    EQP_DW_220414 = true,
    EQP_DW_220525 = true,
    EQP_DW_220602 = true,
    EQP_DW_220603 = true,
    EQP_DW_220604 = true,
    EQP_DW_220605 = true,
    EQP_DW_221002 = true,
    EQP_DW_221003 = true,
    EQP_DW_221004 = true,
    EQP_DW_221103 = true,
    EQP_DW_221104 = true,
    EQP_DW_221105 = true,
    EQP_DW_221304 = true,
    EQP_DW_221305 = true,
    EQP_DW_221306 = true,
    EQP_DW_221404 = true,
    EQP_DW_221405 = true,
    EQP_DW_221406 = true,
    EQP_DW_221505 = true,
    EQP_DW_221506 = true,
    EQP_DW_221507 = true,
    EQP_HL_300001 = true,
    EQP_HL_300002 = true,
    EQP_HL_300003 = true,
    EQP_HL_300004 = true,
    EQP_HL_300005 = true,
    EQP_HL_300101 = true,
    EQP_HL_300202 = true,
    EQP_HL_300302 = true,
    EQP_HL_300303 = true,
    EQP_HL_300304 = true,
    EQP_HL_300413 = true,
    EQP_HL_300414 = true,
    EQP_HL_300415 = true,
    EQP_HL_300502 = true,
    EQP_HL_300503 = true,
    EQP_HL_300504 = true,
    EQP_HL_300604 = true,
    EQP_HL_300605 = true,
    EQP_HL_300606 = true,
    EQP_MB_500103 = true,
    EQP_MB_500104 = true,
    EQP_MB_500105 = true,
    EQP_MB_500114 = true,
    EQP_MB_500115 = true,
    EQP_MB_500116 = true,
    EQP_MB_500203 = true,
    EQP_MB_500204 = true,
    EQP_MB_500205 = true,
    EQP_MB_500214 = true,
    EQP_MB_500215 = true,
    EQP_MB_500216 = true,
    EQP_MB_500225 = true,
    EQP_MB_500226 = true,
    EQP_MB_500227 = true,
    EQP_WP_East_sr_010 = true,
    EQP_WP_Quiet_st_010 = true,
    EQP_WP_Quiet_st_020 = true,
    EQP_WP_Quiet_st_030 = true,
    EQP_WP_Quiet_st_040 = true,
    EQP_WP_Quiet_st_050 = true,
    EQP_WP_Quiet_st_060 = true,
    UD_None = true
  },
  TppGameSequence = {
    GetInstance = true,
    RequestGameSetup = true
  },
  TppMbDev = {
    EQP_DEV_SWP_C4 = true,
    EQP_DEV_SWP_Grenade = true,
    EQP_DEV_SWP_Magazine = true,
    EQP_DEV_SWP_SmokeGrenade = true,
    EQP_DEV_WP_ar00_v06 = true,
    EQP_DEV_WP_ar00_v07 = true,
    EQP_DEV_WP_ar00_v08 = true,
    EQP_DEV_WP_ar01_v00 = true,
    EQP_DEV_WP_hg00_v01 = true,
    EQP_DEV_WP_hg01_v00 = true,
    EQP_DEV_WP_hg08 = true,
    EQP_DEV_WP_mg03_v00 = true,
    EQP_DEV_WP_ms00 = true,
    EQP_DEV_WP_sg01_v00 = true,
    EQP_DEV_WP_sm00_v00 = true,
    EQP_DEV_WP_sr01_v00 = true
  },
  TppMotherBaseManagement = {
    DEBUG_DirectAddRandomStaffs = true,
    DEBUG_DumpMbsParam = true
  },
  TppNetworkUtil = {
    DEBUG_DumpServerParameter = true
  },
  TppPickable = {
    DEBUG_DropWeapon = true
  },
  TppPlaced = true,
  TppScriptVars = {
    CATEGORY_MGO = true
  },
  name = true
}
return this