local ParameterPackingList = {
{ name = "ModelDefault",
	params = {},
	packing = { },
	textures = {  }
},
{ name = "fox3DDF_Blin",
	params = {"MatParamIndex_0"},
	packing = { 0x0,0x0,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN" }
},
{ name = "fox3DDF_Blin_4MT",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3"},
	packing = { 0x0,0x4,0x8,0xc },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "MatParamMap_Tex_LIN" }
},
{ name = "fox3DDF_Blin_2MT",
	params = {"MatParamIndex_0","MatParamIndex_1"},
	packing = { 0x0,0x4,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "MatParamMap_Tex_LIN" }
},
{ name = "fox3DDF_Blin_SubNorm",
	params = {"MatParamIndex_0","SubNormal_Blend","URepeat_UV","VRepeat_UV"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x8,0xc,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "SubNormalMap_Tex_NRM", "SubNormalMask_Tex_LIN" }
},
{ name = "fox3DDF_Blin_SubNormAnim",
	params = {"MatParamIndex_0","SubNormal_Blend","URepeat_UV","VRepeat_UV","UShift_UV","VShift_UV"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x8,0xc,0x0,  0x10,0x14,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "SubNormalMap_Tex_NRM", "SubNormalMask_Tex_LIN" }
},
{ name = "fox3DDF_Dirty",
	params = {"MatParamIndex_0"},
	packing = { 0x0,0x0,0x0,0x0,  0x0,0x0,0x0,0x0,  0x0,0x0,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Dirty_Tex_LIN" }
},
{ name = "fox3DDF_Blin_4MT_Dirty",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3"},
	packing = { 0x0,0x4,0x8,0xc },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "MatParamMap_Tex_LIN", "Dirty_Tex_LIN" }
},
{ name = "fox3DDF_Hair",
	params = {"MatParamIndex_0","Anistropic_MainLightDir","Anistropic_Diffusion","HairShiftScale","Incidence_Roughness","Incidence_Color","URepeat_UV","VRepeat_UV"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x5,0x6,0x0,  0x8,0xc,0x0,0x0,  0x10,0x0,0x0,0x0,  0x14,0x15,0x16,0x17,  0x18,0x1c,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "SpecularMap_Tex_LIN", "Translucent_Tex_LIN", "Shift_Tex_LIN" }
},
{ name = "fox3DDF_Blin_MicroRoughness_SubNorm",
	params = {"MatParamIndex_0","SubNormal_Blend","URepeat_UV","VRepeat_UV","MinRoughness","RoughnessFrequency"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x8,0xc,0x0,  0x10,0x14,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "SubNormalMap_Tex_NRM", "SubNormalMask_Tex_LIN" }
},
{ name = "fox3DDF_Skin_Dirty",
	params = {"MatParamIndex_0","Incidence_Roughness","Incidence_Color"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x0,0x0,0x0,  0x8,0x9,0xa,0xb },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Translucent_Tex_LIN", "Dirty_Tex_LIN" }
},
{ name = "fox3DDF_Skin_Tension_Dirty",
	params = {"MatParamIndex_0","Incidence_Roughness","TensionRate","TensionShift","TensionController","Incidence_Color"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x8,0xc,0x10,  0x14,0x15,0x16,0x17 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Translucent_Tex_LIN", "TensionSubNormalMap_Tex_NRM", "Dirty_Tex_LIN" }
},
{ name = "fox3DDF_FastWave",
	params = {"MatParamIndex_0","Specular_Value","Roughness_Value","Translucent_Value","WindDir","WindAnimTime","WindAmplitude","WeightDiffusion","WeightOffset","WindOffset","OldWindDir","NormalRotRate","OldWindAnimTime","OldWindAmplitude","WindRandAmplitude"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x8,0xc,0x0,  0x10,0x11,0x12,0x0,  0x14,0x18,0x1c,0x20,  0x24,0x25,0x26,0x0,  0x28,0x29,0x2a,0x2c,  0x30,0x34,0x38,0x0 },
	textures = { "Base_Tex_SRGB" }
},
{ name = "fox3DDF_PixcelWave",
	params = {"MatParamIndex_0","Specular_Value","Roughness_Value","Translucent_Value","WindDir","WindAnimTime","WindAmplitude","WeightDiffusion","WeightOffset","WindOffset","OldWindDir","NormalRotRate","OldWindAnimTime","OldWindAmplitude","WindRandAmplitude","PixcelWaveCenterV","PixcelWaveScale","NegWaveScale"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x8,0xc,0x0,  0x10,0x11,0x12,0x0,  0x14,0x18,0x1c,0x20,  0x24,0x25,0x26,0x0,  0x28,0x29,0x2a,0x2c,  0x30,0x34,0x38,0x0,  0x3c,0x40,0x44,0x0 },
	textures = { "Base_Tex_SRGB" }
},
{ name = "fox3DDF_TempolaryView",
	params = {"TempolaryBaseColor"},
	packing = { 0x0,0x0,0x0,0x0,  0x0,0x1,0x2,0x3 },
	textures = {  }
},
{ name = "fox3DFW_Constant",
	params = {"SelfColor","SelfColorIntensity"},
	packing = { 0x0,0x1,0x2,0x3,  0x4,0x0,0x0,0x0 },
	textures = { "Mask_Tex_LIN" }
},
{ name = "fox3DFW_ConstantSRGB",
	params = {"SelfColor","SelfColorIntensity"},
	packing = { 0x0,0x1,0x2,0x3,  0x4,0x0,0x0,0x0 },
	textures = { "Base_Tex_SRGB" }
},
{ name = "fox3DFW_Constant_NDR",
	params = {},
	packing = { },
	textures = { "Base_Tex_LIN" }
},
{ name = "fox3DFW_ParallaxReflection",
	params = {"HeightScale"},
	packing = { 0x0,0x0,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "Height_Tex_LIN", "Mask_Tex_LIN" }
},
{ name = "fox3DFW_Glass",
	params = {"MatParamIndex_0","ReflectionColor","GlassColor","GlassRoughness"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x5,0x6,0x0,  0x8,0x9,0xa,0xb,  0x0,0xc,0x0,0x0 },
	textures = { "Base_Tex_LIN", "NormalMap_Tex_NRM", "GlassReflection_Tex_SRGB" }
},
{ name = "fox3DFW_Glass_CommonRef",
	params = {"MatParamIndex_0","ReflectionColor","GlassColor","GlassRoughness"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x5,0x6,0x0,  0x8,0x9,0xa,0xb,  0x0,0xc,0x0,0x0 },
	textures = { "Base_Tex_LIN", "NormalMap_Tex_NRM", "GlassReflection_Tex_SRGB" }
},
{ name = "fox3DDC_Blin",
	params = {"MatParamIndex_0"},
	packing = { 0x0,0x0,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN" }
},
{ name = "fox3DNDW_Shadow",
	params = {},
	packing = { 0x0,0x0,0x0,0x0 },
	textures = { "Mask_Tex_LIN" }
},
{ name = "fox3DDF_Blin_NC",
	params = {"MatParamIndex_0"},
	packing = { 0x0,0x0,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN" }
},
{ name = "fox3DDF_Blin_SubNorm_NC",
	params = {"MatParamIndex_0","SubNormal_Blend","URepeat_UV","VRepeat_UV"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x8,0xc,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "SubNormalMap_Tex_NRM", "SubNormalMask_Tex_LIN" }
},
{ name = "fox3DDF_Blin_LayerBl_MaskUV",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3","URepeat_UV","VRepeat_UV","UShift_UV","VShift_UV"},
	packing = { 0x0,0x4,0x8,0xc,  0x10,0x14,0x18,0x1c },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Layer_Tex_SRGB", "LayerMask_Tex_LIN" }
},
{ name = "fox3DDF_Blin_LayerSRGBBl",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3","URepeat_UV","VRepeat_UV","UShift_UV","VShift_UV"},
	packing = { 0x0,0x4,0x8,0xc,  0x10,0x14,0x18,0x1c },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Layer_Tex_SRGB", "LayerMask_Tex_LIN" }
},
{ name = "fox3DDF_Blin_LayerSRGBBl_MaskUV",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3","URepeat_UV","VRepeat_UV","UShift_UV","VShift_UV"},
	packing = { 0x0,0x4,0x8,0xc,  0x10,0x14,0x18,0x1c },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Layer_Tex_SRGB", "LayerMask_Tex_LIN" }
},
{ name = "fox3DDF_Blin_LayerSRGBBl_SubNorm_MaskUV",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3","URepeat_UV","VRepeat_UV","UShift_UV","VShift_UV","SubNormal_Blend","URepeat_SubNorm_UV","VRepeat_SubNorm_UV"},
	packing = { 0x0,0x4,0x8,0xc,  0x10,0x14,0x18,0x1c,  0x20,0x24,0x28,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Layer_Tex_SRGB", "LayerMask_Tex_LIN", "SubNormalMap_Tex_NRM" }
},
{ name = "fox3DDF_Blin_MicroRoughness_LayerSRGBBl_SubNorm_MaskUV",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3","URepeat_UV","VRepeat_UV","UShift_UV","VShift_UV","SubNormal_Blend","URepeat_SubNorm_UV","VRepeat_SubNorm_UV","MinRoughness","RoughnessFrequency"},
	packing = { 0x0,0x4,0x8,0xc,  0x10,0x14,0x18,0x1c,  0x20,0x24,0x28,0x0,  0x2c,0x30,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Layer_Tex_SRGB", "LayerMask_Tex_LIN", "SubNormalMap_Tex_NRM" }
},
{ name = "fox3DDF_Blin_3MT_Dirty",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3"},
	packing = { 0x0,0x4,0x8,0xc },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "MatParamMap_Tex_LIN", "Dirty_Tex_LIN" }
},
{ name = "fox3DDF_Blin_VR",
	params = {"MatParamIndex_0"},
	packing = { 0x0,0x0,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN" }
},
{ name = "fox3DDF_Blin_LNM",
	params = {"MatParamIndex_0"},
	packing = { 0x0,0x0,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN" }
},
{ name = "fox3DDF_Blin_LNM_VR",
	params = {"MatParamIndex_0"},
	packing = { 0x0,0x0,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN" }
},
{ name = "fox3DDF_Blin_4MT_VR",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3"},
	packing = { 0x0,0x4,0x8,0xc },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "MatParamMap_Tex_LIN" }
},
{ name = "fox3DDF_Blin_4MT_LNM",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3"},
	packing = { 0x0,0x4,0x8,0xc },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "MatParamMap_Tex_LIN" }
},
{ name = "fox3DDF_Blin_4MT_LNM_VR",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3"},
	packing = { 0x0,0x4,0x8,0xc },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "MatParamMap_Tex_LIN" }
},
{ name = "fox3DDF_Blin_3MT_LNM",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2"},
	packing = { 0x0,0x4,0x8,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "MatParamMap_Tex_LIN" }
},
{ name = "fox3DDF_Blin_3MT_LNM_VR",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2"},
	packing = { 0x0,0x4,0x8,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "MatParamMap_Tex_LIN" }
},
{ name = "fox3DDF_Blin_2MT_VR",
	params = {"MatParamIndex_0","MatParamIndex_1"},
	packing = { 0x0,0x4,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "MatParamMap_Tex_LIN" }
},
{ name = "fox3DDF_Blin_2MT_LNM",
	params = {"MatParamIndex_0","MatParamIndex_1"},
	packing = { 0x0,0x4,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "MatParamMap_Tex_LIN" }
},
{ name = "fox3DDF_Blin_2MT_LNM_VR",
	params = {"MatParamIndex_0","MatParamIndex_1"},
	packing = { 0x0,0x4,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "MatParamMap_Tex_LIN" }
},
{ name = "fox3DDF_Blin_SubNorm_LNM",
	params = {"MatParamIndex_0","SubNormal_Blend","URepeat_UV","VRepeat_UV"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x8,0xc,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "SubNormalMap_Tex_NRM", "SubNormalMask_Tex_LIN" }
},
{ name = "fox3DDF_Blin_SubNorm_LNM_VR",
	params = {"MatParamIndex_0","SubNormal_Blend","URepeat_UV","VRepeat_UV"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x8,0xc,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "SubNormalMap_Tex_NRM", "SubNormalMask_Tex_LIN" }
},
{ name = "fox3DDF_Blin_SubNorm_4MT_LNM",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3","SubNormal_Blend","URepeat_UV","VRepeat_UV"},
	packing = { 0x0,0x4,0x8,0xc,  0x10,0x14,0x18,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "MatParamMap_Tex_LIN", "SubNormalMap_Tex_NRM", "SubNormalMask_Tex_LIN" }
},
{ name = "fox3DDF_Blin_SubNorm_3MT_LNM",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","SubNormal_Blend","URepeat_UV","VRepeat_UV"},
	packing = { 0x0,0x4,0x8,0x0,  0xc,0x10,0x14,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "MatParamMap_Tex_LIN", "SubNormalMap_Tex_NRM", "SubNormalMask_Tex_LIN" }
},
{ name = "fox3DDF_Blin_SubNorm_2MT_LNM",
	params = {"MatParamIndex_0","MatParamIndex_1","SubNormal_Blend","URepeat_UV","VRepeat_UV"},
	packing = { 0x0,0x4,0x0,0x0,  0x8,0xc,0x10,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "MatParamMap_Tex_LIN", "SubNormalMap_Tex_NRM", "SubNormalMask_Tex_LIN" }
},
{ name = "fox3DDF_Blin_SubNorm_2MT_LNM_VR",
	params = {"MatParamIndex_0","MatParamIndex_1","SubNormal_Blend","URepeat_UV","VRepeat_UV"},
	packing = { 0x0,0x4,0x0,0x0,  0x8,0xc,0x10,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "MatParamMap_Tex_LIN", "SubNormalMap_Tex_NRM", "SubNormalMask_Tex_LIN" }
},
{ name = "fox3DDF_Blin_LayerBl_LNM",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3","URepeat_UV","VRepeat_UV","UShift_UV","VShift_UV"},
	packing = { 0x0,0x4,0x8,0xc,  0x10,0x14,0x18,0x1c },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Layer_Tex_SRGB", "LayerMask_Tex_LIN" }
},
{ name = "fox3DDF_Blin_LayerBl_LNM_VR",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3","URepeat_UV","VRepeat_UV","UShift_UV","VShift_UV"},
	packing = { 0x0,0x4,0x8,0xc,  0x10,0x14,0x18,0x1c },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Layer_Tex_SRGB", "LayerMask_Tex_LIN" }
},
{ name = "fox3DDF_Blin_LayerBl_SubNorm_MaskUV_LNM",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3","URepeat_UV","VRepeat_UV","UShift_UV","VShift_UV","SubNormal_Blend","URepeat_SubNorm_UV","VRepeat_SubNorm_UV"},
	packing = { 0x0,0x4,0x8,0xc,  0x10,0x14,0x18,0x1c,  0x20,0x24,0x28,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Layer_Tex_SRGB", "LayerMask_Tex_LIN", "SubNormalMap_Tex_NRM" }
},
{ name = "fox3DDF_Incidence_LNM",
	params = {"MatParamIndex_0","Incidence_Roughness","Incidence_Color"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x0,0x0,0x0,  0x8,0x9,0xa,0xb },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN" }
},
{ name = "fox3DDF_Incidence_NrmUV_Dirty_LNM",
	params = {"MatParamIndex_0","Incidence_Roughness","Incidence_Color"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x0,0x0,0x0,  0x8,0x9,0xa,0xb },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Dirty_Tex_LIN" }
},
{ name = "fox3DDF_Incidence_NrmUV_Dirty_LNM_VR",
	params = {"MatParamIndex_0","Incidence_Roughness","Incidence_Color"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x0,0x0,0x0,  0x8,0x9,0xa,0xb },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Dirty_Tex_LIN" }
},
{ name = "fox3DDF_Cloth_NC_LNM",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3","SubNormal_Blend","URepeat_UV","VRepeat_UV","Incidence_Roughness","Incidence_Color"},
	packing = { 0x0,0x4,0x8,0xc,  0x10,0x14,0x18,0x0,  0x1c,0x0,0x0,0x0,  0x20,0x21,0x22,0x23 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Layer_Tex_SRGB", "LayerMask_Tex_LIN", "SubNormalMap_Tex_NRM" }
},
{ name = "fox3DDF_Dirty_LNM",
	params = {"MatParamIndex_0"},
	packing = { 0x0,0x0,0x0,0x0,  0x0,0x0,0x0,0x0,  0x0,0x0,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Dirty_Tex_LIN" }
},
{ name = "fox3DDF_Blin_4MT_Dirty_VR",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3"},
	packing = { 0x0,0x4,0x8,0xc },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "MatParamMap_Tex_LIN", "Dirty_Tex_LIN" }
},
{ name = "fox3DDF_Blin_4MT_Dirty_LNM",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3"},
	packing = { 0x0,0x4,0x8,0xc },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "MatParamMap_Tex_LIN", "Dirty_Tex_LIN" }
},
{ name = "fox3DDF_Blin_4MT_Dirty_LNM_VR",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3"},
	packing = { 0x0,0x4,0x8,0xc },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "MatParamMap_Tex_LIN", "Dirty_Tex_LIN" }
},
{ name = "fox3DDF_Blin_SubNorm_Dirty_LNM",
	params = {"MatParamIndex_0","SubNormal_Blend","URepeat_UV","VRepeat_UV"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x8,0xc,0x0,  0x0,0x0,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "SubNormalMap_Tex_NRM", "SubNormalMask_Tex_LIN", "Dirty_Tex_LIN" }
},
{ name = "fox3DDF_Blin_LayerMul_Dirty_LNM",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3","URepeat_UV","VRepeat_UV","UShift_UV","VShift_UV"},
	packing = { 0x0,0x4,0x8,0xc,  0x10,0x14,0x18,0x1c,  0x0,0x0,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Layer_Tex_SRGB", "LayerMask_Tex_LIN", "Dirty_Tex_LIN" }
},
{ name = "fox3DDF_Cloth_NC_Dirty_LNM",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3","SubNormal_Blend","URepeat_UV","VRepeat_UV","Incidence_Roughness","Incidence_Color"},
	packing = { 0x0,0x4,0x8,0xc,  0x10,0x14,0x18,0x0,  0x1c,0x0,0x0,0x0,  0x20,0x21,0x22,0x23 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Layer_Tex_SRGB", "LayerMask_Tex_LIN", "SubNormalMap_Tex_NRM", "Dirty_Tex_LIN" }
},
{ name = "fox3DDF_MicroRoughness_LNM",
	params = {"MatParamIndex_0","MinRoughness","RoughnessFrequency"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x8,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN" }
},
{ name = "fox3DDF_Blin_Translucent_LNM",
	params = {"MatParamIndex_0"},
	packing = { 0x0,0x0,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Translucent_Tex_LIN" }
},
{ name = "fox3DDF_Blin_Translucent_DirectiveAlpha_NC_LNM",
	params = {"MatParamIndex_0","StartFadeDot","EndFadeDot"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x8,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Translucent_Tex_LIN" }
},
{ name = "fox3DDF_Skin_LNM",
	params = {"MatParamIndex_0","Incidence_Roughness","Incidence_Color"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x0,0x0,0x0,  0x8,0x9,0xa,0xb },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Translucent_Tex_LIN" }
},
{ name = "fox3DDF_Skin_LNM_VR",
	params = {"MatParamIndex_0","Incidence_Roughness","Incidence_Color"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x0,0x0,0x0,  0x8,0x9,0xa,0xb },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Translucent_Tex_LIN" }
},
{ name = "fox3DDF_Skin_Dirty_LNM",
	params = {"MatParamIndex_0","Incidence_Roughness","Incidence_Color"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x0,0x0,0x0,  0x8,0x9,0xa,0xb },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Translucent_Tex_LIN", "Dirty_Tex_LIN" }
},
{ name = "fox3DDF_Skin_Tension_LNM",
	params = {"MatParamIndex_0","Incidence_Roughness","TensionRate","TensionShift","TensionController","Incidence_Color"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x8,0xc,0x10,  0x14,0x15,0x16,0x17 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Translucent_Tex_LIN", "TensionSubNormalMap_Tex_NRM" }
},
{ name = "fox3DDF_Skin_Tension_Dirty_LNM",
	params = {"MatParamIndex_0","Incidence_Roughness","TensionRate","TensionShift","TensionController","Incidence_Color"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x8,0xc,0x10,  0x14,0x15,0x16,0x17 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Translucent_Tex_LIN", "TensionSubNormalMap_Tex_NRM", "Dirty_Tex_LIN" }
},
{ name = "fox3DDF_Eye_LNM",
	params = {"MatParamIndex_0","HeightScale"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x0,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Translucent_Tex_LIN", "ViewReflection_Tex_LIN", "LensHeight_Tex_LIN", "Base_Tex2_SRGB" }
},
{ name = "fox3DDF_Eye_LNM_VR",
	params = {"MatParamIndex_0","HeightScale"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x0,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Translucent_Tex_LIN", "ViewReflection_Tex_LIN", "LensHeight_Tex_LIN", "Base_Tex2_SRGB" }
},
{ name = "fox3DDF_NormalWave_LNM",
	params = {"MatParamIndex_0","Specular_Value","Roughness_Value","Translucent_Value","WindDir","WindAnimTime","WindAmplitude","WeightDiffusion","WeightOffset","WindOffset","OldWindDir","NormalRotRate","OldWindAnimTime","OldWindAmplitude","WindRandAmplitude"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x8,0xc,0x0,  0x10,0x11,0x12,0x0,  0x14,0x18,0x1c,0x20,  0x24,0x25,0x26,0x0,  0x28,0x29,0x2a,0x2c,  0x30,0x34,0x38,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM" }
},
{ name = "fox3DDF_NormalWave_DirectiveAlpha_LNM",
	params = {"MatParamIndex_0","Specular_Value","Roughness_Value","Translucent_Value","WindDir","WindAnimTime","WindAmplitude","WeightDiffusion","WeightOffset","WindOffset","OldWindDir","NormalRotRate","OldWindAnimTime","OldWindAmplitude","WindRandAmplitude","StartFadeDot","EndFadeDot"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x8,0xc,0x0,  0x10,0x11,0x12,0x0,  0x14,0x18,0x1c,0x20,  0x24,0x25,0x26,0x0,  0x28,0x29,0x2a,0x2c,  0x30,0x34,0x38,0x0,  0x3c,0x40,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM" }
},
{ name = "fox3DDF_Dirty_UVSCroll_LNM",
	params = {"MatParamIndex_0","UShift_UV","VShift_UV"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x8,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Dirty_Tex_LIN" }
},
{ name = "fox3DDF_LightCover_LNM",
	params = {"MatParamIndex_0"},
	packing = { 0x0,0x0,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "InternalNormalMap_Tex_NRM", "CoverTranslucentMap_Tex_LIN" }
},
{ name = "fox3DDF_LightCover_LNM_VR",
	params = {"MatParamIndex_0"},
	packing = { 0x0,0x0,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "InternalNormalMap_Tex_NRM", "CoverTranslucentMap_Tex_LIN" }
},
{ name = "fox3DFW_Glass_LNM",
	params = {"MatParamIndex_0","ReflectionColor","GlassColor","GlassRoughness"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x5,0x6,0x0,  0x8,0x9,0xa,0xb,  0x0,0xc,0x0,0x0 },
	textures = { "Base_Tex_LIN", "NormalMap_Tex_NRM", "GlassReflection_Tex_SRGB" }
},
{ name = "fox3DFW_Glass_LNM_VR",
	params = {"MatParamIndex_0","ReflectionColor","GlassColor","GlassRoughness"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x5,0x6,0x0,  0x8,0x9,0xa,0xb,  0x0,0xc,0x0,0x0 },
	textures = { "Base_Tex_LIN", "NormalMap_Tex_NRM", "GlassReflection_Tex_SRGB" }
},
{ name = "fox3DFW_Glass_CommonRef_LNM",
	params = {"MatParamIndex_0","ReflectionColor","GlassColor","GlassRoughness"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x5,0x6,0x0,  0x8,0x9,0xa,0xb,  0x0,0xc,0x0,0x0 },
	textures = { "Base_Tex_LIN", "NormalMap_Tex_NRM", "GlassReflection_Tex_SRGB" }
},
{ name = "fox3DFW_Glass_CommonRef_LNM_VR",
	params = {"MatParamIndex_0","ReflectionColor","GlassColor","GlassRoughness"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x5,0x6,0x0,  0x8,0x9,0xa,0xb,  0x0,0xc,0x0,0x0 },
	textures = { "Base_Tex_LIN", "NormalMap_Tex_NRM", "GlassReflection_Tex_SRGB" }
},
{ name = "fox3DFW_WaterCover_LNM",
	params = {"MatParamIndex_0","WaterTrans","WaterRoughness","Incidence_Roughness","Incidence_Color","SubNormal_Blend","URepeat_UV","VRepeat_UV","UShift_UV","VShift_UV"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x8,0x0,0x0,  0xc,0x0,0x0,0x0,  0x10,0x11,0x12,0x13,  0x14,0x18,0x1c,0x0,  0x20,0x24,0x0,0x0 },
	textures = { "Base_Tex_LIN", "NormalMap_Tex_NRM", "SpheremapReflection_Tex_LIN", "SubNormalMap_Tex_NRM", "SubNormalMask_Tex_LIN", "AnimMask_Tex_LIN" }
},
{ name = "fox3DFW_WaterCover_LNM_VR",
	params = {"MatParamIndex_0","WaterTrans","WaterRoughness","Incidence_Roughness","Incidence_Color","SubNormal_Blend","URepeat_UV","VRepeat_UV","UShift_UV","VShift_UV"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x8,0x0,0x0,  0xc,0x0,0x0,0x0,  0x10,0x11,0x12,0x13,  0x14,0x18,0x1c,0x0,  0x20,0x24,0x0,0x0 },
	textures = { "Base_Tex_LIN", "NormalMap_Tex_NRM", "SpheremapReflection_Tex_LIN", "SubNormalMap_Tex_NRM", "SubNormalMask_Tex_LIN", "AnimMask_Tex_LIN" }
},
{ name = "fox3DDC_Blin_LNM",
	params = {"MatParamIndex_0"},
	packing = { 0x0,0x0,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN" }
},
{ name = "fox3DDC_Blin_LNM_VR",
	params = {"MatParamIndex_0"},
	packing = { 0x0,0x0,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN" }
},
{ name = "fox3DDF_Blin_NrmUV_LNM",
	params = {"MatParamIndex_0"},
	packing = { 0x0,0x0,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN" }
},
{ name = "fox3DDF_Blin_NC_LNM",
	params = {"MatParamIndex_0"},
	packing = { 0x0,0x0,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN" }
},
{ name = "fox3DDF_Blin_NrmUV_NC_LNM",
	params = {"MatParamIndex_0"},
	packing = { 0x0,0x0,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN" }
},
{ name = "fox3DDF_Blin_3MT_NrmUV_LNM",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2"},
	packing = { 0x0,0x4,0x8,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "MatParamMap_Tex_LIN" }
},
{ name = "fox3DDF_Blin_2MT_NrmUV_LNM",
	params = {"MatParamIndex_0","MatParamIndex_1"},
	packing = { 0x0,0x4,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "MatParamMap_Tex_LIN" }
},
{ name = "fox3DDF_Blin_2MT_NrmUV_LNM_VR",
	params = {"MatParamIndex_0","MatParamIndex_1"},
	packing = { 0x0,0x4,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "MatParamMap_Tex_LIN" }
},
{ name = "fox3DDF_Blin_SubNorm_NrmUV_LNM",
	params = {"MatParamIndex_0","SubNormal_Blend","URepeat_UV","VRepeat_UV"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x8,0xc,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "SubNormalMap_Tex_NRM", "SubNormalMask_Tex_LIN" }
},
{ name = "fox3DDF_Blin_SubNorm_NrmUV_LNM_VR",
	params = {"MatParamIndex_0","SubNormal_Blend","URepeat_UV","VRepeat_UV"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x8,0xc,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "SubNormalMap_Tex_NRM", "SubNormalMask_Tex_LIN" }
},
{ name = "fox3DDF_Blin_SubNorm_NC_LNM",
	params = {"MatParamIndex_0","SubNormal_Blend","URepeat_UV","VRepeat_UV"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x8,0xc,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "SubNormalMap_Tex_NRM", "SubNormalMask_Tex_LIN" }
},
{ name = "fox3DDF_Blin_SubNorm_NrmUV_NC_LNM",
	params = {"MatParamIndex_0","SubNormal_Blend","URepeat_UV","VRepeat_UV"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x8,0xc,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "SubNormalMap_Tex_NRM", "SubNormalMask_Tex_LIN" }
},
{ name = "fox3DDF_Blin_SubNormAnim_NC_LNM",
	params = {"MatParamIndex_0","SubNormal_Blend","URepeat_UV","VRepeat_UV","UShift_UV","VShift_UV"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x8,0xc,0x0,  0x10,0x14,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "SubNormalMap_Tex_NRM", "SubNormalMask_Tex_LIN" }
},
{ name = "fox3DDF_Blin_LayerBl_MaskUV_LNM",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3","URepeat_UV","VRepeat_UV","UShift_UV","VShift_UV"},
	packing = { 0x0,0x4,0x8,0xc,  0x10,0x14,0x18,0x1c },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Layer_Tex_SRGB", "LayerMask_Tex_LIN" }
},
{ name = "fox3DDF_Blin_LayerSRGBBl_LNM",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3","URepeat_UV","VRepeat_UV","UShift_UV","VShift_UV"},
	packing = { 0x0,0x4,0x8,0xc,  0x10,0x14,0x18,0x1c },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Layer_Tex_SRGB", "LayerMask_Tex_LIN" }
},
{ name = "fox3DDF_Blin_LayerSRGBBl_MaskUV_LNM",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3","URepeat_UV","VRepeat_UV","UShift_UV","VShift_UV"},
	packing = { 0x0,0x4,0x8,0xc,  0x10,0x14,0x18,0x1c },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Layer_Tex_SRGB", "LayerMask_Tex_LIN" }
},
{ name = "fox3DDF_Blin_LayerSRGBBl_MaskUV_NrmUV_LNM",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3","URepeat_UV","VRepeat_UV","UShift_UV","VShift_UV"},
	packing = { 0x0,0x4,0x8,0xc,  0x10,0x14,0x18,0x1c },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Layer_Tex_SRGB", "LayerMask_Tex_LIN" }
},
{ name = "fox3DDF_Blin_LayerSRGBBl_SubNorm_MaskUV_LNM",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3","URepeat_UV","VRepeat_UV","UShift_UV","VShift_UV","SubNormal_Blend","URepeat_SubNorm_UV","VRepeat_SubNorm_UV"},
	packing = { 0x0,0x4,0x8,0xc,  0x10,0x14,0x18,0x1c,  0x20,0x24,0x28,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Layer_Tex_SRGB", "LayerMask_Tex_LIN", "SubNormalMap_Tex_NRM" }
},
{ name = "fox3DDF_Blin_LayerBl_2MT_MaskUV_LNM",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3","URepeat_UV","VRepeat_UV","UShift_UV","VShift_UV"},
	packing = { 0x0,0x4,0x8,0xc,  0x10,0x14,0x18,0x1c },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "MatParamMap_Tex_LIN", "Layer_Tex_SRGB", "LayerMask_Tex_LIN" }
},
{ name = "fox3DDF_Blin_LayerBl_2MT_MaskUV_LNM_VR",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3","URepeat_UV","VRepeat_UV","UShift_UV","VShift_UV"},
	packing = { 0x0,0x4,0x8,0xc,  0x10,0x14,0x18,0x1c },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "MatParamMap_Tex_LIN", "Layer_Tex_SRGB", "LayerMask_Tex_LIN" }
},
{ name = "fox3DDF_Blin_LayerBl_3MT_LNM",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3","URepeat_UV","VRepeat_UV","UShift_UV","VShift_UV"},
	packing = { 0x0,0x4,0x8,0xc,  0x10,0x14,0x18,0x1c },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "MatParamMap_Tex_LIN", "Layer_Tex_SRGB", "LayerMask_Tex_LIN" }
},
{ name = "fox3DDF_Blin_LayerMul_3MT_LNM",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3","URepeat_UV","VRepeat_UV","UShift_UV","VShift_UV"},
	packing = { 0x0,0x4,0x8,0xc,  0x10,0x14,0x18,0x1c },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "MatParamMap_Tex_LIN", "Layer_Tex_SRGB", "LayerMask_Tex_LIN" }
},
{ name = "fox3DDF_Blin_LayerMul_3MT_LNM_VR",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3","URepeat_UV","VRepeat_UV","UShift_UV","VShift_UV"},
	packing = { 0x0,0x4,0x8,0xc,  0x10,0x14,0x18,0x1c },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "MatParamMap_Tex_LIN", "Layer_Tex_SRGB", "LayerMask_Tex_LIN" }
},
{ name = "fox3DDF_Blin_LayerSRGBBl_2MT_MaskUV_LNM",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3","URepeat_UV","VRepeat_UV","UShift_UV","VShift_UV"},
	packing = { 0x0,0x4,0x8,0xc,  0x10,0x14,0x18,0x1c },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "MatParamMap_Tex_LIN", "Layer_Tex_SRGB", "LayerMask_Tex_LIN" }
},
{ name = "fox3DDF_Blin_LayerSRGBBl_SubNorm_2MT_MaskUV_LNM",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3","URepeat_UV","VRepeat_UV","UShift_UV","VShift_UV","SubNormal_Blend","URepeat_SubNorm_UV","VRepeat_SubNorm_UV"},
	packing = { 0x0,0x4,0x8,0xc,  0x10,0x14,0x18,0x1c,  0x20,0x24,0x28,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "MatParamMap_Tex_LIN", "Layer_Tex_SRGB", "LayerMask_Tex_LIN", "SubNormalMap_Tex_NRM" }
},
{ name = "fox3DDF_Blin_LayerSRGBBl_2SubNorm_NrmUV_LNM",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3","URepeat_UV","VRepeat_UV","UShift_UV","VShift_UV","SubNormal_Blend","URepeat_SubNorm_UV","VRepeat_SubNorm_UV","SmallSubNormal_Blend","URepeat_SmallSubNorm_UV","VRepeat_SmallSubNorm_UV"},
	packing = { 0x0,0x4,0x8,0xc,  0x10,0x14,0x18,0x1c,  0x20,0x24,0x28,0x0,  0x2c,0x30,0x34,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Layer_Tex_SRGB", "LayerMask_Tex_LIN", "SubNormalMap_Tex_NRM", "SmallSubNormalMap_Tex_NRM" }
},
{ name = "fox3DDF_Cloth_LNM",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3","SubNormal_Blend","URepeat_UV","VRepeat_UV","Incidence_Roughness","Incidence_Color"},
	packing = { 0x0,0x4,0x8,0xc,  0x10,0x14,0x18,0x0,  0x1c,0x0,0x0,0x0,  0x20,0x21,0x22,0x23 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Layer_Tex_SRGB", "LayerMask_Tex_LIN", "SubNormalMap_Tex_NRM" }
},
{ name = "fox3DDF_Blin_3MT_Dirty_VR",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3"},
	packing = { 0x0,0x4,0x8,0xc },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "MatParamMap_Tex_LIN", "Dirty_Tex_LIN" }
},
{ name = "fox3DDF_Blin_3MT_Dirty_LNM",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3"},
	packing = { 0x0,0x4,0x8,0xc },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "MatParamMap_Tex_LIN", "Dirty_Tex_LIN" }
},
{ name = "fox3DDF_Blin_3MT_Dirty_LNM_VR",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3"},
	packing = { 0x0,0x4,0x8,0xc },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "MatParamMap_Tex_LIN", "Dirty_Tex_LIN" }
},
{ name = "fox3DDF_Blin_2MT_Dirty_LNM",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3"},
	packing = { 0x0,0x4,0x8,0xc },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "MatParamMap_Tex_LIN", "Dirty_Tex_LIN" }
},
{ name = "fox3DDF_Blin_2MT_Dirty_LNM_VR",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3"},
	packing = { 0x0,0x4,0x8,0xc },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "MatParamMap_Tex_LIN", "Dirty_Tex_LIN" }
},
{ name = "fox3DDF_Blin_Incidence_LayerMul_3MT_Dirty_LNM",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3","URepeat_UV","VRepeat_UV","UShift_UV","VShift_UV","Incidence_Roughness","Incidence_Color"},
	packing = { 0x0,0x4,0x8,0xc,  0x10,0x14,0x18,0x1c,  0x20,0x0,0x0,0x0,  0x24,0x25,0x26,0x27 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "MatParamMap_Tex_LIN", "Layer_Tex_SRGB", "LayerMask_Tex_LIN", "Dirty_Tex_LIN" }
},
{ name = "fox3DDF_Cloth_Dirty_LNM",
	params = {"MatParamIndex_0","MatParamIndex_1","MatParamIndex_2","MatParamIndex_3","SubNormal_Blend","URepeat_UV","VRepeat_UV","Incidence_Roughness","Incidence_Color"},
	packing = { 0x0,0x4,0x8,0xc,  0x10,0x14,0x18,0x0,  0x1c,0x0,0x0,0x0,  0x20,0x21,0x22,0x23 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Layer_Tex_SRGB", "LayerMask_Tex_LIN", "SubNormalMap_Tex_NRM", "Dirty_Tex_LIN" }
},
{ name = "fox3DDF_Blin_Translucent_NC_LNM",
	params = {"MatParamIndex_0"},
	packing = { 0x0,0x0,0x0,0x0 },
	textures = { "Base_Tex_SRGB", "NormalMap_Tex_NRM", "SpecularMap_Tex_LIN", "Translucent_Tex_LIN" }
},
{ name = "fox3DFW_GlassColor_LNM",
	params = {"MatParamIndex_0","ReflectionColor","GlassColor","GlassRoughness"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x5,0x6,0x0,  0x8,0x9,0xa,0xb,  0x0,0xc,0x0,0x0 },
	textures = { "Base_Tex_LIN", "NormalMap_Tex_NRM", "GlassReflection_Tex_SRGB" }
},
{ name = "fox3DFW_GlassColor_LNM_VR",
	params = {"MatParamIndex_0","ReflectionColor","GlassColor","GlassRoughness"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x5,0x6,0x0,  0x8,0x9,0xa,0xb,  0x0,0xc,0x0,0x0 },
	textures = { "Base_Tex_LIN", "NormalMap_Tex_NRM", "GlassReflection_Tex_SRGB" }
},
{ name = "fox3DFW_GlassColor_CommonRef_LNM",
	params = {"MatParamIndex_0","ReflectionColor","GlassColor","GlassRoughness"},
	packing = { 0x0,0x0,0x0,0x0,  0x4,0x5,0x6,0x0,  0x8,0x9,0xa,0xb,  0x0,0xc,0x0,0x0 },
	textures = { "Base_Tex_LIN", "NormalMap_Tex_NRM", "GlassReflection_Tex_SRGB" }
}}
local ShaderAssignList = {
	{ technique="ModelDefault",type="Deferred",variation="", shader="GBuffersBase"},
	{ technique="fox3DDF_Blin",type="Forward",variation="", shader="fox3dfw_blin"},
	{ technique="fox3DDF_Blin_LNM",type="Forward",variation="", shader="fox3dfw_blin_ln"},
	{ technique="fox3DDF_Blin_NrmUV_LNM",type="Forward",variation="", shader="fox3dfw_blin_nu_ln"},
	{ technique="fox3DDF_Blin",type="Deferred",variation="", shader="fox3ddf_blin"},
	{ technique="fox3DDF_Blin_NC",type="Deferred",variation="", shader="fox3ddf_blin_nc"},
	{ technique="fox3DDF_Blin_VR",type="Deferred",variation="", shader="fox3ddf_blin_vr"},
	{ technique="fox3DDF_Blin_LNM",type="Deferred",variation="", shader="fox3ddf_blin_ln"},
	{ technique="fox3DDF_Blin_NrmUV_LNM",type="Deferred",variation="", shader="fox3ddf_blin_nu_ln"},
	{ technique="fox3DDF_Blin_NC_LNM",type="Deferred",variation="", shader="fox3ddf_blin_nc_ln"},
	{ technique="fox3DDF_Blin_NrmUV_NC_LNM",type="Deferred",variation="", shader="fox3ddf_blin_nu_nc_ln"},
	{ technique="fox3DDF_Blin_LNM_VR",type="Deferred",variation="", shader="fox3ddf_blin_ln_vr"},
	{ technique="fox3DDF_Blin",type="CloneDeferred",variation="", shader="fox3ddf_blin_clone"},
	{ technique="fox3DDF_Blin_NC",type="CloneDeferred",variation="", shader="fox3ddf_blin_clone_nc"},
	{ technique="fox3DDF_Blin_VR",type="CloneDeferred",variation="", shader="fox3ddf_blin_clone_vr"},
	{ technique="fox3DDF_Blin_LNM",type="CloneDeferred",variation="", shader="fox3ddf_blin_clone_ln"},
	{ technique="fox3DDF_Blin_NC_LNM",type="CloneDeferred",variation="", shader="fox3ddf_blin_clone_nc_ln"},
	{ technique="fox3DDF_Blin_LNM_VR",type="CloneDeferred",variation="", shader="fox3ddf_blin_clone_ln_vr"},
	{ technique="fox3DDF_Blin_4MT",type="Forward",variation="", shader="ModelForward"},
	{ technique="fox3DDF_Blin_4MT",type="Deferred",variation="", shader="fox3ddf_blin_4mt"},
	{ technique="fox3DDF_Blin_4MT_VR",type="Deferred",variation="", shader="fox3ddf_blin_4mt_vr"},
	{ technique="fox3DDF_Blin_4MT_LNM",type="Deferred",variation="", shader="fox3ddf_blin_4mt_ln"},
	{ technique="fox3DDF_Blin_4MT_LNM_VR",type="Deferred",variation="", shader="fox3ddf_blin_4mt_ln_vr"},
	{ technique="fox3DDF_Blin_3MT_LNM",type="Deferred",variation="", shader="fox3ddf_blin_3mt_ln"},
	{ technique="fox3DDF_Blin_3MT_NrmUV_LNM",type="Deferred",variation="", shader="fox3ddf_blin_3mt_nu_ln"},
	{ technique="fox3DDF_Blin_3MT_LNM_VR",type="Deferred",variation="", shader="fox3ddf_blin_3mt_ln_vr"},
	{ technique="fox3DDF_Blin_2MT",type="Forward",variation="", shader="ModelForward"},
	{ technique="fox3DDF_Blin_2MT",type="Deferred",variation="", shader="fox3ddf_blin_2mt"},
	{ technique="fox3DDF_Blin_2MT_VR",type="Deferred",variation="", shader="fox3ddf_blin_2mt_vr"},
	{ technique="fox3DDF_Blin_2MT_LNM",type="Deferred",variation="", shader="fox3ddf_blin_2mt_ln"},
	{ technique="fox3DDF_Blin_2MT_NrmUV_LNM",type="Deferred",variation="", shader="fox3ddf_blin_2mt_nu_ln"},
	{ technique="fox3DDF_Blin_2MT_LNM_VR",type="Deferred",variation="", shader="fox3ddf_blin_2mt_ln_vr"},
	{ technique="fox3DDF_Blin_2MT_NrmUV_LNM_VR",type="Deferred",variation="", shader="fox3ddf_blin_2mt_nu_ln_vr"},
	{ technique="fox3DDF_Blin_SubNorm",type="Forward",variation="", shader="ModelForward"},
	{ technique="fox3DDF_Blin_SubNorm",type="Deferred",variation="", shader="fox3ddf_blin_subnorm"},
	{ technique="fox3DDF_Blin_SubNorm_NC",type="Deferred",variation="", shader="fox3ddf_blin_subnorm_nc"},
	{ technique="fox3DDF_Blin_SubNorm_LNM",type="Deferred",variation="", shader="fox3ddf_blin_subnorm_ln"},
	{ technique="fox3DDF_Blin_SubNorm_NrmUV_LNM",type="Deferred",variation="", shader="fox3ddf_blin_subnorm_nu_ln"},
	{ technique="fox3DDF_Blin_SubNorm_NC_LNM",type="Deferred",variation="", shader="fox3ddf_blin_subnorm_nc_ln"},
	{ technique="fox3DDF_Blin_SubNorm_NrmUV_NC_LNM",type="Deferred",variation="", shader="fox3ddf_blin_subnorm_nu_nc_ln"},
	{ technique="fox3DDF_Blin_SubNorm_LNM_VR",type="Deferred",variation="", shader="fox3ddf_blin_subnorm_ln_vr"},
	{ technique="fox3DDF_Blin_SubNorm_NrmUV_LNM_VR",type="Deferred",variation="", shader="fox3ddf_blin_subnorm_nu_ln_vr"},
	{ technique="fox3DDF_Blin_SubNormAnim",type="Forward",variation="", shader="ModelForward"},
	{ technique="fox3DDF_Blin_SubNormAnim",type="Deferred",variation="", shader="fox3ddf_blin_subnoranimm"},
	{ technique="fox3DDF_Blin_SubNormAnim_NC_LNM",type="Deferred",variation="", shader="fox3ddf_blin_subnoranimm_nc_ln"},
	{ technique="fox3DDF_Blin_SubNorm_4MT_LNM",type="Deferred",variation="", shader="fox3ddf_blin_4mt_subnorm_ln"},
	{ technique="fox3DDF_Blin_SubNorm_3MT_LNM",type="Deferred",variation="", shader="fox3ddf_blin_3mt_subnorm_ln"},
	{ technique="fox3DDF_Blin_SubNorm_2MT_LNM",type="Deferred",variation="", shader="fox3ddf_blin_2mt_subnorm_ln"},
	{ technique="fox3DDF_Blin_SubNorm_2MT_LNM_VR",type="Deferred",variation="", shader="fox3ddf_blin_2mt_subnorm_ln_vr"},
	{ technique="fox3DDF_Blin_LayerBl_MaskUV",type="Deferred",variation="", shader="fox3ddf_blin_layer_bl_mu"},
	{ technique="fox3DDF_Blin_LayerSRGBBl",type="Deferred",variation="", shader="fox3ddf_blin_layer_sbl"},
	{ technique="fox3DDF_Blin_LayerSRGBBl_MaskUV",type="Deferred",variation="", shader="fox3ddf_blin_layer_sbl_mu"},
	{ technique="fox3DDF_Blin_LayerBl_LNM",type="Deferred",variation="", shader="fox3ddf_blin_layer_bl_ln"},
	{ technique="fox3DDF_Blin_LayerBl_MaskUV_LNM",type="Deferred",variation="", shader="fox3ddf_blin_layer_bl_mu_ln"},
	{ technique="fox3DDF_Blin_LayerSRGBBl_LNM",type="Deferred",variation="", shader="fox3ddf_blin_layer_sbl_ln"},
	{ technique="fox3DDF_Blin_LayerSRGBBl_MaskUV_LNM",type="Deferred",variation="", shader="fox3ddf_blin_layer_sbl_mu_ln"},
	{ technique="fox3DDF_Blin_LayerSRGBBl_MaskUV_NrmUV_LNM",type="Deferred",variation="", shader="fox3ddf_blin_layer_sbl_mu_nu_ln"},
	{ technique="fox3DDF_Blin_LayerBl_LNM_VR",type="Deferred",variation="", shader="fox3ddf_blin_layer_bl_ln_vr"},
	{ technique="fox3DDF_Blin_LayerSRGBBl_SubNorm_MaskUV",type="Deferred",variation="", shader="fox3ddf_blin_layersb_subnm_mu"},
	{ technique="fox3DDF_Blin_LayerBl_SubNorm_MaskUV_LNM",type="Deferred",variation="", shader="fox3ddf_blin_layerb_subnm_mu_ln"},
	{ technique="fox3DDF_Blin_LayerSRGBBl_SubNorm_MaskUV_LNM",type="Deferred",variation="", shader="fox3ddf_blin_layersb_subnm_mu_ln"},
	{ technique="fox3DDF_Blin_MicroRoughness_LayerSRGBBl_SubNorm_MaskUV",type="Deferred",variation="", shader="fox3ddf_micro_layersb_snm_mu"},
	{ technique="fox3DDF_Blin_LayerBl_2MT_MaskUV_LNM",type="Deferred",variation="", shader="fox3ddf_blin_2mt_layerb_mu_ln"},
	{ technique="fox3DDF_Blin_LayerBl_3MT_LNM",type="Deferred",variation="", shader="fox3ddf_blin_3mt_layerb_ln"},
	{ technique="fox3DDF_Blin_LayerMul_3MT_LNM",type="Deferred",variation="", shader="fox3ddf_blin_3mt_layerm_ln"},
	{ technique="fox3DDF_Blin_LayerSRGBBl_2MT_MaskUV_LNM",type="Deferred",variation="", shader="fox3ddf_blin_2mt_layersb_mu_ln"},
	{ technique="fox3DDF_Blin_LayerBl_2MT_MaskUV_LNM_VR",type="Deferred",variation="", shader="fox3ddf_blin_2mt_layerb_mu_ln_vr"},
	{ technique="fox3DDF_Blin_LayerMul_3MT_LNM_VR",type="Deferred",variation="", shader="fox3ddf_blin_3mt_layerm_ln_vr"},
	{ technique="fox3DDF_Blin_LayerSRGBBl_SubNorm_2MT_MaskUV_LNM",type="Deferred",variation="", shader="fox3ddf_blin_2mt_lysb_sbn_mu_ln"},
	{ technique="fox3DDF_Blin_LayerSRGBBl_2SubNorm_NrmUV_LNM",type="Deferred",variation="", shader="fox3ddf_blin_ly_sbl_2snm_nu_ln"},
	{ technique="fox3DDF_Incidence_LNM",type="Deferred",variation="", shader="fox3ddf_blin_incidence_ln"},
	{ technique="fox3DDF_Incidence_NrmUV_Dirty_LNM",type="Deferred",variation="", shader="fox3ddf_blin_ic_nu_dirty_ln"},
	{ technique="fox3DDF_Incidence_NrmUV_Dirty_LNM_VR",type="Deferred",variation="", shader="fox3ddf_blin_ic_nu_dirty_ln_vr"},
	{ technique="fox3DDF_Cloth_NC_LNM",type="Deferred",variation="", shader="fox3ddf_cloth_nc_ln"},
	{ technique="fox3DDF_Cloth_LNM",type="Deferred",variation="", shader="fox3ddf_cloth_ln"},
	{ technique="fox3DDF_Dirty",type="Forward",variation="", shader="ModelForward"},
	{ technique="fox3DDF_Dirty",type="Deferred",variation="", shader="fox3ddf_blin_dirty"},
	{ technique="fox3DDF_Dirty_LNM",type="Deferred",variation="", shader="fox3ddf_blin_dirty_ln"},
	{ technique="fox3DDF_Blin_4MT_Dirty",type="Forward",variation="", shader="ModelForward"},
	{ technique="fox3DDF_Blin_4MT_Dirty",type="Deferred",variation="", shader="fox3ddf_blin_4mt_dirty"},
	{ technique="fox3DDF_Blin_3MT_Dirty",type="Deferred",variation="", shader="fox3ddf_blin_3mt_dirty"},
	{ technique="fox3DDF_Blin_4MT_Dirty_VR",type="Deferred",variation="", shader="fox3ddf_blin_4mt_dirty_vr"},
	{ technique="fox3DDF_Blin_3MT_Dirty_VR",type="Deferred",variation="", shader="fox3ddf_blin_3mt_dirty_vr"},
	{ technique="fox3DDF_Blin_4MT_Dirty_LNM",type="Deferred",variation="", shader="fox3ddf_blin_4mt_dirty_ln"},
	{ technique="fox3DDF_Blin_3MT_Dirty_LNM",type="Deferred",variation="", shader="fox3ddf_blin_3mt_dirty_ln"},
	{ technique="fox3DDF_Blin_2MT_Dirty_LNM",type="Deferred",variation="", shader="fox3ddf_blin_2mt_dirty_ln"},
	{ technique="fox3DDF_Blin_4MT_Dirty_LNM_VR",type="Deferred",variation="", shader="fox3ddf_blin_4mt_dirty_ln_vr"},
	{ technique="fox3DDF_Blin_3MT_Dirty_LNM_VR",type="Deferred",variation="", shader="fox3ddf_blin_3mt_dirty_ln_vr"},
	{ technique="fox3DDF_Blin_2MT_Dirty_LNM_VR",type="Deferred",variation="", shader="fox3ddf_blin_2mt_dirty_ln_vr"},
	{ technique="fox3DDF_Blin_SubNorm_Dirty_LNM",type="Deferred",variation="", shader="fox3ddf_blin_subnorm_dirty_ln"},
	{ technique="fox3DDF_Blin_LayerMul_Dirty_LNM",type="Deferred",variation="", shader="fox3ddf_blin_layer_mul_dirty_ln"},
	{ technique="fox3DDF_Blin_Incidence_LayerMul_3MT_Dirty_LNM",type="Deferred",variation="", shader="fox3ddf_blin_ic_lym_3mt_dirty_ln"},
	{ technique="fox3DDF_Cloth_NC_Dirty_LNM",type="Deferred",variation="", shader="fox3ddf_cloth_nc_dirty_ln"},
	{ technique="fox3DDF_Cloth_Dirty_LNM",type="Deferred",variation="", shader="fox3ddf_cloth_dirty_ln"},
	{ technique="fox3DDF_Hair",type="Forward",variation="", shader="ModelForward"},
	{ technique="fox3DDF_Hair",type="Deferred",variation="", shader="fox3ddf_hair"},
	{ technique="fox3DDF_MicroRoughness_LNM",type="Deferred",variation="", shader="fox3ddf_micro_roughness_ln"},
	{ technique="fox3DDF_Blin_MicroRoughness_SubNorm",type="Forward",variation="", shader="ModelForward"},
	{ technique="fox3DDF_Blin_MicroRoughness_SubNorm",type="Deferred",variation="", shader="fox3ddf_micro_subnorm"},
	{ technique="fox3DDF_Blin_Translucent_LNM",type="Deferred",variation="", shader="fox3ddf_translucent_ln"},
	{ technique="fox3DDF_Blin_Translucent_NC_LNM",type="Deferred",variation="", shader="fox3ddf_translucent_nc_ln"},
	{ technique="fox3DDF_Blin_Translucent_LNM",type="CloneDeferred",variation="", shader="fox3ddf_translucent_clone_ln"},
	{ technique="fox3DDF_Blin_Translucent_NC_LNM",type="CloneDeferred",variation="", shader="fox3ddf_translucent_nc_clone_ln"},
	{ technique="fox3DDF_Blin_Translucent_DirectiveAlpha_NC_LNM",type="Deferred",variation="", shader="fox3ddf_translucent_diralp_nc_ln"},
	{ technique="fox3DDF_Blin_Translucent_DirectiveAlpha_NC_LNM",type="CloneDeferred",variation="", shader="fox3ddf_translucent_diralp_nc_cl_ln"},
	{ technique="fox3DDF_Skin_LNM",type="Deferred",variation="", shader="fox3ddf_skin_ln"},
	{ technique="fox3DDF_Skin_LNM_VR",type="Deferred",variation="", shader="fox3ddf_skin_ln_vr"},
	{ technique="fox3DDF_Skin_Dirty",type="Forward",variation="", shader="ModelForward"},
	{ technique="fox3DDF_Skin_Dirty",type="Deferred",variation="", shader="fox3ddf_skin_dirty"},
	{ technique="fox3DDF_Skin_Dirty_LNM",type="Deferred",variation="", shader="fox3ddf_skin_dirty_ln"},
	{ technique="fox3DDF_Skin_Tension_LNM",type="Deferred",variation="", shader="fox3ddf_skin_tension_ln"},
	{ technique="fox3DDF_Skin_Tension_Dirty",type="Forward",variation="", shader="ModelForward"},
	{ technique="fox3DDF_Skin_Tension_Dirty",type="Deferred",variation="", shader="fox3ddf_skin_tension_dirty"},
	{ technique="fox3DDF_Skin_Tension_Dirty_LNM",type="Deferred",variation="", shader="fox3ddf_skin_tension_dirty_ln"},
	{ technique="fox3DDF_Eye_LNM",type="Deferred",variation="", shader="fox3ddf_eye_ln"},
	{ technique="fox3DDF_Eye_LNM_VR",type="Deferred",variation="", shader="fox3ddf_eye_ln_vr"},
	{ technique="fox3DDF_FastWave",type="Forward",variation="", shader="ModelForward"},
	{ technique="fox3DDF_FastWave",type="Deferred",variation="", shader="fox3ddf_fast_wave"},
	{ technique="fox3DDF_FastWave",type="CloneDeferred",variation="", shader="fox3ddf_fast_wave_clone"},
	{ technique="fox3DDF_NormalWave_LNM",type="Deferred",variation="", shader="fox3ddf_normal_wave_ln"},
	{ technique="fox3DDF_NormalWave_LNM",type="CloneDeferred",variation="", shader="fox3ddf_normal_wave_clone_ln"},
	{ technique="fox3DDF_NormalWave_DirectiveAlpha_LNM",type="Deferred",variation="", shader="fox3ddf_normal_wave_diralp_ln"},
	{ technique="fox3DDF_NormalWave_DirectiveAlpha_LNM",type="CloneDeferred",variation="", shader="fox3ddf_normal_wave_diralp_clone_ln"},
	{ technique="fox3DDF_PixcelWave",type="Forward",variation="", shader="ModelForward"},
	{ technique="fox3DDF_PixcelWave",type="Deferred",variation="", shader="fox3ddf_pixcel_wave"},
	{ technique="fox3DDF_PixcelWave",type="CloneDeferred",variation="", shader="fox3ddf_pixcel_wave_clone"},
	{ technique="fox3DDF_Dirty_UVSCroll_LNM",type="Deferred",variation="", shader="fox3ddf_blin_dirty_uvs_ln"},
	{ technique="fox3DDF_LightCover_LNM",type="Deferred",variation="", shader="fox3ddf_lightcover_ln"},
	{ technique="fox3DDF_LightCover_LNM_VR",type="Deferred",variation="", shader="fox3ddf_lightcover_ln_vr"},
	{ technique="fox3DDF_TempolaryView",type="Forward",variation="", shader="ModelForward"},
	{ technique="fox3DDF_TempolaryView",type="Deferred",variation="", shader="fox3ddf_tempolary_view"},
	{ technique="fox3DFW_Constant",type="Forward",variation="", shader="fox3dfw_constant"},
	{ technique="fox3DFW_ConstantSRGB",type="Forward",variation="", shader="fox3dfw_constant_srgb"},
	{ technique="fox3DFW_Constant_NDR",type="Forward",variation="", shader="fox3dfw_constant_ndr"},
	{ technique="fox3DFW_ParallaxReflection",type="Forward",variation="", shader="fox3dfw_parallax_refrection"},
	{ technique="fox3DFW_Glass",type="Forward",variation="", shader="fox3dfw_glass"},
	{ technique="fox3DFW_Glass_LNM",type="Forward",variation="", shader="fox3dfw_glass_ln"},
	{ technique="fox3DFW_GlassColor_LNM",type="Forward",variation="", shader="fox3dfw_glass_color_ln"},
	{ technique="fox3DFW_Glass_CommonRef",type="Forward",variation="", shader="fox3dfw_glass_commonref"},
	{ technique="fox3DFW_Glass_CommonRef_LNM",type="Forward",variation="", shader="fox3dfw_glass_commonref_ln"},
	{ technique="fox3DFW_GlassColor_CommonRef_LNM",type="Forward",variation="", shader="fox3dfw_glass_commonref_color_ln"},
	{ technique="fox3DFW_WaterCover_LNM",type="Forward",variation="", shader="fox3dfw_water_cover_ln"},
	{ technique="fox3DDC_Blin",type="Deferred_Decal",variation="", shader="fox3ddf_blin_decal"},
	{ technique="fox3DDC_Blin_LNM",type="Deferred_Decal",variation="", shader="fox3ddf_blin_decal_ln"},
	{ technique="fox3DNDW_Shadow",type="Deferred",variation="", shader="GBuffersBase"}}


GrTools():SetShaderParameterPackingTable( ParameterPackingList );
GrTools():SetShaderAssignTable( ShaderAssignList );
