-- ssd TppUiBootInit.lua
local subtitlesDaemon=SubtitlesDaemon.GetInstance()
if SubtitlesCommand then
  SubtitlesCommand:SetSubFilePath"/Assets/ssd/ui/Subtitles/sub_old/"
  SubtitlesCommand:SetSubpFilePath"/Assets/ssd/ui/Subtitles/subp/"
  SubtitlesCommand:SetDefaultGeneratorName"Default"
  SubtitlesCommand:SetSubFpkFilePath"/Assets/ssd/pack/ui/subtitles"
end
UiCommonDataManager.Create()
HudCommonDataManager.Create()
local uiCommonDataManager=UiCommonDataManager.GetInstance()
TppUiCommand.CreateUiDependJob()
TppUiCommand.CreateUiUpdateMarkerJob()
TppUiCommand.CreateUiUseGrJob()
TppUiCommand.UiPadStart()
TppUiCommand.CreateResidentBlockController(338*1024,"/Assets/ssd/pack/ui/ssd_ui_resident_data.fpk")
TppUiCommand.UiPlatFormSetting()
TppUiCommand.UiAreaSetting()
LanguageBlock.Create(860*1024)
LanguageBlock.Create(96*1024)
if Fox.GetPlatformName()=="Windows"then
  if Editor then
    TppUiCommand.SetVarsLanguage(8)
  else
    TppUiCommand.SetPlatformLanguage()
  end
else
  TppUiCommand.SetPlatformLanguage()
end
local lang=AssetConfiguration.GetDefaultCategory"Language"
TppUiCommand.InitFont(lang)
TppUiCommand.ChangeLanguage()
FadeFunction.InitFadeSetting()
UiDaemon.SetExecLuaFile"Tpp/Scripts/Ui/TppUiPrefetchTexture.lua"
local uiDaemon=UiDaemon.GetInstance()
--RETAILPATCH: 1.0.5.0 removed
--uiDaemon.ResetDefaultButtonMap()
--uiDaemon.SetButtonMap("BUTTON_A",fox.PAD_A,fox.KEY_RETURN)
--uiDaemon.SetButtonMap("BUTTON_B",fox.PAD_B,fox.KEY_ESCAPE)
--uiDaemon.SetButtonMap("BUTTON_X",fox.PAD_X,fox.KEY_G)
--uiDaemon.SetButtonMap("BUTTON_Y",fox.PAD_Y,fox.KEY_T)
--uiDaemon.SetButtonMap("BUTTON_UP",fox.PAD_U,fox.KEY_W)
--uiDaemon.SetButtonMap("BUTTON_DOWN",fox.PAD_D,fox.KEY_S)
--uiDaemon.SetButtonMap("BUTTON_LEFT",fox.PAD_L,fox.KEY_A)
--uiDaemon.SetButtonMap("BUTTON_RIGHT",fox.PAD_R,fox.KEY_D)
--uiDaemon.SetButtonMap("STATUS_UP",fox.PAD_U+4,fox.KEY_UP)
--uiDaemon.SetButtonMap("STATUS_DOWN",fox.PAD_D+4,fox.KEY_DOWN)
--uiDaemon.SetButtonMap("STATUS_LEFT",fox.PAD_L+4,fox.KEY_LEFT)
--uiDaemon.SetButtonMap("STATUS_RIGHT",fox.PAD_R+4,fox.KEY_RIGHT)
--uiDaemon.SetButtonMap("BUTTON_LT",fox.PAD_L2,fox.KEY_1)
--uiDaemon.SetButtonMap("BUTTON_RT",fox.PAD_R2,fox.KEY_3)
--uiDaemon.SetButtonMap("BUTTON_LB",fox.PAD_L1,fox.KEY_1)
--uiDaemon.SetButtonMap("BUTTON_RB",fox.PAD_R1,fox.KEY_3)
--uiDaemon.SetButtonDecideMap("UI_DECIDE",fox.KEY_SPACE)
--uiDaemon.SetButtonCancelMap("UI_CANCEL",fox.KEY_ESCAPE)
--uiDaemon.SetButtonDecideMap("DECISION",fox.KEY_SPACE)
--uiDaemon.SetButtonCancelMap("CANCEL",fox.KEY_ESCAPE)
--uiDaemon.SetButtonDecideMap("UI_MOUSE_DECIDE",fox.MOUSE_CODE_LEFT)
--uiDaemon.SetButtonCancelMap("UI_MOUSE_CANCEL",fox.MOUSE_CODE_RIGHT)
--uiDaemon.SetButtonMap("UI_DETAIL",fox.PAD_Y,fox.KEY_T)
--uiDaemon.SetButtonMap("UI_CHECK",fox.PAD_X,fox.KEY_G)
--uiDaemon.SetButtonMap("UI_SELECT",fox.PAD_SELECT,fox.KEY_ESCAPE)
--uiDaemon.SetButtonMap("UI_START",fox.PAD_START,fox.KEY_TAB)
--uiDaemon.SetButtonMap("UI_UP",fox.PAD_U,fox.KEY_W)
--uiDaemon.SetButtonMap("UI_DOWN",fox.PAD_D,fox.KEY_S)
--uiDaemon.SetButtonMap("UI_LEFT",fox.PAD_L,fox.KEY_A)
--uiDaemon.SetButtonMap("UI_RIGHT",fox.PAD_R,fox.KEY_D)
--uiDaemon.SetButtonMap("UI_LT",fox.PAD_L2,fox.KEY_Q)
--uiDaemon.SetButtonMap("UI_RT",fox.PAD_R2,fox.KEY_E)
--uiDaemon.SetButtonMap("UI_LB",fox.PAD_L1,fox.KEY_1)
--uiDaemon.SetButtonMap("UI_RB",fox.PAD_R1,fox.KEY_3)
--uiDaemon.SetButtonMap("UI_LEFTSTICK_PUSH",fox.PAD_L3,fox.KEY_SHIFT)
--uiDaemon.SetButtonMap("UI_RIGHTSTICK_PUSH",fox.PAD_R3,fox.KEY_V)
--uiDaemon.SetButtonMap("UI_LB_PAGE_UP",fox.PAD_L1,fox.KEY_PAGEUP)
--uiDaemon.SetButtonMap("UI_RB_PAGE_DOWN",fox.PAD_R1,fox.KEY_PAGEDOWN)
--uiDaemon.SetButtonMap("UI_KBD_SHIFT",fox.GK_PAD_NO_BUTTON,fox.KEY_SHIFT)
--uiDaemon.SetButtonMap("UI_KBD_ALT",fox.GK_PAD_NO_BUTTON,fox.KEY_ALT)
--uiDaemon.SetButtonMap("UI_KBD_CTRL",fox.GK_PAD_NO_BUTTON,fox.KEY_CTRL)
--uiDaemon.SetButtonMap("UI_KBD_BS",fox.GK_PAD_NO_BUTTON,fox.KEY_BS)
--uiDaemon.SetButtonMap("UI_KBD_RETURN",fox.GK_PAD_NO_BUTTON,fox.KEY_RETURN)
--uiDaemon.SetButtonMap("UI_KBD_1",fox.GK_PAD_NO_BUTTON,fox.KEY_1)
--uiDaemon.SetButtonMap("UI_KBD_2",fox.GK_PAD_NO_BUTTON,fox.KEY_2)
--uiDaemon.SetButtonMap("UI_KBD_3",fox.GK_PAD_NO_BUTTON,fox.KEY_3)
--uiDaemon.SetButtonMap("UI_KBD_4",fox.GK_PAD_NO_BUTTON,fox.KEY_4)
--uiDaemon.SetButtonMap("UI_KBD_5",fox.GK_PAD_NO_BUTTON,fox.KEY_5)
--uiDaemon.SetButtonMap("UI_KBD_6",fox.GK_PAD_NO_BUTTON,fox.KEY_6)
--uiDaemon.SetButtonMap("UI_KBD_7",fox.GK_PAD_NO_BUTTON,fox.KEY_7)
--uiDaemon.SetButtonMap("UI_KBD_8",fox.GK_PAD_NO_BUTTON,fox.KEY_8)
--uiDaemon.SetButtonMap("UI_KBD_9",fox.GK_PAD_NO_BUTTON,fox.KEY_9)
--uiDaemon.SetButtonMap("UI_KBD_0",fox.GK_PAD_NO_BUTTON,fox.KEY_0)
--uiDaemon.SetButtonMap("UI_KBD_X",fox.GK_PAD_NO_BUTTON,fox.KEY_G)
--uiDaemon.SetButtonMap("UI_KBD_Y",fox.GK_PAD_NO_BUTTON,fox.KEY_T)
--uiDaemon.SetButtonMap("UI_KBD_UP",fox.GK_PAD_NO_BUTTON,fox.KEY_UP)
--uiDaemon.SetButtonMap("UI_KBD_DOWN",fox.GK_PAD_NO_BUTTON,fox.KEY_DOWN)
--uiDaemon.SetButtonMap("UI_KBD_LEFT",fox.GK_PAD_NO_BUTTON,fox.KEY_LEFT)
--uiDaemon.SetButtonMap("UI_KBD_RIGHT",fox.GK_PAD_NO_BUTTON,fox.KEY_RIGHT)
--uiDaemon.SetButtonMap("UI_KBD_PAGE_UP",fox.GK_PAD_NO_BUTTON,fox.KEY_PAGEUP)
--uiDaemon.SetButtonMap("UI_KBD_PAGE_DOWN",fox.GK_PAD_NO_BUTTON,fox.KEY_PAGEDOWN)
--uiDaemon.SetButtonMap("UI_EQUIP_PRIMARY",fox.GK_PAD_NO_BUTTON,fox.KEY_1)
--uiDaemon.SetButtonMap("UI_EQUIP_SECONDARY",fox.GK_PAD_NO_BUTTON,fox.KEY_2)
--uiDaemon.SetButtonMap("UI_EQUIP_SUPPORT",fox.GK_PAD_NO_BUTTON,fox.KEY_3)
--uiDaemon.SetButtonMap("UI_EQUIP_ITEM",fox.GK_PAD_NO_BUTTON,fox.KEY_4)
--uiDaemon.SetButtonMap("UI_EQUIP_UP",fox.GK_PAD_NO_BUTTON,fox.KEY_UP)
--uiDaemon.SetButtonMap("UI_EQUIP_DOWN",fox.GK_PAD_NO_BUTTON,fox.KEY_DOWN)
--uiDaemon.SetButtonMap("UI_EQUIP_LEFT",fox.GK_PAD_NO_BUTTON,fox.KEY_LEFT)
--uiDaemon.SetButtonMap("UI_EQUIP_RIGHT",fox.GK_PAD_NO_BUTTON,fox.KEY_RIGHT)
--uiDaemon.SetButtonMap("UI_EQUIP_OP_1",fox.PAD_X,fox.KEY_G)
--uiDaemon.SetButtonMap("UI_EQUIP_OP_2",fox.PAD_Y,fox.KEY_T)
--uiDaemon.SetButtonMap("UI_PAGE_UP",fox.PAD_L,fox.KEY_PAGEUP)
--uiDaemon.SetButtonMap("UI_PAGE_DOWN",fox.PAD_R,fox.KEY_PAGEDOWN)
--uiDaemon.SetButtonMap("UI_MOVE_UP",fox.PAD_R2,fox.KEY_W)
--uiDaemon.SetButtonMap("UI_MOVE_DOWN",fox.PAD_L2,fox.KEY_S)
--uiDaemon.SetButtonMap("UI_MOVE_LEFT",fox.GK_PAD_NO_BUTTON,fox.KEY_A)
--uiDaemon.SetButtonMap("UI_MOVE_RIGHT",fox.GK_PAD_NO_BUTTON,fox.KEY_D)
--uiDaemon.SetButtonMap("UI_STANCE",fox.GK_PAD_NO_BUTTON,fox.KEY_C)
--uiDaemon.SetButtonMap("UI_ACTION",fox.GK_PAD_NO_BUTTON,fox.KEY_E)
--uiDaemon.SetButtonMap("UI_SUBJECT",fox.GK_PAD_NO_BUTTON,fox.KEY_F)
--uiDaemon.SetButtonMap("UI_EVADE",fox.GK_PAD_NO_BUTTON,fox.KEY_SPACE)
--uiDaemon.SetButtonMap("UI_RELOAD",fox.GK_PAD_NO_BUTTON,fox.KEY_R)
--uiDaemon.SetButtonMap("UI_RADIO",fox.GK_PAD_NO_BUTTON,fox.KEY_Q)
--uiDaemon.SetButtonMap("UI_HOLD",fox.GK_PAD_NO_BUTTON,fox.MOUSE_CODE_RIGHT)
--uiDaemon.SetButtonMap("UI_SHOT",fox.GK_PAD_NO_BUTTON,fox.MOUSE_CODE_LEFT)
--uiDaemon.SetButtonMap("UI_STOCK",fox.PAD_R3,fox.KEY_V)
--uiDaemon.SetButtonMap("UI_CQC",fox.GK_PAD_NO_BUTTON,fox.MOUSE_CODE_LEFT)
--uiDaemon.SetButtonMap("UI_SIDE_ROLL",fox.GK_PAD_NO_BUTTON,fox.KEY_SHIFT)
--uiDaemon.SetButtonMap("UI_LIGHT_SWITCH",fox.PAD_R,fox.KEY_X)
--uiDaemon.SetButtonMap("UI_VEHICLE_FIRE",fox.PAD_L1,fox.MOUSE_CODE_LEFT)
--uiDaemon.SetButtonMap("UI_VEHICLE_CALL",fox.GK_PAD_NO_BUTTON,fox.KEY_Q)
--uiDaemon.SetButtonMap("UI_VEHICLE_DASH",fox.GK_PAD_NO_BUTTON,fox.KEY_W)
--uiDaemon.SetButtonMap("UI_VEHICLE_CAMERA",fox.PAD_R1,fox.KEY_F)
--uiDaemon.SetButtonMap("UI_PLACE_MARKER",fox.PAD_L2,fox.MOUSE_CODE_LEFT)
--uiDaemon.SetButtonMap("UI_MAP_MARKER",fox.GK_PAD_NO_BUTTON,fox.MOUSE_CODE_LEFT)
--uiDaemon.SetButtonMap("UI_SCORES",fox.GK_PAD_NO_BUTTON,fox.KEY_ESCAPE)
--uiDaemon.SetButtonMap("UI_DASH",fox.GK_PAD_NO_BUTTON,fox.KEY_SHIFT)
--uiDaemon.SetButtonMap("UI_WALK",fox.GK_PAD_NO_BUTTON,fox.KEY_CTRL)
--uiDaemon.SetButtonMap("UI_MB_HELP",fox.PAD_SELECT,fox.KEY_H)
--uiDaemon.SetButtonMap("UI_BUDDY_DASH",fox.PAD_X,fox.KEY_SHIFT)
--uiDaemon.SetButtonMap("HUD_DECIDE",fox.PAD_R3,fox.KEY_SPACE)
--uiDaemon.SetButtonMap("UI_PAD_ALL",fox.GK_PAD_NO_BUTTON,fox.EX_CODE_PAD_DIR)
--uiDaemon.SetButtonMap("UI_PAD_KEY_UD",fox.GK_PAD_NO_BUTTON,fox.EX_CODE_KEY_UD)
--uiDaemon.SetButtonMap("UI_PAD_KEY_LR",fox.GK_PAD_NO_BUTTON,fox.EX_CODE_KEY_LR)
--uiDaemon.SetButtonMap("UI_PAD_STICK_L",fox.GK_PAD_NO_BUTTON,fox.EX_CODE_STICK_L)
--uiDaemon.SetButtonMap("UI_PAD_STICK_R",fox.GK_PAD_NO_BUTTON,fox.EX_CODE_STICK_R)
--uiDaemon.SetButtonMap("UI_MOUSE_WHEEL",fox.GK_PAD_NO_BUTTON,fox.EX_CODE_MOUSE_WHEEL)
--uiDaemon.SetButtonMap("UI_MOUSE_MIDDLE",fox.GK_PAD_NO_BUTTON,fox.MOUSE_CODE_MIDDLE)
--uiDaemon.SetButtonMap("UI_EQUIP_STICK",fox.GK_PAD_NO_BUTTON,fox.EX_CODE_MOUSE_WHEEL)
--uiDaemon.SetButtonMap("UI_EQUIP_DIR",fox.GK_PAD_NO_BUTTON,fox.EX_CODE_PAD_DIR)
--uiDaemon.SetButtonMap("UI_BINO_RADIO",fox.GK_PAD_NO_BUTTON,fox.KEY_Q)
--uiDaemon.SetButtonMap("UI_BINO_ZOOM",fox.GK_PAD_NO_BUTTON,fox.KEY_V)
--uiDaemon.SetButtonMap("UI_BINO_MARKER",fox.GK_PAD_NO_BUTTON,fox.MOUSE_CODE_LEFT)
--uiDaemon.SetButtonMap("UI_BINO_CHANGE",fox.GK_PAD_NO_BUTTON,fox.KEY_T)
--uiDaemon.SetButtonMap("UI_BINO_DECIDE",fox.GK_PAD_NO_BUTTON,fox.KEY_RETURN)
--uiDaemon.SetButtonMap("CQC_KNIFE_KILL",fox.GK_PAD_NO_BUTTON,fox.KEY_E)
--uiDaemon.SetButtonMap("CQC_HOLD",fox.GK_PAD_NO_BUTTON,fox.MOUSE_CODE_LEFT)
--uiDaemon.SetButtonMap("CQC_INTERROGATE",fox.GK_PAD_NO_BUTTON,fox.KEY_Q)
--uiDaemon.CreateButtonMap()
--uiDaemon.SetKeyCodeEqual("UI_UP",fox.KEY_UP)
--uiDaemon.SetKeyCodeEqual("UI_DOWN",fox.KEY_DOWN)
--uiDaemon.SetKeyCodeEqual("UI_LEFT",fox.KEY_LEFT)
--uiDaemon.SetKeyCodeEqual("UI_RIGHT",fox.KEY_RIGHT)
--uiDaemon.SetKeyCodeEqual("UI_DECIDE",fox.KEY_RETURN)
--uiDaemon.SetKeyCodeEqual("HUD_DECIDE",fox.KEY_RETURN)
--uiDaemon.SetKeyCodeEqual("UI_STOCK",fox.MOUSE_CODE_MIDDLE)
TppUiCommand.InitializeUiInputMap()
UiDaemon.ClearDrawPriorityTable()
UiDaemon.SetDrawPriorityTable{
  interval=100,
  table={
    {name="__BACK_EFFECT",priority=0},
    {name="VERY_BACK",priority=11},
    {name="COMMON_3D",priority=1},
    {name="HOLOGRAM_PANEL",priority=12},
    {name="FACILITY_PANEL",priority=37},
    {name="__HUD",priority=20},
    {name="PICK_UP",priority=21},
    {name="WORLD_MARKER_CHARA",priority=23},
    {name="BOSS_GAUGE_HEAD",priority=25},
    {name="WORLD_MARKER",priority=27},
    {name="TIME_CIGARETTE_BG",priority=30},
    {name="TIME_CIGARETTE",priority=32},
    {name="NOTICE_DIR",priority=35},
    {name="DAMAGE_DIR",priority=37},
    {name="PRESET_RADIO",priority=40},
    {name="ACTION_ICON",priority=50},
    {name="RETICLE_LOW",priority=53},
    {name="RETICLE",priority=55},
    {name="RETICLE_HIGH",priority=57},
    {name="BOSS_GAUGE_2D",priority=60},
    {name="__MB_DEVICE",priority=64},
    {name="MB_BG",priority=65},
    {name="MB_MENU_LOW",priority=66},
    {name="MB_MENU_MIDDLE",priority=68},
    {name="MB_MENU_HIGH",priority=70},
    {name="MB_MAP_BG",priority=71},
    {name="MB_MAP",priority=72},
    {name="MB_MAP_ICON",priority=74},
    {name="MB_MAP_HIGH",priority=82},
    {name="MB_CHILD_PAGE",priority=84},
    {name="MB_CHILD_LOW",priority=85},
    {name="MB_CHILD_MIDDLE",priority=86},
    {name="MB_CHILD_HIGH",priority=88},
    {name="MB_COMMON_HIGH",priority=94},
    {name="PLAYER_INFO",priority=88},
    {name="DEV_COND_POPUP",priority=98},
    {name="WEP_ICON",priority=95},
    {name="__SIGHT",priority=128},
    {name="SIGHT_BG",priority=128},
    {name="SIGHT_RETICLE",priority=130},
    {name="SIGHT_RETICLE_ADD",priority=131},
    {name="SIGHT_STRONG",priority=132},
    {name="SIGHT_STRONG_HUD",priority=133},
    {name="LMENU",priority=133},
    {name="LOCKON_RETICLE",priority=134},
    {name="LMENU_SELECT",priority=135},
    {name="CALL_MENU",priority=135},
    {name="RADIO_GUIDE",priority=136},
    {name="MINIMAP",priority=136},
    {name="WEAPON_PANEL",priority=146},
    {name="HELP_TIPS",priority=147},
    {name="REWARD",priority=143},
    {name="PURCHASE",priority=128},
    {name="REVIVAL_MENU",priority=140},
    {name="MISSION_OBJECTIVE",priority=149},
    {name="ITEM_PANEL",priority=152},
    {name="UNDER_SUBTITLE_BG",priority=150},
    {name="COMMUNICATION_MENU",priority=150},
    {name="DMEO_PAUSE_KEY_HELP",priority=220},
    {name="__SUBTITLE",priority=150},
    {name="SUBTITLE",priority=151},
    {name="__TEXT",priority=160},
    {name="FRIEND_LOG",priority=161},
    {name="PIC_INFO",priority=161},
    {name="MISSION_ICON",priority=161},
    {name="RESOURCE_PANEL",priority=161},
    {name="GMP_INFO",priority=162},
    {name="ANNOUNCE_LOG",priority=163},
    {name="TELOP_TEXT",priority=165},
    {name="USER_REPORT",priority=166},
    {name="__GAME_FADE",priority=190},
    {name="GAME_FADE",priority=191},
    {name="GAME_FADE_UP",priority=192},
    {name="CAMP_RESULT",priority=193},
    {name="INFO_POPUP",priority=193},--RETAILPATCH: 1.0.5.0
    {name="__STRONG_TEXT",priority=195},
    {name="STRONG_ANNOUNCE_LOG",priority=195},
    {name="__TELOP_PAUSE",priority=200},
    {name="TELOP_BG",priority=201},
    {name="PAUSE_BG",priority=201},
    {name="PAUSE_MENU",priority=203},
    {name="PAUSE_MENU_ADD",priority=205},
    {name="STEAM_STORE",priority=205},
    {name="TITLE_BG_LOW",priority=79},
    {name="TITLE_BG",priority=80},
    {name="TITLE_NORMAL_BG",priority=166},
    {name="TITLE_LOGO",priority=167},
    {name="TITLE_MENU",priority=168},
    {name="MATCHING_MENU",priority=200},
    {name="COMMON_INPUT_STRING",priority=133},
    {name="ONLINE_NEWS",priority=210},
    {name="SINGLE_MISSION_RESULT",priority=217},
    {name="BLACK_RADIO",priority=213},
    {name="STORY_SUMMARY",priority=213},
    {name="__STRONG_TELOP_PAUSE",priority=220},
    {name="STRONG_TELOP_BG",priority=221},
    {name="STRONG_TELOP_PAGE",priority=222},
    {name="STRONG_TELOP_TEXT",priority=223},
    {name="STRONG_PAUSE_BG",priority=225},
    {name="STRONG_PAUSE_MENU",priority=227},
    {name="STRONG_PAUSE_ICON",priority=229},
    {name="LYRIC_TELOP",priority=229},
    {name="LOGOUT_COUNTDOWN",priority=229},
    {name="__STRONG_SUBTITLE",priority=230},
    {name="__FRONT_EFFECT",priority=245},
    {name="__ERROR_MESSAGE",priority=251},
    {name="ERROR_MESSAGE",priority=251},
    {name="SYSTEM_MESSAGE",priority=251},
    {name="SYSTEM_ICON",priority=252},
    {name="PREFAB_COMMON",priority=86},
    {name="PREFAB_POPUP",priority=92}
  }
}
TppUiCommand.InitPrefabSystem()
TppUiCommand.InitEmblemSaveData()
SsdBlankMap.Init()
TppUiCommand.CallAccessMessage()
