-- Overrides.lua
EnemyFova={}
EnemyFova.MAX_REALIZED_COUNT=0
TppAnimalId={COUNT=0}
MotherBaseStage={}
function MotherBaseStage.RegisterModifyLayoutCodes(E)
end
Vehicle={type={EASTERN_LIGHT_VEHICLE=0,EASTERN_TRACKED_TANK=0,EASTERN_TRUCK=0,EASTERN_WHEELED_ARMORED_VEHICLE=0,WESTERN_LIGHT_VEHICLE=0,WESTERN_TRACKED_TANK=0,WESTERN_TRUCK=0,WESTERN_WHEELED_ARMORED_VEHICLE=0}}
return{}
