local  afgh_baseTelop = {}

afgh_baseTelop.cpLangIdTable = {
	{ "afgh_bridge_cp", "tpp_afghan_bridge", "tpp_afghan_en_bridge", },
	{ "afgh_waterWay_cp", "tpp_afghan_waterway", "tpp_afghan_en_waterway", },
	{ "afgh_remnants_cp", "tpp_afghan_remnant", "tpp_afghan_en_remnant", },
	{ "afgh_village_cp", "tpp_afghan_village", "tpp_afghan_en_village", },
	{ "afgh_commFacility_cp", "tpp_afghan_commFacility", "tpp_afghan_en_commFacility", },
	{ "afgh_slopedTown_cp", "tpp_afghan_slopedTown", "tpp_afghan_en_slopedTown", },
	{ "afgh_enemyBase_cp", "tpp_afghan_enemyBase", "tpp_afghan_en_enemyBase", },
	{ "afgh_cliffTown_cp", "tpp_afghan_cliffTown", "tpp_afghan_en_cliffTown", },
	{ "afgh_tent_cp", "tpp_afghan_tent", "tpp_afghan_en_tent", },
	{ "afgh_powerPlant_cp", "tpp_afghan_powerPlant", "tpp_afghan_en_powerPlant", },
	{ "afgh_field_cp", "tpp_afghan_field", "tpp_afghan_en_field", },
	{ "afgh_fort_cp", "tpp_afghan_fort", "tpp_afghan_en_fort", },
	{ "afgh_sovietBase_cp", "tpp_afghan_sovietBase", "tpp_afghan_en_sovietBase", },
	{ "afgh_citadel_cp", "tpp_afghan_citadel", "tpp_afghan_en_citadel", },
	{ "afgh_commWest_ob", "tpp_afghan_commWest", "tpp_afghan_en_commWest", },
	{ "afgh_villageWest_ob", "tpp_afghan_villageWest", "tpp_afghan_en_villageWest", },
	{ "afgh_ruinsNorth_ob", "tpp_afghan_ruinsNorth", "tpp_afghan_en_ruinsNorth", },
	{ "afgh_villageNorth_ob", "tpp_afghan_villageNorth", "tpp_afghan_en_villageNorth", },
	{ "afgh_slopedWest_ob", "tpp_afghan_slopedWest", "tpp_afghan_en_slopedWest", },
	{ "afgh_fieldEast_ob", "tpp_afghan_fieldEast", "tpp_afghan_en_fieldEast", },
	{ "afgh_fieldWest_ob", "tpp_afghan_fieldWest", "tpp_afghan_en_fieldWest", },
	{ "afgh_tentNorth_ob", "tpp_afghan_tentNorth", "tpp_afghan_en_tentNorth", },
	{ "afgh_slopedEast_ob", "tpp_afghan_slopedEast", "tpp_afghan_en_slopedEast", },
	{ "afgh_villageEast_ob", "tpp_afghan_villageEast", "tpp_afghan_en_villageEast", },
	{ "afgh_bridgeWest_ob", "tpp_afghan_bridgeWest", "tpp_afghan_en_bridgeWest", },
	{ "afgh_fortSouth_ob", "tpp_afghan_fortSouth", "tpp_afghan_en_fortSouth", },
	{ "afgh_fortWest_ob", "tpp_afghan_fortWest", "tpp_afghan_en_fortWest", },
	{ "afgh_cliffEast_ob", "tpp_afghan_cliffEast", "tpp_afghan_en_cliffEast", },
	{ "afgh_cliffSouth_ob", "tpp_afghan_cliffSouth", "tpp_afghan_en_cliffSouth", },
	{ "afgh_enemyNorth_ob", "tpp_afghan_enemyNorth", "tpp_afghan_en_enemyNorth", },
	{ "afgh_bridgeNorth_ob", "tpp_afghan_bridgeNorth", "tpp_afghan_en_bridgeNorth", },
	{ "afgh_cliffWest_ob", "tpp_afghan_cliffWest", "tpp_afghan_en_cliffWest", },
	{ "afgh_enemyEast_ob", "tpp_afghan_enemyEast", "tpp_afghan_en_enemyEast", },
	{ "afgh_tentEast_ob", "tpp_afghan_tentEast", "tpp_afghan_en_tentEast", },
	{ "afgh_sovietSouth_ob", "tpp_afghan_sovietSouth", "tpp_afghan_en_sovietSouth", },
	{ "afgh_plantWest_ob", "tpp_afghan_plantWest", "tpp_afghan_en_plantWest", },
	{ "afgh_waterwayEast_ob", "tpp_afghan_waterWayEast", "tpp_afghan_en_waterWayEast", },
	{ "afgh_citadelSouth_ob", "tpp_afghan_CitadelSouth", "tpp_afghan_en_CitadelSouth", },
	{ "afgh_ruins_cp", "tpp_afghan_ruins", "tpp_afghan_en_ruins", },
}

return afgh_baseTelop