local this={}
local bnot=bit.bnot
local band,bor,bxor=bit.band,bit.bor,bit.bxor
--NMC GOTCHA TppDefine.Enum indexed from 0, Tpp.Enum indexed from one.
--GOTCHA pulls via pairs, so could use a non array table TODO review in light of this
function this.Enum(enumNames)
  if type(enumNames)~="table"then
    return
  end
  local enumTable={}
  for i,enumName in pairs(enumNames)do
    enumTable[enumName]=i-1--NMC: lua tables indexed from 1, enums indexed from 0
  end
  return enumTable
end
this.SMALL_DIAMOND_GMP=1e4
this.LARGE_DIAMOND_GMP=1e5
this.MAX_32BIT_UINT=4294967295
this.EXCEPTION_QUEUE_MAX=255
this.PICKABLE_MAX=16
this.PLACED_MAX=8
this.DEFAULT_EQUIP_MISSION_BLOCK_GROUP_SIZE=1677721
this.MISSION_COUNT_MAX=128
this.DEFAULT_SOLDIER_STATE_COUNT=160
this.DEFAULT_SOLDIER_OPTION_VARS_COUNT=512
this.DEFAULT_PASSAGE_INFO_COUNT=64
this.DEFAULT_PASSAGE_FLAG_COUNT=this.DEFAULT_PASSAGE_INFO_COUNT*5
this.DEFAULT_NOTICE_INFO_COUNT=24
this.DEFAULT_HOSTAGE_STATE_COUNT=32
this.ENEMY_FOVA_UNIQUE_SETTING_COUNT=16
this.DEFAULT_ENEMY_HELI_STATE_COUNT=1
this.MAX_HOLD_RECOVERED_STATE_COUNT=32
this.MAX_HOLD_VEHICLE_BROKEN_STATE_COUNT=32
this.MAX_ANIMAL_RECOVERED_HISTORY_SIZE=50
this.SEARCH_TARGET_COUNT=8
this.CHECK_POINT_MAX=64
this.QUEST_MAX=250
this.QUEST_FACE_MAX=32
this.QUEST_ENEMY_MAX=8
this.REVENGE_MINE_BASE_MAX=20
this.MISSION_CLEAR_HISTORY_LIMIT=36
this.MAX_MISSION_TASK_COUNT=8
this.MAX_TAKING_OVER_HOSTAGE_COUNT=4
this.MAX_MB_DEMO_PLAYFLAG_MAX=4
this.INIT_HELI_ROUTE=0
this.FLAG_MISSION_MAX=128
this.BASE_DEFENSE_MISSION_MAX=64
this.BASE_DEFENSE_TUTORIAL_MISSION=50500
this.PLAYSTYLE_SAVE_INDEX_MAX=20
this.PLAYSTYLE_HISTORY_MAX=2
this.MAX_TIPS_GUIDE_SHOWN_ONCE=256
this.MAX_CONTROL_GUIDE_SHOWN_ONCE=128
this.MESSAGE_GENERATION={
  [Fox.StrCode32"GameObject"]={
    [Fox.StrCode32"Fulton"]=0,
    [Fox.StrCode32"VehicleBroken"]=0
  }
}
this.DEFAULT_MESSAGE_GENERATION=1
this.ELAPSED_MISSION_COUNT_MAX=14
this.ELAPSED_MISSION_COUNT={INIT=-127,DONE_EVENT=-1,NOW_OCCURRING=0}
this.ELAPSED_QUEST_COUNT={INIT=-127,DONE_EVENT=-1,NOW_OCCURRING=0}
this.MISSION_START_RECOVER_DEMO_TYPE={NONE=0,VEHICLE=1,WALKER_GEAR=2}
this.REWARD_MAX={MISSION=16,MB_MANAGEMENT=64,QUEST=8}
this.REWARD_PARAM={TYPE=0,ARG1=1,ARG2=2,MAX=3}
this.TRAP_TYPE=this.Enum{"NORMAL","TRIGGER"}
this.TRAP_STATE=this.Enum{"ENABLE","DISABLE"}
this.HOSTAGE_GM_TYPE=this.Enum{TppGameObject.GAME_OBJECT_TYPE_HOSTAGE2,TppGameObject.GAME_OBJECT_TYPE_HOSTAGE_UNIQUE,TppGameObject.GAME_OBJECT_TYPE_HOSTAGE_UNIQUE2}
this.FULTONABLE_GIMMICK_TYPE=this.Enum{TppGameObject.GAME_OBJECT_TYPE_GATLINGGUN,TppGameObject.GAME_OBJECT_TYPE_MORTAR,TppGameObject.GAME_OBJECT_TYPE_MACHINEGUN}
this.QUEST_MINE_TYPE_LIST={TppEquip.EQP_SWP_DMine,TppEquip.EQP_SWP_DMine_G01,TppEquip.EQP_SWP_DMine_G02}
this.BUDDY_GM_TYPE_TO_BUDDY_TYPE={
  [TppGameObject.GAME_OBJECT_TYPE_HORSE2]=BuddyType.HORSE,
  [TppGameObject.GAME_OBJECT_TYPE_BUDDYQUIET2]=BuddyType.QUIET,
  [TppGameObject.GAME_OBJECT_TYPE_BOSSQUIET2]=BuddyType.QUIET,
  [TppGameObject.GAME_OBJECT_TYPE_BUDDYDOG2]=BuddyType.DOG,
  [TppGameObject.GAME_OBJECT_TYPE_BUDDYPUPPY]=BuddyType.DOG
}
this.ANIMAL_GAMEOBJECT_TYPE=this.Enum{
  TppGameObject.GAME_OBJECT_TYPE_GOAT,
  TppGameObject.GAME_OBJECT_TYPE_NUBIAN,
  TppGameObject.GAME_OBJECT_TYPE_CRITTER_BIRD,
  TppGameObject.GAME_OBJECT_TYPE_STORK,
  TppGameObject.GAME_OBJECT_TYPE_EAGLE,
  TppGameObject.GAME_OBJECT_TYPE_RAT,
  TppGameObject.GAME_OBJECT_TYPE_ZEBRA,
  TppGameObject.GAME_OBJECT_TYPE_WOLF,
  TppGameObject.GAME_OBJECT_TYPE_JACKAL,
  TppGameObject.GAME_OBJECT_TYPE_BEAR
}
this.MISSION_CLEAR_STATE_LIST={"INIT","NOT_CLEARED_YET","ESTABLISHED_CLEAR","MISSION_GAME_END","SHOW_CREDIT_END","BLACK_TELEPHOHE_END","REWARD_END","MISSION_FINALIZED"}
this.MISSION_CLEAR_STATE=this.Enum(this.MISSION_CLEAR_STATE_LIST)
this.ERROR_ID={
  CONFIRM_AUTO_SAVE=1e3,
  MAKE_NEW_SAVE_DATA=1100,
  SAVE_FAILED_NOT_ENOUGH_STORAGE_CAPACITY=1101,
  SAVE_FAILED_UNKNOWN_REASON=1102,
  SAVE_FAILED_CANNOT_FIND_STORAGE=1103,
  LOADING_SAVE_DATA=1200,
  LOAD_RESULT_OWNER_ERROR=1202,
  LOAD_RESULT_BACKUP_ERROR=1203,
  LOAD_RESULT_FILE_CORRUPT_ERROR=1204,
  LOAD_RESULT_VERSION_ERROR=1205,
  LOAD_RESULT_CONFIG_FILE_CORRUPT_ERROR=1207,
  NOT_SELECT_STORAGE=1300,
  CHECKING_STORAGE_FREE_SPACE_SIZE=1301,
  CANNOT_FIND_STORAGE_IN_GAME=1302,
  START_NOT_SIGN_IN=2001,
  SIGNIN_USER_CHANGED=22100,
  DISCONNECT_FROM_PSN=22200,
  DISCONNECT_FROM_KONAMI=23208,
  DISCONNECT_FROM_NETWORK=23208,
  SESSION_DISCONNECT_FROM_HOST=4180,
  GET_MGO_INVITATION=5e3,
  NOW_INSTALLATION_CHECKING=7e3,
  INSERT_INSTALL_DISK_WHEN_NOT_INSTALLED=7060,
  CANNOT_FIND_HDD=7002,
  NOW_INSTALLING=7003,
  INSTALL_CANCEL=7004,
  INSTALL_FAILED_NOT_ENOUGH_STORAGE_CAPACITY=7005,
  INSTALL_FAILED_UNKNOWN_REASON=7006,
  INSERT_GAME_DISK_WHEN_INSTALL_END=7051,
  INSERT_GAME_DISK_WHEN_ALREADY_INSTALLED=7052,
  TROPHY_INSTALLING=7101,
  TROPHY_INSTALL_FAILED=7102,
  DLC_DOWNLOAD_ERROR=8001,
  SESSION_ABANDON=20013,
  FAILED_JOIN_SESSION=20014
}
this.UI_STATUS_TYPE_ALL={CallMenu="INVALID",PauseMenu="INVALID",EquipHud="INVALID",EquipPanel="INVALID",CqcIcon="INVALID",ActionIcon="INVALID",AnnounceLog="SUSPEND_LOG",BaseName="INVALID",Damage="INVALID",Notice="INVALID",HeadMarker="INVALID",WorldMarker="INVALID",HudText="INVALID",GmpInfo="INVALID",AtTime="INVALID",InfoTypingText="INVALID"}
this.GAME_STATUS_TYPE_ALL={S_DISABLE_PLAYER_PAD=true,S_DISABLE_NPC=true,S_DISABLE_TARGET=true,S_DISABLE_NPC_NOTICE=true,S_DISABLE_PLAYER_DAMAGE=true,S_DISABLE_THROWING=true,S_DISABLE_PLACEMENT=true,S_DISABLE_HUD=true}
this.SAVE_FILE_LOAD_RESULT=this.Enum{"NOT_EXIST_FILE","OK","OK_LOAD_BACKUP","DIFFER_FROM_CURRENT_VERSION","ERROR_LOAD_FAILED"}
this.SAVE_FILE_LOAD_RESULT.INIT=-1
this.SAVE_SLOT={
  GLOBAL=0,
  CHECK_POINT=1,
  RETRY=2,
  MB_MANAGEMENT=3,
  QUEST=4,
  MISSION_START=5,
  CHECK_POINT_RESTARTABLE=6,
  CONFIG=7,
  SAVING=8,
  CONFIG_SAVE=9,
  PERSONAL=10,
  PERSONAL_SAVE=11
}
this.PROGRAM_SAVE_FILE_VERSION_OFFSET=65535
this.GAME_SAVE_FILE_NAME="SSD_GAME_DATA"
this.GAME_SAVE_FILE_NAME_TMP="SSD_GAME_DATA_TMP"
this.CONFIG_SAVE_FILE_NAME="SSD_CONFIG_DATA"
this.PERSONAL_DATA_SAVE_FILE_NAME="PERSONAL_DATA"
this.CATEGORY_MISSION_RESTARTABLE=2
this.SAVE_FILE_INFO={
  [TppScriptVars.CATEGORY_GAME_GLOBAL]={version=104,slot=this.SAVE_SLOT.GLOBAL},
  [TppScriptVars.CATEGORY_MISSION]={version=101,slot=this.SAVE_SLOT.CHECK_POINT},
  [TppScriptVars.CATEGORY_RETRY]={version=100,slot=this.SAVE_SLOT.RETRY},
  [TppScriptVars.CATEGORY_MB_MANAGEMENT]={version=101,slot=this.SAVE_SLOT.MB_MANAGEMENT},
  [TppScriptVars.CATEGORY_QUEST]={version=100,slot=this.SAVE_SLOT.QUEST},
  [TppScriptVars.CATEGORY_CONFIG]={version=100,slot=this.SAVE_SLOT.CONFIG},
  [this.CATEGORY_MISSION_RESTARTABLE]={version=101,slot=this.SAVE_SLOT.CHECK_POINT_RESTARTABLE,missionStartSlot=this.SAVE_SLOT.MISSION_START},
  [TppScriptVars.CATEGORY_PERSONAL]={version=101,slot=this.SAVE_SLOT.PERSONAL}
}
this.PROGRAM_SAVE_FILE_VERSION=TppScriptVars.GetProgramVersionTable()
this.VARS_GROUP_GAME_DATA_ON_START_MISSION=bor(TppScriptVars.GROUP_BIT_GVARS,TppScriptVars.GROUP_BIT_VARS)
this.MISSION_LOAD_TYPE=this.Enum{"MISSION_FINALIZE","MISSION_ABORT","MISSION_RESTART","CONTINUE_FROM_CHECK_POINT"}
this.SERVER_SAVE_TYPE=this.Enum{"MISSION_START","CHECK_POINT","MISSION_END","FLAG_MISSION_END","COOP_MISSION_END","AVATAR_EDIT_END"}
this.LOCATION_ID={
  INIT=1,
  AFGH=10,
  MAFR=20,
  CYPR=30,
  GNTN=40,
  OMBS=45,
  MTBS=50,
  MBQF=55,
  HLSP=60,
  FLYK=70,
  init=1,
  afgh=10,
  mafr=20,
  cypr=30,
  gntn=40,
  ombs=45,
  mtbs=50,
  mbqf=55,
  hlsp=60,
  flyk=70,
  SSD_AFGH=15,
  ssd_afgh=15,
  SSD_OMBS=47,
  ssd_ombs=47,
  AFTR=16,
  aftr=16,
  SSD_AFGH2=17,
  ssd_afgh2=17,
  SBRI=18,
  sbri=18,
  SPFC=19,
  spfc=19,
  SSAV=25,
  ssav=25,
  SAND_AFGH=91,
  SAND_MAFR=92,
  SAND_MTBS=95,
  sand_afgh=91,
  sand_mafr=92,
  sand_mtbs=95
}
this.LOCATION_CHUNK_INDEX_TABLE={
  [this.LOCATION_ID.INIT]=Chunk.INDEX_AFGH,
  [this.LOCATION_ID.AFTR]=Chunk.INDEX_AFGH,
  [this.LOCATION_ID.OMBS]=Chunk.INDEX_AFGH,
  [this.LOCATION_ID.SSD_OMBS]=Chunk.INDEX_AFGH,
  [this.LOCATION_ID.AFGH]=Chunk.INDEX_MAFR,
  [this.LOCATION_ID.MAFR]=Chunk.INDEX_MAFR,
  [this.LOCATION_ID.CYPR]=Chunk.INDEX_MAFR,
  [this.LOCATION_ID.MTBS]=Chunk.INDEX_MAFR,
  [this.LOCATION_ID.MBQF]=Chunk.INDEX_MAFR,
  [this.LOCATION_ID.SSD_AFGH]=Chunk.INDEX_MAFR,
  [this.LOCATION_ID.SSD_AFGH2]=Chunk.INDEX_MAFR,
  [this.LOCATION_ID.SPFC]=Chunk.INDEX_MAFR,
  [this.LOCATION_ID.SSAV]=Chunk.INDEX_MAFR
}
this.WEATHER={SUNNY=0,CLOUDY=1,RAINY=2,SANDSTORM=3,FOGGY=4,POURING=5}
this.MISSION_LIST={"1010","10010","10020","20010","20110","21010","30010","50010","12010","12020","12030","32010","65010","65030","65040","65060",nil}
this.MISSION_ENUM=this.Enum(this.MISSION_LIST)
if Mission.RegisterMissionCodeList then
end
this.MISSING_NUMBER_MISSION_LIST={"12010","12020","12030","65010","65030","65040","65060"}
this.MISSING_NUMBER_MISSION_ENUM=this.Enum(this.MISSING_NUMBER_MISSION_LIST)
this.SYS_MISSION_ID={
  INIT=1,
  TITLE=5,
  AVATAR_EDIT=1010,
  MAFR_AVATAR_EDIT=1020,
  NO_LOCATION_MATCHING_ROOM=21e3,
  TUTORIAL_MATCHING_ROOM=21005,
  AFGH_MATCHING_ROOM=21010,
  SPFC_MATCHING_ROOM=21019,
  MAFR_MATCHING_ROOM=21020,
  SSAV_MATCHING_ROOM=21025,
  AFGH_FREE=30010,
  MAFR_FREE=30020,
  SSD_AFGH_FREE=30010,
  SELECT=6e4
}
this.MISSION_CODE_NONE=65535
this.INVALID_LAYOUT_CODE=65535
this.INVALID_CLUSTER_ID=255
this.STORY_SEQUENCE_LIST={
  "STORY_START",
  "CLEARED_TUTORIAL",
  "BEFORE_k40040",
  "CLEARED_k40040",
  "BEFORE_k40050",
  "CLEARED_k40050",
  "BEFORE_k40060",
  "CLEARED_k40060",
  "BEFORE_k40070",
  "CLEARED_k40070",
  "BEFORE_k40015",
  "CLEARED_k40015",
  "BLACK_RADIO_k40020",
  "BEFORE_k40020",
  "CLEARED_k40020",
  "BEFORE_k40030",
  "CLEARED_k40030",
  "BEFORE_k40035",
  "CLEARED_k40035",
  "BEFORE_DEFENSE_AREA_1",
  "CLEARED_DEFENSE_AREA_1",
  "BEFORE_k40077",
  "CLEARED_k40077",
  "BLACK_TELEPHONE_AFTER_COOP_AREA_1",
  "BEFORE_k40080",
  "CLEARED_k40080",
  "BEFORE_k40090",
  "CLEARED_k40090",
  "BEFORE_k40130",
  "CLEARED_k40130",
  "BEFORE_k40140",
  "CLEARED_k40140",
  "BEFORE_k40150",
  "CLEARED_k40150",
  "BEFORE_k40155",
  "CLEARED_k40155",
  "BEFORE_AFGH_LAST",
  "CLEARED_AFGH_LAST",
  "BLACK_RADIO_MAFR",
  "BEFORE_k40160",
  "CLEARED_k40160",
  "BEFORE_k40180",
  "CLEARED_k40180",
  "BEFORE_k40170",
  "CLEARED_k40170",
  "BEFORE_k40230",
  "CLEARED_k40230",
  "BEFORE_RETURN_TO_AFGH",
  "CLEARED_RETURN_TO_AFGH",
  "BEFORE_s10050",
  "CLEARED_s10050",
  "BEFORE_k40220",
  "CLEARED_k40220",
  "BEFORE_k40250",
  "CLEARED_k40250",
  "BEFORE_k40260",
  "CLEARED_k40260",
  "BEFORE_k40270",
  "CLEARED_k40270",
  "BEFORE_STORY_LAST",
  "CLEARED_STORY_LAST",
  "BEFORE_BASE_DEFENSE_TUTORIAL",
  "CLEARED_BASE_DEFENSE_TUTORIAL",
  "BEFORE_k40320",
  "CLEARED_k40320",
  "BEFORE_k40310",
  "CLEARED_k40310",
  "STORY_FINISH",
  nil
}
this.STORY_SEQUENCE=this.Enum(this.STORY_SEQUENCE_LIST)
if Mission.RegisterStoryFinishSequenceIndex then
  Mission.RegisterStoryFinishSequenceIndex(this.STORY_SEQUENCE.CLEARED_STORY_LAST)
end
if Mission.RegisterClassOpenedSequenceIndex then
  Mission.RegisterClassOpenedSequenceIndex(this.STORY_SEQUENCE.CLEARED_k40310)
end
this.MISSION_COMMON_PACK={
  AFGH_SCRIPT="/Assets/tpp/pack/location/afgh/pack_common/afgh_script.fpk",
  MAFR_SCRIPT="/Assets/ssd/pack/location/mafr/pack_common/mafr_script.fpk",
  CYPR_SCRIPT="/Assets/tpp/pack/location/cypr/pack_common/cypr_script.fpk",
  MTBS_SCRIPT="/Assets/tpp/pack/location/mtbs/pack_common/mtbs_script.fpk",
  AFGH_MISSION_AREA="/Assets/tpp/pack/mission2/common/mis_com_afgh.fpk",
  MAFR_MISSION_AREA="/Assets/tpp/pack/mission2/common/mis_com_mafr.fpk",
  MTBS_MISSION_AREA="/Assets/tpp/pack/mission2/common/mis_com_mtbs.fpk",
  AFGH_HOSTAGE="/Assets/tpp/pack/mission2/common/mis_com_afgh_hostage.fpk",
  MAFR_HOSTAGE="/Assets/tpp/pack/mission2/common/mis_com_mafr_hostage.fpk",
  MAFR_HOSTAGE_WOMAN="/Assets/tpp/pack/mission2/common/mis_com_mafr_hostage_woman.fpk",
  HELICOPTER="/Assets/tpp/pack/mission2/common/mis_com_helicopter.fpk",
  ENEMY_HELI="/Assets/tpp/pack/mission2/common/mis_com_enemy_heli.fpk",
  ORDER_BOX="/Assets/tpp/pack/mission2/common/mis_com_order_box.fpk",
  CODETALKER="/Assets/tpp/pack/mission2/common/mis_com_codetalker.fpk",
  HUEY="/Assets/tpp/pack/mission2/common/mis_com_huey.fpk",
  LIQUID="/Assets/tpp/pack/mission2/common/mis_com_liquid.fpk",
  MANTIS="/Assets/tpp/pack/mission2/common/mis_com_mantis.fpk",
  MILLER="/Assets/tpp/pack/mission2/common/mis_com_miller.fpk",
  OCELOT="/Assets/tpp/pack/mission2/common/mis_com_ocelot.fpk",
  QUIET="/Assets/tpp/pack/mission2/common/mis_com_quiet.fpk",
  SAHELAN="/Assets/tpp/pack/mission2/common/mis_com_sahelan.fpk",
  SKULLFACE="/Assets/tpp/pack/mission2/common/mis_com_skullface.fpk",
  PF_SOLIDER="/Assets/tpp/pack/mission2/common/mis_com_pf_solider.fpk",
  SOVIET_SOLIDER="/Assets/tpp/pack/mission2/common/mis_com_soviet_solider.fpk",
  DD_SOLDIER_WAIT="/Assets/tpp/pack/mission2/common/mis_com_dd_soldier_wait.fpk",
  VOLGIN="/Assets/tpp/pack/mission2/common/mis_com_volgin.fpk",
  WALKERGEAR="/Assets/tpp/pack/mission2/common/mis_com_walkergear.fpk",
  CHILD_SOLDIER="/Assets/tpp/pack/mission2/common/mis_com_child_soldier.fpk",
  XOF_SOLDIER="/Assets/tpp/pack/mission2/common/mis_com_xof_soldier.fpk",
  DD_SOLDIER_ATTACKER="/Assets/tpp/pack/mission2/common/mis_com_dd_soldier_attack.fpk",
  DD_SOLDIER_SNEAKING="/Assets/tpp/pack/mission2/common/mis_com_dd_soldier_sneak.fpk",
  DD_SOLDIER_BTRDRS="/Assets/tpp/pack/mission2/common/mis_com_dd_soldier_btdrs.fpk",
  DD_SOLDIER_ARMOR="/Assets/tpp/pack/mission2/common/mis_com_dd_soldier_armor.fpk",
  FOB_HOSTAGE="/Assets/tpp/pack/mission2/common/mis_com_fob_hostage.fpk",
  SSD_AFGH_SCRIPT="/Assets/ssd/pack/location/afgh/pack_common/afgh_script.fpk",
  SSD_AFGH_MISSION_AREA="/Assets/ssd/pack/mission/common/mis_com_afgh.fpk",
  SSD_AFGH_SPAWN_POINT="/Assets/ssd/pack/mission/common/mis_com_afgh_spawn.fpk",
  ZOMBIE="/Assets/ssd/pack/mission/common/mis_com_zombie.fpk",
  SSD_PLAYER_EMOTION="/Assets/ssd/pack/player/game_object/ssd_emotion.fpk",
  AFTR_SCRIPT="/Assets/ssd/pack/location/afgh/pack_common/afgh_script.fpk",
  SSD_AFGH_SCRIPT="/Assets/ssd/pack/location/afgh/pack_common/afgh_script.fpk",
  SSD_AFGH_MISSION_AREA="/Assets/ssd/pack/mission/common/mis_com_afgh.fpk",
  SBRI_SCRIPT="/Assets/ssd/pack/location/sbri/pack_common/sbri_script.fpk",
  SPFC_SCRIPT="/Assets/ssd/pack/location/spfc/pack_common/spfc_script.fpk",
  SSAV_SCRIPT="/Assets/ssd/pack/location/ssav/pack_common/ssav_script.fpk",
  AFGH_DECOY="/Assets/tpp/pack/collectible/decoy/decoy_svs.fpk",
  MAFR_DECOY="/Assets/tpp/pack/collectible/decoy/decoy_pf.fpk",
  MTBS_DECOY="/Assets/tpp/pack/collectible/decoy/decoy_fob.fpk",
  BEAR="/Assets/tpp/pack/mission2/common/mis_com_bear.fpk",
  RAVEN="/Assets/tpp/pack/mission2/common/mis_com_raven.fpk",
  RAT="/Assets/tpp/pack/mission2/common/mis_com_rat.fpk",
  LYCAON="/Assets/tpp/pack/mission2/common/mis_com_lycaon.fpk",
  JACKAL="/Assets/tpp/pack/mission2/common/mis_com_jackal.fpk",
  EAST_LV="/Assets/tpp/pack/mission2/common/veh_mc_east_lv.fpk",
  EAST_TANK="/Assets/tpp/pack/mission2/common/veh_mc_east_tnk.fpk",
  EAST_TRUCK="/Assets/tpp/pack/mission2/common/veh_mc_east_trc.fpk",
  EAST_TRUCK_AMMUNITION="/Assets/tpp/pack/mission2/common/veh_mc_east_trc_crg_ammunition.fpk",
  EAST_TRUCK_DRUM="/Assets/tpp/pack/mission2/common/veh_mc_east_trc_crg_drum.fpk",
  EAST_TRUCK_GENERATOR="/Assets/tpp/pack/mission2/common/veh_mc_east_trc_crg_generator.fpk",
  EAST_TRUCK_MATERIAL="/Assets/tpp/pack/mission2/common/veh_mc_east_trc_crg_material.fpk",
  EAST_WAV="/Assets/tpp/pack/mission2/common/veh_mc_east_wav.fpk",
  EAST_WAV_ROCKET="/Assets/tpp/pack/mission2/common/veh_mc_east_wav_rocket.fpk",
  WEST_LV="/Assets/tpp/pack/mission2/common/veh_mc_west_lv.fpk",
  WEST_TANK="/Assets/tpp/pack/mission2/common/veh_mc_west_tnk.fpk",
  WEST_TRUCK="/Assets/tpp/pack/mission2/common/veh_mc_west_trc.fpk",
  WEST_TRUCK_CISTERN="/Assets/tpp/pack/mission2/common/veh_mc_west_trc_crg_cistern.fpk",
  WEST_TRUCK_CONTAINER="/Assets/tpp/pack/mission2/common/veh_mc_west_trc_crg_container.fpk",
  WEST_TRUCK_ITEMBOX="/Assets/tpp/pack/mission2/common/veh_mc_west_trc_crg_itembox.fpk",
  WEST_TRUCK_HOOD="/Assets/tpp/pack/mission2/common/veh_mc_west_trc_hood.fpk",
  WEST_WAV="/Assets/tpp/pack/mission2/common/veh_mc_west_wav.fpk",
  WEST_WAV_CANNON="/Assets/tpp/pack/mission2/common/veh_mc_west_wav_trt_cannon.fpk",
  WEST_WAV_MACHINE_GUN="/Assets/tpp/pack/mission2/common/veh_mc_west_wav_trt_machinegun.fpk",
  AMBULANCE="/Assets/tpp/pack/mission2/common/veh_mc_ambulance.fpk",
  AVATAR_EDIT="/Assets/ssd/pack/mission/common/mis_com_avatar_edit.fpk",
  AVATAR_ASSET_LIST={
    "/Assets/tpp/pack/player/avatar/deform/avm_dfrm_men_mtar.fpk",
    "/Assets/tpp/pack/player/avatar/face/plfova_avm0_type0_v00.fpk",
    "/Assets/tpp/pack/player/avatar/face/plfova_avm0_type1_v00.fpk",
    "/Assets/tpp/pack/player/avatar/face/plfova_avm0_type2_v00.fpk",
    "/Assets/tpp/pack/player/avatar/face/plfova_avm0_type3_v00.fpk",
    "/Assets/tpp/pack/player/avatar/face/plfova_avm0_type4_v00.fpk",
    "/Assets/tpp/pack/player/avatar/face/plfova_avm0_type5_v00.fpk",
    "/Assets/tpp/pack/player/avatar/face/plfova_avm0_type6_v00.fpk",
    "/Assets/tpp/pack/player/avatar/face/plfova_avm0_type7_v00.fpk",
    "/Assets/tpp/pack/player/avatar/deform/pldfrm_avm0_type0_v00.fpk",
    "/Assets/tpp/pack/player/avatar/deform/pldfrm_avm0_type1_v00.fpk",
    "/Assets/tpp/pack/player/avatar/deform/pldfrm_avm0_type2_v00.fpk",
    "/Assets/tpp/pack/player/avatar/deform/pldfrm_avm0_type3_v00.fpk",
    "/Assets/tpp/pack/player/avatar/deform/pldfrm_avm0_type4_v00.fpk",
    "/Assets/tpp/pack/player/avatar/deform/pldfrm_avm0_type5_v00.fpk",
    "/Assets/tpp/pack/player/avatar/deform/pldfrm_avm0_type6_v00.fpk",
    "/Assets/tpp/pack/player/avatar/deform/pldfrm_avm0_type7_v00.fpk",
    "/Assets/tpp/pack/player/avatar/hair/plfova_avm_hair_a0_v00.fpk",
    "/Assets/tpp/pack/player/avatar/hair/plfova_avm_hair_b0_v00.fpk",
    "/Assets/tpp/pack/player/avatar/hair/plfova_avm_hair_c0_v00.fpk",
    "/Assets/tpp/pack/player/parts/plparts_avatar_man.fpk",
    "/Assets/tpp/pack/player/avatar/body/plfova_avm0_main0_skin0_c00.fpk",
    "/Assets/tpp/pack/player/avatar/body/plfova_avm0_main0_skin0_c01.fpk",
    "/Assets/tpp/pack/player/avatar/body/plfova_avm0_main0_skin0_c02.fpk",
    "/Assets/tpp/pack/player/avatar/body/plfova_avm0_main0_skin0_c03.fpk",
    "/Assets/tpp/pack/player/avatar/body/plfova_avm0_main0_skin0_c04.fpk",
    "/Assets/tpp/pack/player/parts/plvoice_ddm_a.fpk",
    "/Assets/tpp/pack/player/parts/plvoice_ddm_b.fpk",
    "/Assets/tpp/pack/player/parts/plvoice_ddm_c.fpk",
    "/Assets/tpp/pack/player/parts/plvoice_ddm_d.fpk",
    "/Assets/tpp/pack/ui/ui_avatar_edit_men.fpk"
  },
  AVATAR_ASSET_LIST_FEMALE={
    "/Assets/ssd/pack/player/avatar/deform/avm_dfrm_women_mtar.fpk",
    "/Assets/ssd/pack/player/avatar/face/plfova_avf0_type0_v00.fpk",
    "/Assets/ssd/pack/player/avatar/face/plfova_avf0_type1_v00.fpk",
    "/Assets/ssd/pack/player/avatar/face/plfova_avf0_type2_v00.fpk",
    "/Assets/ssd/pack/player/avatar/face/plfova_avf0_type3_v00.fpk",
    "/Assets/ssd/pack/player/avatar/face/plfova_avf0_type4_v00.fpk",
    "/Assets/ssd/pack/player/avatar/face/plfova_avf0_type5_v00.fpk",
    "/Assets/ssd/pack/player/avatar/face/plfova_avf0_type6_v00.fpk",
    "/Assets/ssd/pack/player/avatar/face/plfova_avf0_type7_v00.fpk",
    "/Assets/ssd/pack/player/avatar/deform/pldfrm_avf0_type0_v00.fpk",
    "/Assets/ssd/pack/player/avatar/deform/pldfrm_avf0_type1_v00.fpk",
    "/Assets/ssd/pack/player/avatar/deform/pldfrm_avf0_type2_v00.fpk",
    "/Assets/ssd/pack/player/avatar/deform/pldfrm_avf0_type3_v00.fpk",
    "/Assets/ssd/pack/player/avatar/deform/pldfrm_avf0_type4_v00.fpk",
    "/Assets/ssd/pack/player/avatar/deform/pldfrm_avf0_type5_v00.fpk",
    "/Assets/ssd/pack/player/avatar/deform/pldfrm_avf0_type6_v00.fpk",
    "/Assets/ssd/pack/player/avatar/deform/pldfrm_avf0_type7_v00.fpk",
    "/Assets/ssd/pack/player/avatar/hair/plfova_avf_hair_a0_v00.fpk",
    "/Assets/ssd/pack/player/avatar/hair/plfova_avf_hair_b0_v00.fpk",
    "/Assets/ssd/pack/player/avatar/hair/plfova_avf_hair_c0_v00.fpk",
    "/Assets/ssd/pack/player/avatar/hair/plfova_avf_hair_d0_v00.fpk",
    "/Assets/tpp/pack/player/parts/plparts_avatar_woman.fpk",
    "/Assets/tpp/pack/player/avatar/body/plfova_avf0_main0_skin0_c00.fpk",
    "/Assets/tpp/pack/player/avatar/body/plfova_avf0_main0_skin0_c01.fpk",
    "/Assets/tpp/pack/player/avatar/body/plfova_avf0_main0_skin0_c02.fpk",
    "/Assets/tpp/pack/player/avatar/body/plfova_avf0_main0_skin0_c03.fpk",
    "/Assets/tpp/pack/player/avatar/body/plfova_avf0_main0_skin0_c04.fpk",
    "/Assets/tpp/pack/player/parts/plvoice_ddf_a.fpk",
    "/Assets/tpp/pack/player/parts/plvoice_ddf_b.fpk",
    "/Assets/tpp/pack/player/parts/plvoice_ddf_c.fpk",
    "/Assets/tpp/pack/player/parts/plvoice_ddf_d.fpk",
    "/Assets/ssd/pack/ui/ui_avatar_edit_women.fpk"
  }
}
this.SOLIDER2_COMMON_PACK={
  default="/Assets/ssd/pack/npc/common/NpcHumanCommon.fpk",
  s10150_special="/Assets/tpp/pack/mission2/story/s10150/s10150_special_npc.fpk",
  s10151_special="/Assets/tpp/pack/mission2/story/s10151/s10151_special_npc.fpk",
  s10151_ending="/Assets/tpp/pack/mission2/story/s10151/s10151_ending_npc.fpk"
}
for E,A in pairs(this.SOLIDER2_COMMON_PACK)do
  this.SOLIDER2_COMMON_PACK[Fox.StrCode32(E)]=A
end
this.DEFAULT_SOLIDER2_COMMON_PACKAGE=Fox.StrCode32"default"
this.SOLIDER2_COMMON_PACK_PREREQUISITES={s10150_special={"mission_block"},s10151_special={"mission_block"},s10151_ending={"mission_block"}}
this.AFR_ARMOR={TYPE_CFA=1,TYPE_ZRS=2,TYPE_RC=3}
this.QUEST_DEFINE={}
this.QUEST_RANDOM_FACE_DEFINE={"quest_q20015","quest_q20025","quest_q20035","quest_q20045","quest_q20055","quest_q20065","quest_q20075","quest_q20085","quest_q20095","quest_q20105","quest_q20205","quest_q20305","quest_q20405","quest_q20505","quest_q20605","quest_q20705","quest_q20805","quest_q20905","quest_q21005","quest_q22005","quest_q23005","quest_q24005","quest_q25005","quest_q26005","quest_q27005"}
this.QUEST_TYPE={STORY=1,RECOVERED=2,ELIMINATE=3,ANIMAL_RECOVERED=4,DEVELOP_RECOVERED=5,GIMMICK_RECOVERED=6,MSF_RECOVERED=7,SHOOTING_PRACTIVE=8,DEFENSE=9,COLLECTION=10,ANIMAL=11}
this.QUEST_CLEAR_TYPE={NONE=1,CLEAR=2,FAILURE=3,UPDATE=4}
this.QUEST_RACE_TYPE={CAUCASIAN=0,BROWN=1,BLACK=2,ASIA=3}
this.QUEST_GENDER_TYPE={MAN=0,WOMAN=1}
if#this.QUEST_DEFINE>this.QUEST_MAX then
end
this.QUEST_INDEX=this.Enum(this.QUEST_DEFINE)
if#this.QUEST_RANDOM_FACE_DEFINE>this.QUEST_FACE_MAX then
end
this.QUEST_RANDOM_FACE_INDEX=this.Enum(this.QUEST_RANDOM_FACE_DEFINE)
this.QUEST_RANK_LIST={"S","A","B","C","D","E","F","G","H","I"}
this.QUEST_RANK=Tpp.Enum(this.QUEST_RANK_LIST)
this.QUEST_BONUS_GMP={[this.QUEST_RANK.S]=3e5,[this.QUEST_RANK.A]=2e5,[this.QUEST_RANK.B]=18e4,[this.QUEST_RANK.C]=14e4,[this.QUEST_RANK.D]=12e4,[this.QUEST_RANK.E]=1e5,[this.QUEST_RANK.F]=9e4,[this.QUEST_RANK.G]=8e4,[this.QUEST_RANK.H]=6e4,[this.QUEST_RANK.I]=3e4}
this.QUEST_RANK_TABLE={}
this.QUEST_BODY_ID_LIST={AFGH_ARMOR=49,MAFR_ARMOR=109,Q20910=207,Q20911=208,Q20912=209,Q20913=205,Q20914=206,Q19010=259,Q19011=255,Q19012=111,Q19013=110,Q99070=110,Q99071=264,Q99072=110,MSF_01=280,MSF_02=281,MSF_03=292,MSF_04=293,MSF_05=294,MSF_06=295,MSF_07=286,MSF_08=297,MSF_09=288,MSF_10=289,Q99080_01=373,Q99080_02=374,MAFR_ARMOR_ZRS=TppEnemyBodyId.pfa0_v00_a,MAFR_ARMOR_CFA=TppEnemyBodyId.pfa0_v00_b,MAFR_ARMOR_RC=TppEnemyBodyId.pfa0_v00_c,AFGH_HOSTAGE_MALE=TppEnemyBodyId.prs2_main0_v00,MAFR_HOSTAGE_MALE=TppEnemyBodyId.prs5_main0_v00,AFGH_HOSTAGE_FEMALE=TppEnemyBodyId.prs3_main0_v00,MAFR_HOSTAGE_FEMALE=TppEnemyBodyId.prs6_main0_v00}
this.QUEST_FACE_ID_LIST={Q19010=601,Q19011=609,Q19012=648,Q19013=647,Q99070=640,Q99071=641,Q99072=646,TAN=621,DEFAULT_MAN=0,DEFAULT_WOMAN=500,AFGH_BALACLAVA=TppEnemyFaceId.svs_balaclava,MAFR_BALACLAVA=TppEnemyFaceId.pfs_balaclava}
this.QUEST_BLOCK_TYPE_DEFINE={"quest_block_1","quest_block_2","quest_block_3"}
this.QUEST_BLOCK_TYPE_INDEX=Tpp.Enum(this.QUEST_BLOCK_TYPE_DEFINE)
this.FLAG_MISSION_CLEAR_TYPE={NONE=1,CLEAR=2,FAILURE=3}
this.BASE_DEFENSE_CLEAR_TYPE={NONE=1,CLEAR=2,FAILURE=3,ABANDON=4}
this.DEFENSE_GAME_STATE={NONE=Mission.DEFENSE_STATE_NONE,PREPARE=Mission.DEFENSE_STATE_PREPARE,WAVE=Mission.DEFENSE_STATE_WAVE,WAVE_INTERVAL=Mission.DEFENSE_STATE_WAVE_INTERVAL,ESCAPE=Mission.DEFENSE_STATE_ESCAPE,RESULT=Mission.DEFENSE_STATE_RESULT}
this.MISSION_CLEAR_RANK_LIST={"S","A","B","C","D","E"}
this.MISSION_CLEAR_RANK=Tpp.Enum(this.MISSION_CLEAR_RANK_LIST)
this.MISSION_CLEAR_RANK.NOT_DEFINED=0
this.INITIAL_PLAYER_STATE={MIN=0,ON_FOOT=1,RIDEON_HELICOPTER=2,MAX=3}
this.MB_FREEPLAY_DEMO_PRIORITY_LIST={}
this.MB_FREEPLAY_DEMO_ENUM=this.Enum(this.MB_FREEPLAY_DEMO_PRIORITY_LIST)
this.FORCE_MB_RETURN_RADIO_LIST={}
this.FORCE_MB_RETURN_RADIO_ENUM=this.Enum(this.FORCE_MB_RETURN_RADIO_LIST)
this.MB_FREEPLAY_DEMO_REQUESTFLAG_LIST={"PlayAfterQuietBattle","PlayAfterDethFactory","PlayAfterWhiteMamba"}
this.MB_FREEPLAY_DEMO_REQUESTFLAG_DEFINE=this.Enum(this.MB_FREEPLAY_DEMO_REQUESTFLAG_LIST)
this.MISSION_TYPE={STORY=MissionType.STORY,FLAG=MissionType.FLAG,DEFENSE=MissionType.DEFENSE,QUEST=MissionType.QUEST,COOP=MissionType.COOP,MATCHING=MissionType.MATCHING}
this.GAME_OVER_TYPE={PLAYER_DEAD=1,PLAYER_FALL_DEAD=2,HELICOPTER_DESTROYED=3,TARGET_DEAD=4,OUTSIDE_OF_MISSION_AREA=5,FOB_TIME_OVER=6,TARGET_ESCAPE=7,TARGET_ESCAPE_BY_HELI=8,PLAYER_KILL_CHILD_SOLDIER=9,FOB_FULTONED=10,ON_DISCOVERY=11,FOB_ABORT=12,FOB_ESCAPE=13,S10060_RETURN_END=14,DEFENSE_TARGET_WAS_DESTROYED=15,S10035_TOO_CLOSE_KAIJU=16,S10035_TIME_OVER=17,S10035_OUT_OF_MISSION_AREA=18,OUT_OF_DEFENSE_GAME_AREA=19,ABORT=254,GAME_OVER_DEMO_MASK=255,MAX=256}
this.GAME_OVER_RADIO={PLAYER_DEAD=1,OUT_OF_MISSION_AREA=2,OUT_OF_MISSION_AREA_HELI=3,HELICOPTER_DESTROYED=4,PLAYER_DESTROY_HELI=5,RIDING_HELI_DESTROYED=6,TARGET_DEAD=7,PLAYER_KILL_TARGET=8,PLAYER_KILL_TARGET_WOMAN=9,PLAYER_KILL_CHILD_SOLDIER=10,PLAYER_KILL_DD=11,OTHERS=255,MAX=256}
this.COMMON_RADIO={ENEMY_RECOVERED=1,HOSTAGE_RECOVERED=2,HOSTAGE_DEAD=3,HOSTAGE_DAMAGED_FROM_PC=4,PHASE_DOWN_OUTSIDE_HOTZONE=5,OUTSIDE_MISSION_AREA=6,OUTSIDE_HOTZONE_ALERT=7,OUTSIDE_HOTZONE=8,RETURN_HOTZONE=9,ABORT_BY_HELI=10,RECOMMEND_CURE=11,SUPPRESSOR_BROKEN=12,CALL_HELI_FIRST_TIME=13,CALL_HELI_FIRST_TIME_HOT_ZONE=14,CALL_HELI_SECOND_TIME=15,RESULT_RANK_S=16,RESULT_RANK_A=17,RESULT_RANK_B=18,RESULT_RANK_C=19,RESULT_RANK_D=20,RESULT_RANK_E=21,RECOVERED_RUSSIAN_INTERPRETER=22,CALL_SUPPROT_BUDDY=23,TARGET_MARKED=24,SEARCH_TARGET_ENABLED=25,RESULT_RANK_NOT_DEFINED=26,TARGET_RECOVERED=27,TARGET_ELIMINATED=28,CANNOT_GET_INTEL_ON_ALERT=29,CALL_BUDDY_QUIET_WHILE_FORCE_HOSPITALIZE=30,OUTSIDE_HOTZONE_CHANGE_SNEAK=31,UNLOCK_LANDING_ZONE=32,DISCOVERED_BY_SNIPER=33,DISCOVERED_BY_ENEMY_HELI=34,PLAYER_NEAR_ENEMY_HELI=35,HELI_LOST_CONTROL_END=36,HELI_LOST_CONTROL_END_ENEMY_ATTACK=37,HELI_DAMAGE_FROM_PLAYER=38,DISABLE_TRANSLATE_RUSSIAN=39,DISABLE_TRANSLATE_AFRIKANS=40}
this.MISSION_CLEAR_TYPE={ON_FOOT=1,RIDE_ON_HELICOPTER=2,RIDE_ON_VEHILCE=3,FOB_GOAL=4,FOB_ESCAPE=5,FREE_PLAY_ORDER_BOX_DEMO=6,FROM_HELISPACE=7,QUEST_BOSS_QUIET_BATTLE_END=8,QUEST_LOST_QUIET_END=9,QUEST_INTRO_RESCUE_EMERICH_END=10,CYPRUS_GOAL=11,RIDE_ON_FULTON_CONTAINER=12,FREE_PLAY_NO_ORDER_BOX=13,FORCE_GO_TO_MB_ON_SIDE_OPS_CLEAR=14,HELI_TAX_MB_FREE_CLEAR=15,FOB_DO_CRIME=16,LOCATION_CHANGE_WITH_FAST_TRAVEL=17}
this.ELAPSED_MISSION_EVENT_LIST={"D_DOG_COME_TO_GET","D_DOG_GO_WITH_ME","QUIET_WITH_GO_MISSION","QUIET_VISIT_MISSION","DECISION_HUEY","THE_GREAT_ESCAPE_LIQUID","FAILED_RETAKE_THE_PLATFORM","CAN_REUNION_QUIET","RADIATION_LEAK_MATHER_BASE","MOVE_SAHELANTHROPUS","BATTLEGEAR_HANGER_LEVELUP","AFTER_THE_GREAT_ESCAPE_LIQUID","STORY_SEQUENCE"}
if#this.ELAPSED_MISSION_EVENT_LIST>this.ELAPSED_MISSION_COUNT_MAX then
end
this.ELAPSED_MISSION_EVENT=this.Enum(this.ELAPSED_MISSION_EVENT_LIST)
this.INIT_ELAPSED_MISSION_COUNT={D_DOG_COME_TO_GET=2,D_DOG_GO_WITH_ME=6,QUIET_WITH_GO_MISSION=3,QUIET_VISIT_MISSION=1,DECISION_HUEY=1,THE_GREAT_ESCAPE_LIQUID=1,FAILED_RETAKE_THE_PLATFORM=3,CAN_REUNION_QUIET=11,POD_IN_CORPSE_01=1,RADIATION_LEAK_MATHER_BASE=2,MOVE_SAHELANTHROPUS=1,BATTLEGEAR_HANGER_LEVELUP=2,AFTER_THE_GREAT_ESCAPE_LIQUID=1,STORY_SEQUENCE=2}
this.WEAPONSLOT={MIN=0,PRIMARY_HIP=0,PRIMARY_BACK=1,SECONDARY=2,SUPPORT_0=3,SUPPORT_1=4,SUPPORT_2=5,SUPPORT_3=6,SUPPORT_4=7,SUPPORT_5=8,SUPPORT_6=9,SUPPORT_7=10,MAX=11,GUN_WEAPON_MAX=4}
this.HONEY_BEE_EQUIP_ID=TppEquip.EQP_WP_HoneyBee
this.INIT_MAG={ASSAULT_DEFAULT=8,MACHINEGUN_DEFAULT=3,SHOTGUN_DEFAULT=10,SNIPER_DEFAULT=10,MISSILE_DEFAULT=4,HANDGAN_DEFAULT=10,SUBMACHINEGUN_DEFAULT=10}
this.SCRIPT_BLOCK_STATE={MIN=0,EMPTY=1,ALLOCATED=1,INITIALIZED=2,ACTIVATE_REQUESTED=3,WAITING_ACTIVATE=4,ACTIVATED=5,MAX=6}
this.HOSTAGE_UNLOCK_START=0
this.HOSTAGE_UNLOCK_FINISH=1
this.STOCK_DIRECTION_RIGHT=0
this.STOCK_DIRECTION_LEFT=1
this.TIPS={TIPS=1,R3_ZOOM=2,COVER=3,COVER_SHOOT=4,QUICK_DIVE=5,REFLEX_MODE=6,WEAPON_RANGE=7,RETICLE_COLOR=8,RELOAD=9,STOCK_CHANGE=10,INJURY=11,AUTO_AIM=12,VIEWPOINT_WEAPON=13,TAKE_DOWN=14,BASIC=15,SPOTTED=16,INFILTRATING=17,BINO_MARKING=18,PUT_MARKER=19,RADIO_ESPIONAGE=20,LOG=21,COMOF_STANCE=22,STEALTH_MODE=23,TRASH=24,TOILET=25,HORSE_HIDEACTION=26,ACTION_MAKENOISE=27,CALL_MENU=28,TRANQUILIZER=29,PICKUP_WEAPON=30,AMMO=31,CARRY_WEAPON_LIMIT=32,HOLD_UP=33,SUPPRESSOR=34,THROW_EQUIP=35,NVG=36,BINOCULARS=37,AUDIO_CUE=38,MARKING=39,NIGHT=40,COMBAT_ALERT=41,ELUDE=42,QUICK_CHANGE=43,CQC=44,CQC_THROW=45,CQC_ATTACK=46,CQC_HOLD_UP=47,CQC_COMB=48,CQC_HOLD=49,CQC_INTERROGATION=50,CQC_CHOKE=51,CQC_KILL=52,HOLD_UP_INTERROGATION=53,GET_DOWN=54,INTERPRETER=55,FREE_RUN=56,DAY_NIGHT_SHIFT=57,COMOF_NIGHT=58,COMOF_INGRASS=59,SAND_STORM=60,COMOF_VEHICLE=61,TRACK_HIDE=62,ROLLING=63,CRACK_CLIMB=64,BULLET_PENETRATE=65,NON_LETHAL_BULLET=66,BULLET_REFILL=67,SUPPLY_WEAPON=68,SUPPORT_HELI=69,ACC=70,TACTICAL_BUDDY=71,BUDDY_COMMAND=72,BUDDY_HORSE=73,ANIMALS=74,SAVE_ANIMAL=75,PLANT=76,DIAMOND=77,MATERIAL=78,COMMUNICATOR=79,ELECTRICITY=80,RADAR=81,SEARCH_LIGHT=82,GUN_LIGHT=83,SNIPER_RIFLE=84,FLARE_GRENADE=85,ITEM=86,CARDBOARD_BOX=87,PHANTOM_CIGAR_TOILET=88,MICROPHONE=89,MB_DEVICE=90,FULLTON_DEVICE=91,SHOWER_ROOM=92,MB_CLASS_FUNCTION=93,FULTON_CLASS_FUNCTION_STOP=94,GMP=95,LOSS_GMP=96,RANK=97,MORALE=98,EMBLEM=99,RECO_TRANQUILIZER=100,FREE=101,SKILL=102,WOOD_BOX=103,RED_DRUMS=104,FOG=105,MAP_SHORTCUT=106,FULLTON_RECOVERY=107,FULTON_MACHINEGUN=108,DEV_DOCUMENT=109,BOX_MOVE=110,SUPPORT_ATTACK=111,HEROISM=112,CODENAMES=113,DEVELOPMENT=114,TANK=115,GUNSHIP=116,BUDDY_DOG=117,DECOY=118,MINE=119,ACTIVE_SONAR=120,BUDDY_WALKER=121,FULTON_COMMON_VEHICLE=122,FULTON_CONTAINER=123,RAIN=124,UNDER_BARREL=125,BUDDY_QUIET=126,SLEEP_GUS=127,TROUBLE=128,FOB_WORM_HOLE=129,INJURY_2=130,BULLET_PENETRATE_FAIL=131,ANIMAL_CAGE=132,FULTON_MORTAR=133,FULTON_ANTI_AIRCRAFT=134,PHANTOM_CIGAR_TRASH=135,FOB_ABILITY=136,WORM_HOLE=137,FOB_SHIELD=138,ESP_POINT=139,STAFF_RANK_BONUS=140,FOB_GOAL=141,FOB_GOAL_BONUS=142,DIRECT_CONTRACTS=143,REVENGE_WORM_HOLE=144,NUCLEAR_WEAPON=145,FOB_HERO=146,EQUIPPED_GUARDS=147,PF_RATING=148,PF_POINT=149,FOB_SUPPORT=150,FOB_RESCUE_STAFF=151,EMERGENCES=152,FOB_CONSTRUCT=153,ONLINE_DISPATCH_MISSION=154}
this.TIPS_REDUNDANT_REF={[this.TIPS.INJURY_2]=this.TIPS.INJURY,[this.TIPS.BULLET_PENETRATE_FAIL]=this.TIPS.BULLET_PENETRATE,[this.TIPS.ANIMAL_CAGE]=this.TIPS.SAVE_ANIMAL,[this.TIPS.FULTON_MORTAR]=this.TIPS.FULTON_MACHINEGUN,[this.TIPS.FULTON_ANTI_AIRCRAFT]=this.TIPS.FULTON_MACHINEGUN,[this.TIPS.PHANTOM_CIGAR_TRASH]=this.TIPS.PHANTOM_CIGAR_TOILET}
this.CONTINUE_TIPS_TABLE={[this.STORY_SEQUENCE.STORY_START]={"BASIC","SPOTTED"}}
this.CONTROL_GUIDE={MB_DEVICE=1,BINO=2,BINO_ZOOM=3,OPTIONALRADIO=4,CUSTUMMARKER=5,ADVICE=6,HORSE_CALL=7,HORSE_HIDE=8,HORSE_HIDE_CHANGE=9,HORSE_RUN=10,HORSE_RIDEON=11,HORSE_GETOFF=12,GET_INTEL=13,ATTACK=14,RELOAD=15,CURE=16,JUMP=17,STANCE=18,LOOK_IN=19,ELUDE_UP=20,ELUDE_DOWN=21,CLIMEB_UP=22,ROLLING=23,COVER_ATTACK=24,SHOULDER=25,SHOULDER_THROW=26,HULTON=27,PIPE_UP=28,FREECLIMD=29,GARBAGEBOX_HIDE=30,CQC=31,CQC_PUNCH=32,CQC_THROW=33,RESTRAINT2=34,NONE=35,INTERROGATION=36,SWOON=37,KILL=38,C4_SET=39,C4_EXPLODING=40,ACCELARATER=41,BRAKE=42,HELI_RIDEON=43,HELI_GETOFF=44,CQC_COMBO=45,EQUIPMENT_WP=46,CAMERA_MOVE=47,CAMERA_ZOOM=48,CAMERA_CHANGE=49,PLAY_MOVE=50,PLAY_COVER=51,PLAY_DASH=52,PLAY_EVADE=53,ORDER_CHILD=54,MACHINEGUN=55,MORTAR=56,ANTI_AIRCRAFT=57,SEARCH_LIGHT=58,UNDER_BARREL=59,MOVE_IN_HELI=60,BOOSTER_SCOPE=61,DRIVE_COMMON_VEHICLE=62,DRIVE_WALKER_GEAR=63,RIDE_HORSE=64,SNIPER_RIFLE=65,SHIELD=66,STANCE_SQUAT=67,STANCE_CRAWL=68,STEP_FENCE=69,ATTACK_VEHICLE_SHOOT=70,ATTACK_VEHICLE_CAMERA=71,VEHICLE_LIGHT=72}
this.PAUSE_CONTROL_GUIDE={[this.CONTROL_GUIDE.DRIVE_COMMON_VEHICLE]="vehicle",[this.CONTROL_GUIDE.DRIVE_WALKER_GEAR]="walker-gear",[this.CONTROL_GUIDE.RIDE_HORSE]="horse"}
this.CONTROL_GUIDE_LANG_ID_LIST={"tutorial_mb_device","tutorial_bino","tutorial_bino_zoom","tutorial_optionalradio","tutorial_set_marker","tutorial_advice","tutorial_horse_call","tutorial_horse_hide","tutorial_horse_hide_change","tutorial_horse_run","tutorial_horse_rideon","tutorial_horse_getoff","tutorial_get_intel","tutorial_attack","tutorial_reload","tutorial_cure","tutorial_jump","tutorial_stance","tutorial_look_in","tutorial_elude_up","tutorial_elude_down","tutorial_climeb_up","tutorial_rolling","tutorial_cover_attack","tutorial_shoulder","tutorial_shoulder_throw","tutorial_hulton","tutorial_pipe","tutorial_cliff","tutorial_garbagebox_hide","tutorial_cqc","tutorial_cqc_punch","tutorial_cqc_throw","tutorial_restraint2","","tutorial_interrogation","tutorial_swoon","tutorial_kill","tutorial_C4_set","tutorial_C4_exploding","tutorial_accelarater","tutorial_brake","tutorial_heli_rideon","tutorial_heli_getoff","tutorial_cqc_combo","tutorial_equipment_wp","tutorial_camera_move","tutorial_camera_zoom","tutorial_camera_change","tutorial_play_move","tutorial_play_cover","tutorial_play_dash","tutorial_play_evade","tutorial_order_child","tutorial_attack_machinegun","tutorial_attack_mortar","tutorial_attack_anti_aircraft","tutorial_searchlight_onoff","tutorial_change_barrel","tutorial_play_move","tutorial_bino_zoom","tutorial_show_controller","tutorial_show_controller","tutorial_show_controller","tutorial_change_camera","tutorial_shield2","tutorial_stance3","tutorial_stance2","tutorial_fence_jump","tutorial_v_attack","tutorial_v_fps_tps","tutorial_searchlight_onoff"}
this.GMP_COST_TYPE={FULTON=1,SUPPORT_SUPPLY=2,SUPPORT_ATTACK=3,CALL_HELLI=4,BUDDY=5,CLEAR_SIDE_OPS=6,DESTROY_SUPPORT_HELI=7}
this.CLUSTER_NAME={"Command","Combat","Develop","Support","Medical","Spy","BaseDev"}
this.CLUSTER_DEFINE=this.Enum(this.CLUSTER_NAME)
this.FOB_EVENT_ID_LIST={ARMOR={3},HOSTAGE={3},ZOMBIE={5},PARASITE_METAL={5}}
this.STATION_LIST={afgh={"bridge","enemyBase","field","fort","tent","cliffTown","commFacility","powerPlant","remmnants","slopedTown","sovietBase","village"},mafr={"banana","diamond","lab","flowStation","hill","outland","pfCamp","savannah","swamp"},mtbs={"Command","Combat","Develop","Support","Medical","Spy","BaseDev"}}
this.STAFF_TYPE_ID={NORMAL=1,COMBAT=2,DEVELOP=3,BASE_DEV=4,SUPPORT=5,SPY=6,MEDICAL=7}
this.UNIQUE_STAFF_TYPE_ID={SNEAK=248,OCELOT=249,MILLER=250,QUIET=251,HUEY=252,CODETALKER=253,INITIAL_STAFF_01=0,INITIAL_STAFF_02=1,INITIAL_STAFF_03=2,FULTON_LESSON_STAFF_01=3,FULTON_LESSON_STAFF_02=4,FULTON_LESSON_STAFF_03=5,FULTON_LESSON_STAFF_04=6,FULTON_LESSON_STAFF_05=7,FULTON_LESSON_STAFF_06=8,FULTON_LESSON_STAFF_07=9,FULTON_LESSON_STAFF_08=10,FULTON_LESSON_STAFF_09=33,FULTON_LESSON_STAFF_10=34,FULTON_LESSON_STAFF_11=35,FULTON_LESSON_STAFF_12=36,FULTON_LESSON_STAFF_13=45,FULTON_LESSON_STAFF_14=46,S10080_GUN_SMITH=11,S10080_ENGINEER=12,S10054_HOSTAGE_01=58,S10054_HOSTAGE_02=93,S10054_HOSTAGE_03=94,S10054_HOSTAGE_04=95,S10054_HOSTAGE_05=96,S10054_HOSTAGE_06=97,S10043_INTERPRETER=14,S10086_INTERPRETER=15,S10036_COMMANDER=16,S10040_DEAF_HOSTAGE=17,S10052_MALAK=18,S10052_DRIVER=19,S10085_FEMALE_HOSTAGE=20,S10120_OUTLAND_HOSTAGE=102,S10121_PF_OPERATOR=21,S10121_WEAPON_DEALER=22,S10200_TARGET_HOSTAGE=23,S10200_BONUS_HOSTAGE=24,S10200_CHILD_COMMANDER=25,S10100_BANANA_TARGET=26,S10171_BONUS_SOLIDER=27,S10085_HOSTAGE=28,S10041_FIELD_COMMANDER=29,S10041_VILLAGE_COMMANDER=30,S10041_ENEMY_BASE_COMMANDER=31,S10041_FIELD_DRIVER=47,S10041_FIELD_BODYGUARD=48,S10041_ENEMY_BASE_DRIVER=49,S10041_ENEMY_BASE_BODYGUARD=50,S10044_CLIFFTOWN_VIP=62,S10044_CLIFFTOWN_HOSTAGE=92,S10033_TARGET_HOSTAGE=32,S10211_TRAFFICKER=37,S10211_BODYGUARD_01=51,S10211_BODYGUARD_02=52,S10211_BODYGUARD_03=53,S10211_BODYGUARD_04=54,S10211_BODYGUARD_05=55,S10045_TARGET_HOSTAGE=38,S10045_EXECUTIONER=39,S10115_MOSQUITO=40,S10195_TARGET=41,S10195_TRACER=42,S10195_HOSTAGE=43,S10020_ENEMY_BASE_COMMANDER=56,S10020_DRIVER=57,S10086_HOSTAGE_A=44,S10086_HOSTAGE_B=63,S10086_HOSTAGE_C=64,S10086_HOSTAGE_D=65,S10091_EXECUTEUNIT_A=66,S10091_EXECUTEUNIT_B=67,S10091_SWAMPNEAR_HOSTAGE=100,S10091_TRUCK_DRIVER=101,S10156_HOSTAGE=109,S10043_HOSTAGE_A=87,S10043_HOSTAGE_B=88,S10082_HOSTAGE_A=98,S10082_HOSTAGE_B=99,S10045_HOSTAGE_A=107,S10045_HOSTAGE_B=108,S10045_HOSTAGE_TARGET=38,S10045_EXECUTION=39,S10033_HOSTAGE=89,S10093_ZRS_CAPTAIN=68,S10041_HOSTAGE_A=90,S10041_HOSTAGE_B=91,S10211_HOSTAGE_A=103,S10211_HOSTAGE_B=104,S10211_HOSTAGE_C=105,S10211_HOSTAGE_D=106,QUEST_MSF_01=69,QUEST_MSF_02=70,QUEST_MSF_03=71,QUEST_MSF_04=72,QUEST_MSF_05=73,QUEST_MSF_06=74,QUEST_MSF_07=75,QUEST_MSF_08=76,QUEST_MSF_09=77,QUEST_MSF_10=78,QUEST_PASHTO=80,QUEST_KIKONGO=81,QUEST_MASTERGUNSMITH=79,QUEST_GUNSMITH_02=13,QUEST_KANTOKU=110,QUEST_TAN=111,QUEST_HOSTAGE_R_01=166,QUEST_HOSTAGE_R_02=156,QUEST_HOSTAGE_SR_01=177,QUEST_HOSTAGE_SR_02=179,QUEST_AFRLKAANS=184,RESCUE_SP_HOSTAGE=224,RESCUE_HOSTAGE_E20010_001=219,RESCUE_HOSTAGE_E20010_002=220,RESCUE_HOSTAGE_E20010_003=221,RESCUE_HOSTAGE_E20010_004=222,RESCUE_HOSTAGE_E20050_000=234,RESCUE_HOSTAGE_E20050_001=235,RESCUE_HOSTAGE_E20050_002=236,RESCUE_HOSTAGE_E20050_003=237,RESCUE_HOSTAGE_E20020_000=225,RESCUE_HOSTAGE_E20020_001=226,RESCUE_HOSTAGE_E20030_000=229,RESCUE_HOSTAGE_E20030_001=230,RESCUE_HOSTAGE_E20030_002=231,RESCUE_ENEMY_US_MISSION_TARGET_CENTER000=227,RESCUE_ENEMY_US_MISSION_TARGET_SQUAD000=228,RESCUE_E20030_BETRAYER=232,RESCUE_E20030_MASTERMIND=233,RESCUE_FRIENDMAN=110,RESCUE_GENOME_SOILDER_SAVE=238,S10040_ENEMY_01=59,S10040_ENEMY_02=60,S10040_ENEMY_03=61,STAFF_STAFF2_MSF_01=241,STAFF_STAFF2_MSF_02=242,STAFF_STAFF1_FOX_01=239,STAFF_STAFF1_FOX_02=240,STAFF_STAFF3_DD_01=243,STAFF_STAFF3_DD_02=244,STAFF_STAFF4_FOX_HOUND_01=245,STAFF_STAFF4_FOX_HOUND_02=246}
this.IGNORE_EXIST_STAFF_CHECK={[this.UNIQUE_STAFF_TYPE_ID.SNEAK]=true,[this.UNIQUE_STAFF_TYPE_ID.OCELOT]=true,[this.UNIQUE_STAFF_TYPE_ID.MILLER]=true,[this.UNIQUE_STAFF_TYPE_ID.QUIET]=true,[this.UNIQUE_STAFF_TYPE_ID.HUEY]=true,[this.UNIQUE_STAFF_TYPE_ID.CODETALKER]=true,[this.UNIQUE_STAFF_TYPE_ID.INITIAL_STAFF_01]=true,[this.UNIQUE_STAFF_TYPE_ID.INITIAL_STAFF_02]=true,[this.UNIQUE_STAFF_TYPE_ID.INITIAL_STAFF_03]=true,[this.UNIQUE_STAFF_TYPE_ID.FULTON_LESSON_STAFF_01]=true,[this.UNIQUE_STAFF_TYPE_ID.FULTON_LESSON_STAFF_02]=true,[this.UNIQUE_STAFF_TYPE_ID.FULTON_LESSON_STAFF_03]=true,[this.UNIQUE_STAFF_TYPE_ID.FULTON_LESSON_STAFF_04]=true,[this.UNIQUE_STAFF_TYPE_ID.FULTON_LESSON_STAFF_05]=true,[this.UNIQUE_STAFF_TYPE_ID.FULTON_LESSON_STAFF_06]=true,[this.UNIQUE_STAFF_TYPE_ID.FULTON_LESSON_STAFF_07]=true,[this.UNIQUE_STAFF_TYPE_ID.FULTON_LESSON_STAFF_08]=true,[this.UNIQUE_STAFF_TYPE_ID.FULTON_LESSON_STAFF_09]=true,[this.UNIQUE_STAFF_TYPE_ID.FULTON_LESSON_STAFF_10]=true,[this.UNIQUE_STAFF_TYPE_ID.FULTON_LESSON_STAFF_11]=true,[this.UNIQUE_STAFF_TYPE_ID.FULTON_LESSON_STAFF_12]=true,[this.UNIQUE_STAFF_TYPE_ID.FULTON_LESSON_STAFF_13]=true,[this.UNIQUE_STAFF_TYPE_ID.FULTON_LESSON_STAFF_14]=true,[this.UNIQUE_STAFF_TYPE_ID.S10040_DEAF_HOSTAGE]=true}
this.CYPR_PLAYER_INITIAL_WEAPON_TABLE={{secondary="EQP_None"},{primaryHip="EQP_None"},{primaryBack="EQP_None"},{support="EQP_None"},{support="EQP_None"},{support="EQP_None"},{support="EQP_None"},{support="EQP_None"},{support="EQP_None"},{support="EQP_None"},{support="EQP_None"}}
this.CYPR_PLAYER_INITIAL_ITEM_TABLE={"EQP_None","EQP_None","EQP_None","EQP_None","EQP_None","EQP_None","EQP_None"}
this.RANKING_MAX=21
this.RANKING_ENUM=Tpp.Enum{"TotalTacticalTakeDownCount","XPersonMarkingTime","FirstHeadShotTime","FirstHeadShotTimeTranq","FirstCommandPostAnnihilateTime","CboxGlidingDistance","MechaNeutralizeCount","LongestBirdShotDistance","XPersonPerfectStealthCQCNeutralizeTime","XRocketArmNeutralizeTime","FobSneakingGoalCount","FobDefenceSucceedCount","NuclearDisposeCount","mtbs_q42010","mtbs_q42020","mtbs_q42030","mtbs_q42040","mtbs_q42050","mtbs_q42060","mtbs_q42070"}
this.DEFAULT_DROP_ROUTE={}
this.DIRECTION_ZOOM_IN_CAMERA_ZOOM_INTERP_TIME=1
this.DIRECTION_ZOOM_IN_CAMERA_ROTATION_INTERP_TIME=1
this.ENEMY_HELI_COLORING_TYPE={DEFAULT=0,BLACK=1,RED=2}
this.DEFENSE_GAME_TYPE={ENEMY_BASE=Mission.DEFENSE_TYPE_ENEMY_BASE,BASE=Mission.DEFENSE_TYPE_BASE,SPOT=Mission.DEFENSE_TYPE_SPOT}
this.DEFENSE_FINISH_TYPE={WAVE=Mission.FINISH_TYPE_WAVE,TIMER=Mission.FINISH_TYPE_TIMER,KILL_COUNT=Mission.FINISH_TYPE_KILL_COUNT}
this.DIGGER_SHOCK_WAVE_TYPE={FINISH_WAVE=Mission.SHOCKWAVE_TYPE_FINISH_WAVE,LIFE_BREAK_POINT=Mission.SHOCKWAVE_TYPE_LIFE_BREAK_POINT}
this.WORMHOLE_DROP_TYPE={ENERGY=Mission.WORMHOLE_DROP_TYPE_ENERGY,RESOURCE=Mission.WORMHOLE_DROP_TYPE_RESOURCE,CBOX=Mission.WORMHOLE_DROP_TYPE_CBOX,NPC=Mission.WORMHOLE_DROP_TYPE_NPC,TASK_RESOURCE=Mission.WORMHOLE_DROP_TYPE_TASK_RESOURCE,TASK_NPC=Mission.WORMHOLE_DROP_TYPE_TASK_NPC}
this.COOP_TASK_REWARD_TYPE={IRI=Mission.COOP_TASK_REWARD_TYPE_IRI,KUB=Mission.COOP_TASK_REWARD_TYPE_KUB,WALKERGEAR=Mission.COOP_TASK_REWARD_TYPE_WALKERGEAR,AMMO_BOX=Mission.COOP_TASK_REWARD_TYPE_AMMO_BOX,BUILDING=Mission.COOP_TASK_REWARD_TYPE_BUILDING,RECOVER_DIGGER_LIFE=Mission.COOP_TASK_REWARD_TYPE_RECOVER_DIGGER_LIFE}
this.COOP_CLEAR_TYPE={CLEAR=0,FAILURE=1,ABORT=2}
this.DEFAULT_DIGGER_SHOCK_WAVE_SETTINGS={breakPoints={.875,.75,.625,.5,.375,.25,.125},radius=15}
this.ZOMBIE_TYPE_LIST={"SsdZombie","SsdZombieBom","SsdZombieDash","SsdZombieShell","SsdZombieArmor","SsdZombiePack","SsdZombieEvent"}
this.CREATURE_TYPE_LIST={"SsdInsect1","SsdInsect2","SsdInsect3"}
this.BOSS_TYPE_LIST={"SsdBoss1","SsdBoss2","SsdBoss3"}
this.ENEMY_TYPE_LIST={}
for A,E in ipairs{this.ZOMBIE_TYPE_LIST,this.CREATURE_TYPE_LIST,this.BOSS_TYPE_LIST}do
  for A,E in ipairs(E)do
    table.insert(this.ENEMY_TYPE_LIST,E)
  end
end
this.WAVE_ENEMY_TYPE_LIST={}
for A,E in ipairs(this.ZOMBIE_TYPE_LIST)do
  table.insert(this.WAVE_ENEMY_TYPE_LIST,E)
end
table.insert(this.WAVE_ENEMY_TYPE_LIST,"SsdInsect1")
if CrewType then
  this.CREW_TYPE={
    UNIQUE_MLT=CrewType.UNIQUE_MLT,
    UNIQUE_BOY=CrewType.UNIQUE_BOY,
    UNIQUE_NRS=CrewType.UNIQUE_NRS,
    UNIQUE_PLC=CrewType.UNIQUE_PLC,
    UNIQUE_ENG=CrewType.UNIQUE_ENG,
    UNIQUE_SETH=CrewType.UNIQUE_SETH,
    MOB_MALE=CrewType.MOB_MALE,
    MOB_FEMALE=CrewType.MOB_FEMALE
  }
else
  this.CREW_TYPE={}
end
if CrewBlockController then
  this.RESCUE_CREW_MISSION_TYPE={
    FLAG_MISSION=CrewBlockController.MISSION_TYPE_FLAG_MISSION,
    QUEST_1=CrewBlockController.MISSION_TYPE_QUEST_1,
    QUEST_2=CrewBlockController.MISSION_TYPE_QUEST_2,
    QUEST_3=CrewBlockController.MISSION_TYPE_QUEST_3
  }
else
  this.RESCUE_CREW_MISSION_TYPE={}
end
this.ENEMY_REGION_DEFINE={
  afgh={"afgh_dungeon1","afgh_dungeon2","afgh_field","afgh_field_crystal","afgh_village","afgh_village_crystal","afgh_area1_01","afgh_area1_02","afgh_area2_01","afgh_area2_02","afgh_base_spot"},
  mafr={"mafr_factory","mafr_area1_00","mafr_area1_01","mafr_area1_02","mafr_area1_03","mafr_lab","mafr_dungeon01","mafr_diamond","mafr_diamond_crystal"}
}
this.TREASUREPOINT_CRAFT={
  PRD_EQP_SWP_PetrolBomb={"PRD_EXP_Bottle","RES_Rag","RES_Oil"},
  PRD_EQP_SWP_PetrolBomb_3={"PRD_EXP_Bottle","PRD_EXP_Bottle","PRD_EXP_Bottle","COL_RagSet3","COL_OilSet3"},
  PRD_DEF_Fence_C={"RES_Iron","COL_IronSet5"},PRD_DEF_Fence_C_3={"COL_IronSet3","COL_IronSet5","COL_IronSet10"},
  PRD_BL_Hg9x19mm_3={"COL_GunPowderSet3","COL_CopperSet3","COL_LeadSet3"},
  PRD_BL_ARW_Iron_5={"COL_AluminiumSet3","COL_SteelSet3"},
  PRD_BL_ARW_Flame_5={"COL_RagSet3","COL_IronSet3","COL_WoodSet5","COL_OilSet3"},
  PRD_EQP_SWP_DMine={"COL_IronSet5","RES_Wire","RES_Wire","COL_Powder_TNTSet3"},
  PRD_EQP_SWP_DMine_2={"COL_IronSet10","RES_Wire","COL_WireSet3","RES_Powder_TNT","COL_Powder_TNTSet5"},
  PRD_DEF_Barricade_B_3={"RES_Wood","RES_Wood","COL_WoodSet10","RES_Nail","RES_Nail","COL_NailSet10","RES_Wire","COL_WireSet5"},
  PRD_BL_ARW_Normal_5={"COL_WoodSet3","COL_IronSet5"},
  PRD_BL_12GA00Back_2={"RES_GunPowder","RES_GunPowder","RES_Copper","COL_CopperSet5","RES_Lead","COL_LeadSet5"},
  PRD_EQP_SWP_MolotovCocktail_3={"PRD_EXP_Bottle","PRD_EXP_Bottle","PRD_EXP_Bottle","COL_RagSet3","COL_Oil_NapalmSet3"},
  PRD_DEF_Barricade_C_2={"RES_Iron","RES_Iron","COL_IronSet10","RES_Nail","COL_NailSet5","COL_NailSet10","COL_CementSet3","COL_CementSet5"},
  PRD_EQP_SWP_Decoy_3={"RES_Rubber","RES_Rubber","RES_Rubber","COL_AluminiumSet3"},
  PRD_DEF_Fence_B_2={"RES_Wood","RES_Wood","COL_WoodSet10","COL_NailSet3","COL_NailSet5","RES_Wire","COL_WireSet5"},
  PRD_DEF_Barricade_E_2={"RES_Wood","RES_Wood","RES_Wood","COL_WoodSet5","COL_WoodSet10","COL_RopeSet3","COL_RopeSet5"},
  PRD_EQP_SWP_Grenade_2={"COL_IronSet10","RES_Spring","RES_Spring","RES_Powder_TNT","COL_Powder_TNTSet5"},
  PRD_DEF_AutoTurret_A={"RES_GunPowder","RES_GunPowder","COL_GunPowderSet10","COL_SteelSet5","COL_SteelSet5","RES_Gear","COL_GearSet5","RES_ElectronicCircuit","RES_Device_Sensor","RES_Device_Firing"},
  PRD_DEF_AutoTurret_B={"COL_SteelSet5","COL_SteelSet5","RES_ElectronicCircuit","RES_Gear","COL_GearSet5","RES_Device_Sensor","RES_Device_Firing","COL_Powder_CompositionSet3","COL_Powder_CompositionSet5"},
  PRD_DEF_Floor_C={"COL_SteelSet5","RES_Device_Sensor","RES_Liquid_Nitrogen","COL_Liquid_NitrogenSet5"},
  PRD_EQP_SWP_C4={"COL_AdhesiveSet5","RES_ElectronicCircuit","COL_Powder_CompositionSet3"},
  PRD_EQP_SWP_ShockDecoy_2={"RES_Aluminium","RES_Aluminium","RES_ElectronicCircuit","RES_ElectronicCircuit","RES_Battery_High","RES_Battery_High","RES_SiliconRubber","COL_SiliconRubberSet3"},
  PRD_DEF_Fence_E_2={"RES_Iron","RES_Iron","COL_IronSet10","RES_Wire","COL_WireSet5","COL_WireSet10","RES_Battery_High","RES_Battery_High"},
  PRD_DEF_Floor_B={"COL_SteelSet5","RES_Device_Sensor","RES_Oil_Napalm","COL_Oil_NapalmSet5"}
}
this.QUEST_RESOURCE_LIST={
  Seq1_1={this.TREASUREPOINT_CRAFT.PRD_EQP_SWP_PetrolBomb_3,this.TREASUREPOINT_CRAFT.PRD_DEF_Fence_C_3},
  Seq1_2={this.TREASUREPOINT_CRAFT.PRD_BL_Hg9x19mm_3,this.TREASUREPOINT_CRAFT.PRD_DEF_Fence_C},
  Seq1_3={this.TREASUREPOINT_CRAFT.PRD_EQP_SWP_PetrolBomb,this.TREASUREPOINT_CRAFT.PRD_BL_Hg9x19mm_3,this.TREASUREPOINT_CRAFT.PRD_DEF_Fence_C},
  Seq2_1={this.TREASUREPOINT_CRAFT.PRD_DEF_Fence_C_3,this.TREASUREPOINT_CRAFT.PRD_BL_Hg9x19mm_3},
  Seq3_1={this.TREASUREPOINT_CRAFT.PRD_EQP_SWP_PetrolBomb_3,this.TREASUREPOINT_CRAFT.PRD_EQP_SWP_DMine_2,this.TREASUREPOINT_CRAFT.PRD_BL_Hg9x19mm_3},
  Seq4_1={this.TREASUREPOINT_CRAFT.PRD_DEF_Barricade_B_3,this.TREASUREPOINT_CRAFT.PRD_BL_ARW_Normal_5},
  Seq5_1={this.TREASUREPOINT_CRAFT.PRD_BL_ARW_Iron_5,this.TREASUREPOINT_CRAFT.PRD_BL_ARW_Flame_5},
  Seq5_2={this.TREASUREPOINT_CRAFT.PRD_EQP_SWP_DMine,this.TREASUREPOINT_CRAFT.PRD_BL_Hg9x19mm_3},
  Seq5_3={this.TREASUREPOINT_CRAFT.PRD_BL_ARW_Iron_5,this.TREASUREPOINT_CRAFT.PRD_EQP_SWP_DMine,this.TREASUREPOINT_CRAFT.PRD_BL_Hg9x19mm_3},
  Seq6_1={this.TREASUREPOINT_CRAFT.PRD_BL_ARW_Iron_5,this.TREASUREPOINT_CRAFT.PRD_BL_12GA00Back_2},
  Seq7_1={this.TREASUREPOINT_CRAFT.PRD_EQP_SWP_Decoy_3,this.TREASUREPOINT_CRAFT.PRD_DEF_Fence_B_2},
  Seq8_1={this.TREASUREPOINT_CRAFT.PRD_EQP_SWP_MolotovCocktail_3,this.TREASUREPOINT_CRAFT.PRD_EQP_SWP_Decoy_3},
  Seq9_1={this.TREASUREPOINT_CRAFT.PRD_EQP_SWP_MolotovCocktail_3,this.TREASUREPOINT_CRAFT.PRD_DEF_Barricade_C_2},
  Seq10_1={this.TREASUREPOINT_CRAFT.PRD_DEF_Barricade_C_2,this.TREASUREPOINT_CRAFT.PRD_EQP_SWP_Grenade_2},
  Seq11_1={this.TREASUREPOINT_CRAFT.PRD_DEF_Barricade_E_2,this.TREASUREPOINT_CRAFT.PRD_EQP_SWP_Grenade_2},
  Seq12_1={this.TREASUREPOINT_CRAFT.PRD_DEF_Barricade_E_2,this.TREASUREPOINT_CRAFT.PRD_DEF_Barricade_C_2},
  Seq13_1={this.TREASUREPOINT_CRAFT.PRD_DEF_AutoTurret_A},
  Seq13_2={this.TREASUREPOINT_CRAFT.PRD_DEF_AutoTurret_B},
  Seq13_3={this.TREASUREPOINT_CRAFT.PRD_DEF_Floor_C},
  Seq13_4={this.TREASUREPOINT_CRAFT.PRD_EQP_SWP_C4,this.TREASUREPOINT_CRAFT.PRD_EQP_SWP_ShockDecoy_2},
  Seq13_5={this.TREASUREPOINT_CRAFT.PRD_DEF_Fence_E_2,this.TREASUREPOINT_CRAFT.PRD_DEF_Floor_B}
}
this.PARAMETER_FILE_PATH={
  {name="DefenseGameBaseDigging",path="/Assets/ssd/level_asset/server/parameter/DefenseGameBaseDigging.param"},
  {name="DefenseGameEmbeddedMission",path="/Assets/ssd/level_asset/server/parameter/DefenseGameEmbeddedMission.param"},
  {name="DefenseGameEventMission",path="/Assets/ssd/level_asset/server/parameter/DefenseGameEventMission.param"},
  {name="DefenseGameQuest",path="/Assets/ssd/level_asset/server/parameter/DefenseGameQuest.param"},
  {name="SsdBaseDefenseSettings",path="/Assets/ssd/level_asset/server/parameter/SsdBaseDefenseSettings.param"},
  {name="SsdBuffParameter_opt",path="/Assets/ssd/level_asset/server/parameter/SsdBuffParameter_opt.param"},
  {name="SsdBuildingParameterTable",path="/Assets/ssd/level_asset/server/parameter/SsdBuildingParameterTable.param"},
  {name="SsdCollectionItems",path="/Assets/ssd/level_asset/server/parameter/SsdCollectionItems.param"},
  {name="SsdCombatDeployParameterTable",path="/Assets/ssd/level_asset/server/parameter/SsdCombatDeployParameterTable.param"},
  {name="SsdCrewGeneratorTable",path="/Assets/ssd/level_asset/server/parameter/SsdCrewGeneratorTable.param"},
  {name="SsdDamageParameter_opt",path="/Assets/ssd/level_asset/server/parameter/SsdDamageParameter_opt.param"},
  {name="SsdDlcMissionSettings",path="/Assets/ssd/level_asset/server/parameter/SsdDlcMissionSettings.param"},
  {name="SsdEquipParameters_opt",path="/Assets/ssd/level_asset/server/parameter/SsdEquipParameters_opt.param"},
  {name="SsdNpcLevelParameters",path="/Assets/ssd/level_asset/server/parameter/SsdNpcLevelParameters.param"},
  {name="SsdPlayerParameters",path="/Assets/ssd/level_asset/server/parameter/SsdPlayerParameters.param"},
  {name="SsdSbmParameters_opt",path="/Assets/ssd/level_asset/server/parameter/SsdSbmParameters_opt.param"},
  {name="SsdUiCoopMissionInfo",path="/Assets/ssd/level_asset/server/parameter/SsdUiCoopMissionInfo.param"},
  {name="SsdWalkerGearParameters",path="/Assets/ssd/level_asset/server/parameter/SsdWalkerGearParameters.param"},
  {name="SsdWeaponParameters_opt",path="/Assets/ssd/level_asset/server/parameter/SsdWeaponParameters_opt.param"}
}
return this
