


local  afgh_wormhole = {}


local RANDOM_COUNT = 3


local AREA_A_PROBABILITY = 0.8
local AREA_B_PROBABILITY = 0.8
local AREA_C_PROBABILITY = 0.8
local AREA_D_PROBABILITY = 0.8


afgh_wormhole.wormholeResourceList = {
	
	areaA = {
		"COL_WoodStick_Nail",
		"COL_DrumFragment_4",
		"COL_Sandbag_WH",
		"COL_Cluster_Fabric_WH",
		"COL_Carton_E",
		"COL_Carton_A",
		"COL_Bottle_C_WH",
	},
	
	areaB = {
		"COL_WoodStick_Nail",
		"COL_DrumFragment_4",
		"COL_Carton_G",
		"COL_Sandbag_WH",
		"COL_Cluster_Fabric_WH",
		"COL_Carton_E",
		"COL_Carton_A",
		"COL_GunPowderPack_WH",
		"COL_Tire_B_WH",
		"COL_Bottle_C_WH",
		"COL_Oil",
		"COL_Tableware_G_WH",
		"COL_Ashtray_WH",
		"COL_Bucket_C_WH",
		"COL_MedicalEquip_D_WH",
	},
	
	areaC = {
		"COL_WoodStick_Nail",
		"COL_DrumFragment_4",
		"COL_Carton_G",
		"COL_Sandbag_WH",
		"COL_Cluster_Fabric_WH",
		"COL_Carton_E",
		"COL_Carton_A",
		"COL_GunPowderPack_WH",
		"COL_Tire_B_WH",
		"COL_Bottle_C_WH",
		"COL_Oil",
		"COL_Tableware_G_WH",
		"COL_Ashtray_WH",
		"COL_Bucket_C_WH",
		"COL_Cluster_Steel_WH",
		"COL_MedicalEquip_D_WH",
		"COL_Tube_TNT_WH",
	},
	
	areaD = {
		"COL_WoodStick_Nail",
		"COL_DrumFragment_4",
		"COL_Carton_G",
		"COL_Sandbag_WH",
		"COL_Cluster_Fabric_WH",
		"COL_Carton_E",
		"COL_Carton_A",
		"COL_GunPowderPack_WH",
		"COL_MedicalEquip_A_WH",
		"COL_Solvent",
		"COL_Tire_B_WH",
		"COL_Bottle_C_WH",
		"COL_Oil",
		"COL_Carton_F",
		"COL_Tableware_G_WH",
		"COL_Ashtray_WH",
		"COL_Carton_B",
		"COL_Bucket_C_WH",
		"COL_Broken_D_WH",
		"COL_Cluster_Steel_WH",
		"COL_MedicalEquip_D_WH",
		"COL_Bag_B_WH",
		"COL_Tube_TNT_WH",
	},
}




afgh_wormhole.wormholePointTable = {

	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/128/128_146/afgh_128_146_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaA,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_A_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/129/129_145/afgh_129_145_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaA,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_A_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/129/129_146/afgh_129_146_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaA,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_A_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/129/129_147/afgh_129_147_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaA,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_A_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/130/130_145/afgh_130_145_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaA,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_A_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/130/130_146/afgh_130_146_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaA,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_A_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0001|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/130/130_146/afgh_130_146_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaA,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_A_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/130/130_147/afgh_130_147_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaA,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_A_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0001|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/130/130_147/afgh_130_147_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaA,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_A_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/131/131_145/afgh_131_145_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaA,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_A_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/131/131_146/afgh_131_146_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaA,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_A_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/131/131_147/afgh_131_147_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaA,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_A_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/131/131_148/afgh_131_148_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaA,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_A_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/132/132_149/afgh_132_149_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaA,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_A_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/132/132_150/afgh_132_150_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaA,
		reset			= false,
		radius			= 25,
		halfSize		= 0,
		probability		= AREA_A_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0001|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/132/132_150/afgh_132_150_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaA,
		reset			= false,
		radius			= 25,
		halfSize		= 0,
		probability		= AREA_A_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0002|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/132/132_150/afgh_132_150_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaA,
		reset			= false,
		radius			= 25,
		halfSize		= 0,
		probability		= AREA_A_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},

	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/132/132_147/afgh_132_147_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaB,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_B_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/132/132_148/afgh_132_148_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaB,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_B_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0001|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/132/132_148/afgh_132_148_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaB,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_B_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0002|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/132/132_148/afgh_132_148_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaB,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_B_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/133/133_149/afgh_133_149_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaB,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_B_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/133/133_150/afgh_133_150_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaB,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_B_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/134/134_148/afgh_134_148_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaB,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_B_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/134/134_149/afgh_134_149_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaB,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_B_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0001|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/134/134_149/afgh_134_149_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaB,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_B_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/134/134_151/afgh_134_151_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaB,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_B_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},

	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/135/135_148/afgh_135_148_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/135/135_149/afgh_135_149_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/135/135_150/afgh_135_150_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0001|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/135/135_150/afgh_135_150_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/135/135_151/afgh_135_151_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0001|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/135/135_151/afgh_135_151_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/136/136_148/afgh_136_148_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0001|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/136/136_148/afgh_136_148_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/136/136_149/afgh_136_149_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/136/136_150/afgh_136_150_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0001|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/136/136_150/afgh_136_150_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/137/137_143/afgh_137_143_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0001|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/137/137_143/afgh_137_143_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0002|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/137/137_143/afgh_137_143_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/137/137_144/afgh_137_144_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0001|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/137/137_144/afgh_137_144_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/137/137_146/afgh_137_146_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0001|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/137/137_146/afgh_137_146_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/137/137_147/afgh_137_147_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/138/138_143/afgh_138_143_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0001|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/138/138_143/afgh_138_143_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0002|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/138/138_143/afgh_138_143_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/138/138_144/afgh_138_144_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0001|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/138/138_144/afgh_138_144_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/138/138_146/afgh_138_146_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/138/138_147/afgh_138_147_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/139/139_143/afgh_139_143_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/139/139_144/afgh_139_144_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/139/139_145/afgh_139_145_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0001|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/139/139_145/afgh_139_145_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/139/139_146/afgh_139_146_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/139/139_148/afgh_139_148_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/140/140_141/afgh_140_141_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0001|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/140/140_141/afgh_140_141_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/140/140_142/afgh_140_142_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0001|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/140/140_142/afgh_140_142_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/140/140_143/afgh_140_143_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/140/140_144/afgh_140_144_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/141/141_141/afgh_141_141_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0001|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/141/141_141/afgh_141_141_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/141/141_142/afgh_141_142_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0001|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/141/141_142/afgh_141_142_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0002|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/141/141_142/afgh_141_142_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/141/141_143/afgh_141_143_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0001|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/141/141_143/afgh_141_143_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/141/141_144/afgh_141_144_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0001|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/141/141_144/afgh_141_144_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/142/142_143/afgh_142_143_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaC,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_C_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},

	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/134/134_140/afgh_134_140_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaD,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_D_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/135/135_140/afgh_135_140_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaD,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_D_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/135/135_142/afgh_135_142_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaD,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_D_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/136/136_141/afgh_136_141_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaD,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_D_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0001|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/136/136_141/afgh_136_141_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaD,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_D_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/136/136_142/afgh_136_142_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaD,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_D_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0001|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/136/136_142/afgh_136_142_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaD,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_D_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0002|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/136/136_142/afgh_136_142_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaD,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_D_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/137/137_141/afgh_137_141_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaD,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_D_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0001|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/137/137_141/afgh_137_141_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaD,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_D_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0002|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/137/137_141/afgh_137_141_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaD,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_D_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/137/137_142/afgh_137_142_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaD,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_D_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0001|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/137/137_142/afgh_137_142_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaD,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_D_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0002|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/137/137_142/afgh_137_142_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaD,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_D_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/138/138_141/afgh_138_141_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaD,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_D_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0001|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/138/138_141/afgh_138_141_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaD,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_D_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0002|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/138/138_141/afgh_138_141_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaD,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_D_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/138/138_142/afgh_138_142_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaD,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_D_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0001|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/138/138_142/afgh_138_142_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaD,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_D_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/139/139_140/afgh_139_140_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaD,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_D_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/139/139_141/afgh_139_141_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaD,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_D_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0001|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/139/139_141/afgh_139_141_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaD,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_D_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	
	{
		name			= "com_wormhole_null001_gim_n0000|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/139/139_142/afgh_139_142_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaD,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_D_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
	{
		name			= "com_wormhole_null001_gim_n0001|srt_gim_null_wormhole",
		dataSetName		= "/Assets/ssd/level/location/afgh/block_small/139/139_142/afgh_139_142_gimmick.fox2",
		resources = afgh_wormhole.wormholeResourceList.areaD,
		reset			= false,
		radius			= 45,
		halfSize		= 0,
		probability		= AREA_D_PROBABILITY,
		randomCount		= RANDOM_COUNT,
		randomOffset	= 5,
	},
}

return afgh_wormhole