if SubtitlesCommand then
	
	SubtitlesCommand:SetDefaultSubPriority( 0, 255, 255 )	
	SubtitlesCommand:SetDefaultSubPriority( 1, 0, 0 )		
	SubtitlesCommand:SetDefaultSubPriority( 2, 0, 0 )		
	SubtitlesCommand:SetDefaultSubPriority( 6, 15, 50 )		
	SubtitlesCommand:SetDefaultSubPriority( 9, 15, 50 )		
	SubtitlesCommand:SetDefaultSubPriority( 10, 0, 0 )		
	SubtitlesCommand:SetDefaultSubPriority( 11, 75, 90 )	
	SubtitlesCommand:SetDefaultSubPriority( 12, 65, 70 )	
	SubtitlesCommand:SetDefaultSubPriority( 13, 15, 11 )	
	SubtitlesCommand:SetDefaultSubPriority( 14, 12, 20 )	
	SubtitlesCommand:SetDefaultSubPriority( 16, 0, 0 )		
	SubtitlesCommand:SetDefaultSubPriority( 18, 5, 10 )		
	SubtitlesCommand:SetDefaultSubPriority( 19, 12, 20 )	
	SubtitlesCommand:SetDefaultSubPriority( 20, 65, 70 )	
	SubtitlesCommand:SetDefaultSubPriority( 21, 15, 50 )	
	SubtitlesCommand:SetDefaultSubPriority( 22, 0, 0 )		
	SubtitlesCommand:SetDefaultSubPriority( 23, 1, 0 )		
	SubtitlesCommand:SetDefaultSubPriority( 24, 85, 90 )	
	SubtitlesCommand:SetDefaultSubPriority( 25, 15, 50 )	
	SubtitlesCommand:SetDefaultSubPriority( 26, 75, 80 )		
	SubtitlesCommand:SetDefaultSubPriority( 27, 55, 60 )		
	SubtitlesCommand:SetDefaultSubPriority( 28, 75, 90 )		

	SubtitlesCommand:SetDefaultSubPriority( 61, 255, 255 )	
	SubtitlesCommand:SetDefaultSubPriority( 62, 0, 0 )		
	SubtitlesCommand:SetDefaultSubPriority( 63, 0, 0 )		
end