local mafr_baseTelop = {}

mafr_baseTelop.cpLangIdTable = {
	{ "mafr_swamp_cp", "tpp_africa_swamp", "tpp_africa_en_swamp", },
	{ "mafr_savannah_cp", "tpp_africa_savannah", "tpp_africa_en_savannah", },
	{ "mafr_banana_cp", "tpp_africa_banana", "tpp_africa_en_banana", },
	{ "mafr_diamond_cp", "tpp_africa_diamond", "tpp_africa_en_diamond", },
	{ "mafr_factory_cp", "tpp_africa_factory", "tpp_africa_en_factory", },
	{ "mafr_lab_cp", "tpp_africa_lab", "tpp_africa_en_lab", },
	{ "mafr_flowStation_cp", "tpp_africa_flowstation", "tpp_africa_en_flowstation", },
	{ "mafr_outland_cp", "tpp_africa_outland", "tpp_africa_en_outland", },
	{ "mafr_hill_cp", "tpp_africa_hill", "tpp_africa_en_hill", },
	{ "mafr_pfCamp_cp", "tpp_africa_pfcamp", "tpp_africa_en_pfcamp", },
	{ "mafr_outlandNorth_ob", "tpp_africa_outlandNorth", "tpp_africa_en_outlandNorth", },
	{ "mafr_swampWest_ob", "tpp_africa_swampWest", "tpp_africa_en_swampWest", },
	{ "mafr_outlandEast_ob", "tpp_africa_outlandEast", "tpp_africa_en_outlandEast", },
	{ "mafr_bananaSouth_ob", "tpp_africa_bananaSouth", "tpp_africa_en_bananaSouth", },
	{ "mafr_swampSouth_ob", "tpp_africa_swampSouth", "tpp_africa_en_swampSouth", },
	{ "mafr_swampEast_ob", "tpp_africa_swampEast", "tpp_africa_en_swampEast", },
	{ "mafr_savannahWest_ob", "tpp_africa_savannahWest", "tpp_africa_en_savannahWest", },
	{ "mafr_bananaEast_ob", "tpp_africa_bananaEast", "tpp_africa_en_bananaEast", },
	{ "mafr_diamondWest_ob", "tpp_africa_diamondWest", "tpp_africa_en_diamondWest", },
	{ "mafr_diamondSouth_ob", "tpp_africa_diamondSouth", "tpp_africa_en_diamondSouth", },
	{ "mafr_hillNorth_ob", "tpp_africa_hillNorth", "tpp_africa_en_hillNorth", },
	{ "mafr_hillSouth_ob", "tpp_africa_hillSouth", "tpp_africa_en_hillSouth", },
	{ "mafr_savannahEast_ob", "tpp_africa_savannahEast", "tpp_africa_en_savannahEast", },
	{ "mafr_hillWest_ob", "tpp_africa_hillWest", "tpp_africa_en_hillWest", },
	{ "mafr_hillWestNear_ob", "tpp_africa_hillWestNear", "tpp_africa_en_hillWestNear", },
	{ "mafr_pfCampEast_ob", "tpp_africa_pfCampEast", "tpp_africa_en_pfCampEast", },
	{ "mafr_pfCampNorth_ob", "tpp_africa_pfCampNorth", "tpp_africa_en_pfCampNorth", },
	{ "mafr_factorySouth_ob", "tpp_africa_factorySouth", "tpp_africa_en_factorySouth", },
	{ "mafr_diamondNorth_ob", "tpp_africa_diamondNorth", "tpp_africa_en_diamondNorth", },
	{ "mafr_labWest_ob", "tpp_africa_labWest", "tpp_africa_en_labWest", },
	{ "mafr_chicoVilWest_ob", "tpp_africa_chicoVilWest", "tpp_africa_en_chicoVilWest", },
}

return mafr_baseTelop