function GetClassEditEntry(_)
local e=_+1 ..""local a=_..""local t="id_customize_class_record000"..(_..".UI_ID_Customize_Class_record")
local s={".UI_ID_C_Class_REC",".UI_ID_C_Class_TEC",".UI_ID_C_Class_INF"}
local o={"mgo_UI_ID_Status_REC_Name","mgo_UI_ID_Status_TEC_Name","mgo_UI_ID_Status_INF_Name"}
local l={"mgo_UI_ID_C_RecHelp","mgo_UI_ID_C_TecHelp","mgo_UI_ID_C_InfHelp"}
local t={type="MgoUiMenuEntry",name="menu_entry_class_edit_"..e,states={{type="MgoUiAnimationStateSwitch",name="stateInit",mode="enter",control="play",layout=t..s[_+1]},{type="MgoUiAnimationStateSwitch",name="stateInit",mode="enter",control="play",layout=t..".UI_ID_C_Class_FocusOut"},{type="MgoUiAnimationStateSwitch",name="stateHot",mode="enter",control="play",layout=t..".UI_ID_C_Class_Focus"},{type="MgoUiAnimationStateSwitch",name="stateHot",mode="enter",control="stop",layout=t..".UI_ID_C_Class_FocusOut"},{type="MgoUiAnimationStateSwitch",name="stateHot",mode="exit",control="play",layout=t..".UI_ID_C_Class_FocusOut"},{type="MgoUiAnimationStateSwitch",name="stateHot",mode="exit",control="stop",layout=t..".UI_ID_C_Class_Focus"}},widgets={{type="MgoUiLabel",name="label_class_edit_"..e,index=a,layout=t..".UI_ID_C_ClassName_txt",shadow=t..".UI_ID_C_ClassName_sdw_txt",langTag=o[_+1]},{type="MgoUiLabel",name="label_class_edit_"..(e.."_desc"),index=a,layout=t..".UI_ID_C_ClassDesc_txt",shadow=t..".UI_ID_C_ClassDesc_sdw_txt",textUnitCount=3,langTag=l[_+1]}}}
return t
end
CharacterModClassEdit={widgets={{type="MgoUiMenu",name="menu_class_edit",states={{type="MgoUiAnimationStateSwitch",name="stateHot",mode="exit",control="play",layout="UI_ID_Customize_PT1_layout.UI_ID_C_PT1_Class_Hide"},{type="MgoUiAnimationStateSwitch",name="stateHot",mode="exit",control="stop",layout="UI_ID_Customize_PT1_layout.UI_ID_C_PT1_Class_Show"},{type="MgoUiAnimationStateSwitch",name="stateHot",mode="enter",control="play",layout="UI_ID_Customize_PT1_layout.UI_ID_C_PT1_Class_Show"},{type="MgoUiAnimationStateSwitch",name="stateHot",mode="enter",control="stop",layout="UI_ID_Customize_PT1_layout.UI_ID_C_PT1_Class_Hide"},{type="MgoUiAnimationStateSwitch",name="stateInit",mode="enter",control="play",layout="UI_ID_Customize_PT1_layout.UI_ID_C_PT1_Chr_Bracket_Off"}},widgets={GetClassEditEntry(0),GetClassEditEntry(1),GetClassEditEntry(2)}}}}
