function GetAvailableItemWidget(_)
local e="".._
local t=""..(_+1)
local _=string.format("%0.4d",_+1)
local _="id_customize_pallet_record"..(_..".UI_ID_C_Pallet_record.")
local _={type="MgoUiMenuEntry",name="menu_entry_color_pallet_"..t,states={{type="MgoUiAnimationStateSwitch",name="stateHot",mode="enter",control="play",layout=_.."UI_ID_C_Pallet_Focus"},{type="MgoUiAnimationStateSwitch",name="stateIdle",mode="enter",control="play",layout=_.."UI_ID_C_Pallet_FocusOut"},{type="MgoUiAnimationStateSwitch",name="stateHot",mode="enter",control="play",loop="true",layout=_.."UI_ID_C_Pallet_Cursor_Noise"}},widgets={{type="MgoUiImage",name="image_color_pallet_"..t,source="mgo_idroid_color_edit_list_texture",index=e,layout=_.."UI_ID_C_PalletIcon",default="Icon"},{type="MgoUiAnimation",name="anim_color_pallet_"..(t.."_enable"),source="mgo_idroid_color_edit_list_anim_enable",index=e,layout="",options={{key="_on_",layout=_.."UI_ID_C_Pallet_Full"},{key="_off_",layout=_.."UI_ID_C_Pallet_Off"}}},{type="MgoUiAnimation",name="anim_color_pallet_"..(t.."_ctrl"),source="mgo_idroid_color_edit_list_anim_ctrl",index=e,layout="",options={{key="_on_",layout=_.."UI_ID_C_Pallet_On"},{key="_off_",layout=_.."UI_ID_C_Pallet_Off"}}},{type="MgoUiAnimation",name="anim_color_pallet_"..(t.."_eqp"),source="mgo_idroid_color_edit_list_anim_eqp",index=e,layout="",options={{key="_on_",layout=_.."UI_ID_C_Pallet_EQ_On"},{key="_off_",layout=_.."UI_ID_C_Pallet_EQ_Off"}}},{type="MgoUiAnimation",name="anim_color_pallet_"..(t.."_edg"),source="mgo_idroid_color_edit_list_anim_edg",index=e,layout="",options={{key="_on_",layout=_.."UI_ID_C_Pallet_Edge_On"},{key="_off_",layout=_.."UI_ID_C_Pallet_Edge_Off"}}},{type="MgoUiAnimation",name="anim_color_pallet_"..(t.."_new"),source="mgo_idroid_color_edit_list_anim_new",index=e,layout="",options={{key="_on_",layout=_.."UI_ID_C_Pallet_New_On"},{key="_off_",layout=_.."UI_ID_C_Pallet_New_Off"}}},{type="MgoUiAnimation",name="anim_color_pallet_"..(t.."_attr"),source="mgo_idroid_color_edit_list_anim_attr",index=e,layout="",options={{key="_dollar_",layout=_.."UI_ID_C_Pallet_Dollar"},{key="_locked_",layout=_.."UI_ID_C_Pallet_Locked"},{key="_locked_gp_",layout=_.."UI_ID_C_Pallet_GP"},{key="_locked_pre_",layout=_.."UI_ID_C_Pallet_PRE"},{key="_locked_mb_",layout=_.."UI_ID_C_Pallet_MB"},{key="_none_",layout=_.."UI_ID_C_Pallet_None"},{key="_off_",layout=_.."UI_ID_C_Pallet_Pallet"}}}}}
return _
end
function GetAvailableItemWidgets()ret={}
for _=0,39,1 do
table.insert(ret,GetAvailableItemWidget(_))
end
return ret
end
CharacterModColorPallet={widgets={{type="MgoUiLabel",name="label_color_help",source="mgo_idroid_color_edit_help",layout="UI_ID_Customize_Common_layout.UI_ID_C_Pallet_txt",shadow="UI_ID_Customize_Common_layout.UI_ID_C_Pallet_txt_sdw",default="[0]",textUnitCount=12},{type="MgoUiMenu",name="menu_color_pallet",states={{type="MgoUiAnimationStateSwitch",name="stateInit",mode="enter",control="play",layout="UI_ID_Customize_Common_layout.UI_ID_CC_Pallet_Off"},{type="MgoUiAnimationStateSwitch",name="stateShow",mode="enter",control="play",layout="UI_ID_Customize_Common_layout.UI_ID_CC_Pallet_On"},{type="MgoUiAnimationStateSwitch",name="stateHide",mode="enter",control="play",layout="UI_ID_Customize_Common_layout.UI_ID_CC_Pallet_Off"},{type="MgoUiAnimationStateSwitch",name="stateHot",mode="enter",control="play",layout="UI_ID_Customize_Common_layout.UI_ID_C_Pallet_Setin"},{type="MgoUiAnimationStateSwitch",name="stateIdle",mode="enter",control="play",layout="UI_ID_Customize_Common_layout.UI_ID_C_Pallet_Setout"}},widgets=GetAvailableItemWidgets()}}}
