--DDS8_MAIN0_MIX.lua bodyInfo
--relies on a fovaInfo addon
local this={
 --tex TODO fova not applying unlike males, dds5 fovas dont apply to dds6 either.
    description="Fatigues - All",
    gender="FEMALE",
    bodyIds={
      TppEnemyBodyId.dds6_main0_ply_v00,
      TppEnemyBodyId.dds6_main0_ply_v01,
      TppEnemyBodyId.dds6_main0_ply_v02,
      TppEnemyBodyId.dds6_main0_ply_v03,
      TppEnemyBodyId.dds6_main0_ply_v05,
      TppEnemyBodyId.dds6_main0_ply_v06,
      TppEnemyBodyId.dds6_main0_ply_v07,
      TppEnemyBodyId.dds6_main0_ply_v08,
      TppEnemyBodyId.dds6_main0_ply_v10,
      TppEnemyBodyId.dds6_main0_ply_v11,
      TppEnemyBodyId.dds6_main0_ply_v12,
      TppEnemyBodyId.dds6_main0_ply_v13,
      TppEnemyBodyId.dds6_main0_ply_v14,
      TppEnemyBodyId.dds6_main0_ply_v16,
      TppEnemyBodyId.dds6_main0_ply_v17,
      TppEnemyBodyId.dds6_main0_ply_v18,
      TppEnemyBodyId.dds6_main0_ply_v19,
      TppEnemyBodyId.dds6_main0_ply_v20,
      TppEnemyBodyId.dds6_main0_ply_v22,
      TppEnemyBodyId.dds6_main0_ply_v23,
      TppEnemyBodyId.dds6_main0_ply_v24,
      TppEnemyBodyId.dds6_main0_ply_v25,
      TppEnemyBodyId.dds6_main0_ply_v26,
      TppEnemyBodyId.dds6_main0_ply_v27,
      TppEnemyBodyId.dds6_main0_ply_v28,
      TppEnemyBodyId.dds6_main0_ply_v29,
      TppEnemyBodyId.dds6_main0_ply_v30,
      TppEnemyBodyId.dds6_main0_ply_v31,
      TppEnemyBodyId.dds6_main0_ply_v32,
      TppEnemyBodyId.dds6_main0_ply_v33,
      TppEnemyBodyId.dds6_main0_ply_v35,
      TppEnemyBodyId.dds6_main0_ply_v36,
      TppEnemyBodyId.dds6_main0_ply_v37,
      TppEnemyBodyId.dds6_main0_ply_v38,
      TppEnemyBodyId.dds6_main0_ply_v39,
      TppEnemyBodyId.dds6_main0_ply_v40,
      TppEnemyBodyId.dds6_main0_ply_v41,
      TppEnemyBodyId.dds6_main0_ply_v42,
      TppEnemyBodyId.dds6_main0_ply_v43,
      TppEnemyBodyId.dds6_main0_ply_v44,
      TppEnemyBodyId.dds6_main0_ply_v45,
      TppEnemyBodyId.dds6_main0_ply_v46,
      TppEnemyBodyId.dds6_main0_ply_v47,
      TppEnemyBodyId.dds6_main0_ply_v48,
      TppEnemyBodyId.dds6_main0_ply_v49,
      TppEnemyBodyId.dds6_main0_ply_v50,
      TppEnemyBodyId.dds6_main0_ply_v51,
      TppEnemyBodyId.dds6_main0_ply_v52,
      TppEnemyBodyId.dds6_main0_ply_v53,
      TppEnemyBodyId.dds6_main0_ply_v54,
      TppEnemyBodyId.dds6_main0_ply_v55,
      TppEnemyBodyId.dds6_main0_ply_v56,
      TppEnemyBodyId.dds6_main0_ply_v57,
      TppEnemyBodyId.dds6_main0_ply_v58,
      TppEnemyBodyId.dds6_main0_ply_v59,
      TppEnemyBodyId.dds6_main0_ply_v60,
    },

    partsPath="/Assets/tpp/parts/chara/dds/dds8_main0_def_v00.parts",
    missionPackPath="/Assets/tpp/pack/mission2/common/mis_com_dd_soldier_wait.fpk",
    soldierSubType="DD_FOB",
    useDDHeadgear=true,
}
return this