--cvars.lua
--GENERATED by InfDebug.WriteVars
--2023-04-21 06:39:26
--missionCode:40050
--vscode lua extension lib style: runtime vars arrays are indexed from 0
local this={
  controlType = 0
}
return this