--gvars.lua
--GENERATED by InfDebug.WriteVars
--2023-04-21 06:39:26
--missionCode:40050
--vscode lua extension lib style: runtime vars arrays are indexed from 0
local this={
  DEBUG_initMissionToTitle = 1,
  DEBUG_reserveDestroySaveData = 1,
  DEBUG_showGameStatus = 1,
  DEBUG_showSysVars = 1,
  DEBUG_usingTemporarySaveData = 1,
  canExceptionHandling = 1,
  chickenCapClearCount = 1,
  col_daimondStatus_afgh = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 255, 0, 0, 255, 0, 0, 0, 0, 0, 0, 255, 255, 0, 0, 0, 0, 255, 255, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
    [0] = 0
  },
  col_daimondStatus_mafr = { 0, 0, 0, 255, 0, 0, 0, 255, 255, 255, 0, 255, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 0, 0, 0, 0, 0, 0, 255, 0, 0, 0, 255, 255, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
    [0] = 255
  },
  col_daimondStatus_mtbs = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    [0] = 0
  },
  col_isRegisteredInDb_afgh = { true, true, false, true, true, true, true, false, false, true, true, true, true, true, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true, true, true, true, true, true, true, false, false, true, true, true, false, true, true, true, true, true, true, true, true, true, true, true, true,
    [0] = true
  },
  col_isRegisteredInDb_mafr = { true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, true, true, true, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, true, true, true, false, true, true, true, true, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
    [0] = true
  },
  col_isRegisteredInDb_mtbs = { true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
    [0] = true
  },
  col_markerStatus_afgh = { 850, 849, 985, 859, 860, 861, 853, 858, 197546, 197548, 197549, 197547, 717, 718, 719, 197330, 197365, 197377, 809, 808, 797, 727, 726, 716, 884, 885, 883, 882, 879, 873, 881, 9,
    [0] = 878
  },
  col_markerStatus_mafr = { 197567, 197566, 197568, 197565, 197552, 197553, 197560, 197561, 197544, 197562, 624, 623, 622, 621, 606, 197393, 197024, 197020, 197019, 197021, 197022, 197031, 197023, 197034, 197032, 197033, 197035, 197036, 197016, 196625, 197015, 16,
    [0] = 197017
  },
  col_markerStatus_mtbs = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 20,
    [0] = 0
  },
  continueTipsCount = 1,
  crawlTime = 1,
  dbg_autoMissionOpenClearCheck = 1,
  dbg_forceMaster = 1,
  elapsedTimeSinceLastPlay = 1,
  elapsedTimeSinceLastUseChickCap = 1,
  enableResultPause = 1,
  ene_fovaUniqueBodyIds = { 32766, 32766, 32766, 32766, 32766, 32766, 32766, 32766, 32766, 32766, 32766, 32766, 32766, 32766, 32766,
    [0] = 32766
  },
  ene_fovaUniqueFaceIds = { 32766, 32766, 32766, 32766, 32766, 32766, 32766, 32766, 32766, 32766, 32766, 32766, 32766, 32766, 32766,
    [0] = 32766
  },
  ene_fovaUniqueFlags = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    [0] = 0
  },
  ene_fovaUniqueTargetIds = { 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535,
    [0] = 65535
  },
  ene_isRecoverdInterpreterAfgh = 1,
  ene_isRecoverdInterpreterMafr = 1,
  ene_soldier2CommonPackageLabelIndex = 1,
  ene_takingOverHostageCount = 1,
  ene_takingOverHostageFaceIds = { 0, 0, 0,
    [0] = 0
  },
  ene_takingOverHostageFlags = { 0, 0, 0,
    [0] = 0
  },
  ene_takingOverHostagePositions = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    [0] = 0
  },
  ene_takingOverHostageStaffIdsLower = { 0, 0, 0,
    [0] = 0
  },
  ene_takingOverHostageStaffIdsUpper = { 0, 0, 0,
    [0] = 0
  },
  exc_exceptionProcessing = 1,
  exc_exceptionQueue = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    [0] = 0
  },
  exc_exceptionQueueDepth = 1,
  exc_processState = 1,
  exc_processingExecptionGameMode = 1,
  exc_processingExecptionType = 1,
  exc_queueGameMode = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    [0] = 0
  },
  f30050_NuclearAbolitionCount = 1,
  f30050_discardNuclearCountFromLastAbolition = 1,
  f30050_hangerLevel = 1,
  f30050_isInitNuclearAbolitionCount = 1,
  f30050_missionPackIndex = 1,
  f30050_needUpdateNuclearFlag = 1,
  failedCount = 1,
  firstRescueMillerClearedGMP = 1,
  fobTipsCount = 1,
  forceMbRadioPlayedFlag = { true, true, false, false, true, true, true, true, true, true, false, true, false, false, false, false, false, true,
    [0] = true
  },
  forcePlayerPositionDemoCenter = 1,
  gameDataLoadingResult = 1,
  gim_brekableLightName = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    [0] = 0
  },
  gim_brekableLightStatus = { false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
    [0] = false
  },
  gim_checkPointBreakableObjects = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    [0] = 0
  },
  gim_checkPointStartFultonableObjects = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    [0] = 0
  },
  gim_missionStartBreakableObjects = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    [0] = 0
  },
  gim_missionStartFultonableObjects = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    [0] = 0
  },
  heli_missionStartRoute = 1,
  hosface_groupNumber = 1,
  ini_isReturnToTitle = 1,
  ini_isTitleMode = 1,
  initAmmoInWeapons = { 10, 7, 0,
    [0] = 20
  },
  initAmmoStockCounts = { 0, 40, 0, 21, 36000, 6, 12, 16383, 0, 4, 0, 12, 8, 0, 8, 6, 0, 0, 0, 0, 0, 48,
    [0] = 120
  },
  initAmmoStockIds = { 0, 39, 0, 10, 242, 121, 159, 113, 0, 136, 0, 163, 175, 0, 210, 195, 0, 0, 0, 0, 0, 0,
    [0] = 17
  },
  initAmmoSubInWeapons = { 0, 0, 0,
    [0] = 0
  },
  isContinueFromTitle = 1,
  isFinishFobManualPlacementTutorial = 1,
  isHero = 1,
  isLoadedInitMissionOnSignInUserChanged = 1,
  isMissionClearedS10030 = 1,
  isNewGame = 1,
  isPlayedHappyBirthDayToday = 1,
  localOnlineChallengeTaskVersion = 1,
  mbFreeDemoPlayNextIndex = 1,
  mbFreeDemoPlayRequestFlag = { false, false,
    [0] = false
  },
  mbFreeDemoPlayedFlag = { true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, true, true, true, false, true, true, true, true, true, true, true, true, false, true, false, true, true, true, true, false, false, false, false, true, true, true, true, true,
    [0] = true
  },
  mb_isRecoverd_dlc_staffs = 1,
  mis_checkPoint = 1,
  mis_isExistOpenMissionFlag = 1,
  mis_isStartFromFreePlay = 1,
  mis_isStartFromHelispace = 1,
  mis_missionClearState = 1,
  mis_missionStartRecoverDemoType = 1,
  mis_nextClusterIdForEmergency = 1,
  mis_nextLayoutCodeForEmergency = 1,
  mis_nextMissionCodeForEmergency = 1,
  mis_nextMissionCodeForMissionClear = 1,
  mis_nextMissionStartRouteForEmergency = 1,
  mis_orderBoxName = 1,
  mis_quietCallCountOnMissionStart = 1,
  missionStartClock = 1,
  missionStartExtraWeatherInterval = 1,
  missionStartWeather = 1,
  missionStartWeatherNextTime = 1,
  needWaitMissionInitialize = 1,
  pazEventPhase = 1,
  pazLookedPictureCount = 1,
  pck_missionPackLabelName = 1,
  permitGameSave = 1,
  playTime = 1,
  ply_initialPlayerState = 1,
  ply_isAllGotStation_Afgh = 1,
  ply_isAllGotStation_Mafr = 1,
  ply_isUsingTempItems = 1,
  ply_isUsingTempPlayerType = 1,
  ply_isUsingTempWeapons = 1,
  ply_lastHandEquipUsingTemp = 1,
  ply_lastItemsUsingTemp = { 0, 0, 0, 0, 0, 0, 0,
    [0] = 0
  },
  ply_lastPlayerCamoTypeUsingTemp = 1,
  ply_lastPlayerFaceEquipIdUsingTemp = 1,
  ply_lastPlayerFaceIdUsingTemp = 1,
  ply_lastPlayerHandTypeUsingTemp = 1,
  ply_lastPlayerPartsTypeUsingTemp = 1,
  ply_lastPlayerTypeUsingTemp = 1,
  ply_lastWeaponsUsingTemp = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    [0] = 0
  },
  ply_missionStartPoint = 1,
  ply_missionStartPos = { 0, 0,
    [0] = 0
  },
  ply_missionStartPosForNoOrderBox = { 0, 0,
    [0] = 0
  },
  ply_missionStartRot = 1,
  ply_missionStartRotForNoOrderBox = 1,
  ply_useMissionStartPos = 1,
  ply_useMissionStartPosForNoOrderBox = 1,
  qst_allQuestCleared = 1,
  qst_currentQuestName = 1,
  qst_currentQuestStepNumber = 1,
  qst_elapseCount = 1,
  qst_failedIndex = { -1, -1, -1, -1, -1, -1, -1, -1, -1,
    [0] = -1
  },
  qst_questActiveFlag = { false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, true, true, false, false, false, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, true, false, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
    [0] = false
  },
  qst_questClearedFlag = { true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, true, false, true, true, true, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
    [0] = true
  },
  qst_questOpenFlag = { true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
    [0] = true
  },
  qst_questRepopFlag = { true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, true, true, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
    [0] = false
  },
  qst_randomFaceId = { 392, 40, 375, 356, 172, 513, 257, 10, 466, 71, 513, 382, 464, 3, 264, 167, 16, 342, 90, 282, 272, 164, 211, 167, 519, 513, 516, 508, 500, 518, 501,
    [0] = 0
  },
  qst_volginQuestCleared = 1,
  quietHasFriendshipWithChildFlag = { true, true, true, true,
    [0] = true
  },
  rad_isFinishMissionListTutorial = 1,
  res_bestRank = { 2, 0, 1, 1, 1, 1, 2, 4, 1, 4, 1, 4, 2, 2, 1, 1, 3, 3, 2, 2, 1, 0, 3, 3, 2, 2, 1, 3, 1, 1, 1, 3, 1, 3, 4, 0, 2, 3, 7, 1, 7, 3, 7, 1, 1, 7, 1, 1, 7, 7, 7, 2, 7, 1, 7, 1, 7, 3, 4, 7, 2, 7, 7,
    [0] = 1
  },
  res_headShotCount = { 0, 0,
    [0] = 0
  },
  res_isPerfectStealth = { true, true,
    [0] = false
  },
  res_isStealth = { false, false,
    [0] = false
  },
  res_missionClearHistory = { 10043, 13000, 10040, 13000, 10036, 10040, 10033, 10036, 10020, 10040, 10033, 10036, 10052, 10041, 10040, 10033, 10043, 10036, 10020, 10036, 13000, 13000, 13000, 10043, 11044, 10151, 10150, 11151, 10140, 10240, 0, 0, 0, 0, 0,
    [0] = 13000
  },
  res_missionClearHistorySize = 1,
  res_neutralizeCount = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    [0] = 0
  },
  res_neutralizeCountForPlayData = { 3638, 5922, 2, 105, 13, 28, 326, 207, 234, 107, 34, 20, 402, 70, 6, 73, 94, 125, 8,
    [0] = 2544
  },
  res_neutralizeHistorySize = 1,
  reservedMissionStartMbSync = 1,
  retryCount = 1,
  rev_baseLastVisitedMineAreaAfgh = { 1, 2, 1, 2, 1, 2, 2, 2, 0, 2, 2, 1, 3, 0, 0, 0, 0, 0, 0,
    [0] = 2
  },
  rev_baseLastVisitedMineAreaMafr = { 0, 1, 0, 2, 3, 2, 1, 1, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    [0] = 2
  },
  rev_baseMissionStartMineAreaAfgh = { 1, 2, 1, 2, 1, 2, 2, 2, 0, 2, 2, 1, 3, 0, 0, 0, 0, 0, 0,
    [0] = 2
  },
  rev_baseMissionStartMineAreaMafr = { 0, 1, 0, 2, 3, 2, 1, 1, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    [0] = 2
  },
  rev_lastUpdatedBaseName = 1,
  rev_revengeBlockedCount = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    [0] = 0
  },
  rev_revengeLv = { 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    [0] = 5
  },
  rev_revengePoint = { 0, 250, 0, 0, 0, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    [0] = 549
  },
  rev_revengeRandomValue = 1,
  rnk_CboxGlidingDistance = 1,
  rnk_FirstCommandPostAnnihilateTime = 1,
  rnk_FirstHeadShotTime = 1,
  rnk_FirstHeadShotTimeTranq = 1,
  rnk_FobDefenceSucceedCount = 1,
  rnk_FobSneakingGoalCount = 1,
  rnk_LongestBirdShotDistance = 1,
  rnk_MechaNeutralizeCount = 1,
  rnk_NuclearDisposeCount = 1,
  rnk_TotalTacticalTakeDownCount = 1,
  rnk_XPersonMarkingTime = 1,
  rnk_XPersonPerfectStealthCQCNeutralizeTime = 1,
  rnk_XRocketArmNeutralizeTime = 1,
  rnk_isOpen = { true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
    [0] = false
  },
  rnk_missionBestScore = { 121921, 135921, 164365, 187575, 205888, 165594, 55436, 32441, 135044, 59742, 182002, 35004, 113989, 120482, 185702, 134871, 87763, 89781, 119005, 111361, 138586, 80128, 90247, 0, 112961, 101287, 266764, 95823, 153497, 299620, 167942, 96088, 176782, 0, 51853, 116056, 0, 74384, 0, 260373, 0, 0, 0, 134303, 182689, 0, 192189, 165850, 0, 0, 0, 0, 0, 140751, 0, 173917, 0, 95343, 51759, 0, 0, 0, 0,
    [0] = 137990
  },
  rnk_missionBestScoreUsedLimitEquip = { 143477, 0, 169464, 0, 227437, 199300, 137680, 0, 147460, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 62511, 0, 0, 0, 0, 165714, 0, 171879, 0, 0, 72655, 0, 0, 157441, 0, 0, 0, 0, 61002, 0, 0, 0, 0, 0, 0, 0, 0, 0, 185101, 0, 0, 0, 0, 0, 0, 0, 0, 136030, 0, 0,
    [0] = 0
  },
  rnk_mtbs_q42010 = 1,
  rnk_mtbs_q42020 = 1,
  rnk_mtbs_q42030 = 1,
  rnk_mtbs_q42040 = 1,
  rnk_mtbs_q42050 = 1,
  rnk_mtbs_q42060 = 1,
  rnk_mtbs_q42070 = 1,
  rwd_mbManagementRewardLangEnum = { 45, 52, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 17, 45, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    [0] = 45
  },
  rwd_mbManagementRewardParam = { 3397848781, 3017684269, 6, 904572705, 3017684269, 4, 0, 0, 6, 3900978555, 2242999088, 6, 3064129511, 2242999088, 6, 1087367424, 2242999088, 6, 2456235432, 2242999088, 6, 1749152701, 2242999088, 6, 1176502891, 2242999088, 6, 3298945012, 3017684269, 6, 1810896670, 3017684269, 6, 2945326109, 2242999088, 6, 4143318375, 3017684269, 6, 2964370098, 2242999088, 2, 0, 0, 8, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    [0] = 6
  },
  rwd_mbManagementRewardStackSize = 1,
  rwd_missionRewardLangEnum = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    [0] = 0
  },
  rwd_missionRewardParam = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    [0] = 0
  },
  rwd_missionRewardStackSize = 1,
  rwd_questRewardLangEnum = { 0, 0, 0, 0, 0, 0, 0,
    [0] = 0
  },
  rwd_questRewardParam = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    [0] = 0
  },
  rwd_questRewardStackSize = 1,
  s10043_forceMissionClear = 1,
  s10100_boyEscape = { true, true, true, true,
    [0] = true
  },
  s10100_boyEscapeCurrentPlay = { true, true, true, true,
    [0] = true
  },
  s10240_isPlayedFuneralDemo = 1,
  sav_SaveResultCheckFileName = 1,
  sav_isCheckPointSaving = 1,
  sav_isReservedMbSaveResultNotify = 1,
  sav_varRestoreForContinue = 1,
  solface_groupNumber = 1,
  sortieGmpCost = 1,
  squatTime = 1,
  str_didLostQuiet = 1,
  str_elapsedMissionCount = { -1, 3, -1, 0, 0, -127, -127, -127, -127, -127, -127, -1, -127,
    [0] = -1
  },
  str_isAllMissionCleared = 1,
  str_isAllMissionSRankCleared = 1,
  str_missionClearedFlag = { true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, true, false, true, false, true, true, false, true, true, false, false, false, true, false, true, false, true, false, true, true, false, true, false, false,
    [0] = true
  },
  str_missionNewOpenFlag = { false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
    [0] = false
  },
  str_missionOpenFlag = { true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, true, false, true, false, true, true, false, true, true, false, false, false, true, false, true, false, true, false, true, true, false, true, false, false,
    [0] = true
  },
  str_missionOpenPermission = { true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, true, false, true, false, true, true, false, true, true, false, false, false, true, false, true, false, true, false, true, true, false, true, false, false,
    [0] = true
  },
  str_quietReunionMissionCount = 1,
  str_storySequence = 1,
  timeParadoxCount = 1,
  title_nextLocationCode = 1,
  title_nextMissionCode = 1,
  totalAnnihilateBaseCount = 1,
  totalAnnihilateOutPostCount = 1,
  totalBreakBurglarAlarmCount = 1,
  totalBreakPlacedGimmickCount = 1,
  totalBreakVehicleCount = 1,
  totalHelicopterDestoryCount = 1,
  totalInterrogateCount = 1,
  totalKillCount = 1,
  totalMarkingCount = 1,
  totalMineRemoveCount = 1,
  totalMissionClearCount = 1,
  totalNeutralizeCount = 1,
  totalPerfectStealthMissionClearCount = 1,
  totalRescueCount = 1,
  totalRetryCount = 1,
  totalStealthMissionClearCount = 1,
  totalWalkerGearDestoryCount = 1,
  totalheadShotCount = 1,
  trm_animalRecoverHistory = { 1, 1, 1, 1, 1, 1, 1, 18, 1, 1, 6, 18, 18, 1, 1, 18, 18, 2, 2, 1, 1, 1, 1, 18, 1, 1, 2, 1, 1, 18, 1, 1, 18, 18, 18, 18, 18, 18, 1, 1, 1, 1, 1, 1, 1, 0, 6, 0, 0,
    [0] = 1
  },
  trm_animalRecoverHistorySize = 1,
  trm_currentPandemicBingoCount = 1,
  trm_currentPandemicRestCount = 1,
  trm_doneFobTutorialInThisGame = 1,
  trm_doneIsolateByManual = 1,
  trm_donePandemicEvent = 1,
  trm_donePandemicTutorial = 1,
  trm_doneUpdatePandemicLimit = 1,
  trm_fobTutorialState = 1,
  trm_isPushConstructedFirstFob = 1,
  trm_isPushRewardAnimalPlatform = 1,
  trm_isPushRewardBattleGearDevelopComplete = 1,
  trm_isPushRewardBuddyCommand = { true, true, true, true,
    [0] = true
  },
  trm_isPushRewardCanCustomVehicle = 1,
  trm_isPushRewardCanDevArm = 1,
  trm_isPushRewardCanDevBattleGear = 1,
  trm_isPushRewardCanDevDDog = 1,
  trm_isPushRewardCanDevDWalker = 1,
  trm_isPushRewardCanDevNuclear = 1,
  trm_isPushRewardCanDevParasiteSuit = 1,
  trm_isPushRewardCanDevQuiet = 1,
  trm_isPushRewardCanDevQuietEquip = 1,
  trm_isPushRewardGunSmith = 1,
  trm_isPushRewardOpenFob = 1,
  trm_isPushRewardOpenMBDvcArmsMenu = 1,
  trm_isPushRewardOpenSection = { true, true, true, true, true, true, false,
    [0] = false
  },
  trm_isPushRewardOpenWeaponCustomize = 1,
  trm_isPushRewardSeparationPlatform = 1,
  trm_lastPandemicBingoCount = 1,
  trm_recoveredAfghGoatCount = 1,
  trm_recoveredDonkeyCount = 1,
  trm_recoveredHostageCount = 1,
  trm_recoveredMafrGoatCount = 1,
  trm_recoveredOkapiCount = 1,
  trm_recoveredSoldierCount = 1,
  trm_recoveredZebraCount = 1,
  trp_isGot = { true, true, true, true, true, true, true, true, true, true, true, true, false, false, true, true, true, true, false, true, false, true, false, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false,
    [0] = false
  },
  ui_isControlGuidShownInThisGame = { false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
    [0] = false
  },
  ui_isControlGuideShownOnce = { false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, true, true, false, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, false, false, false, true, true, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
    [0] = false
  },
  ui_isTaskLastComleted = { true, false, false, false, false, false, false, true, true, true, true, true, true, false, false, true, true, true, true, true, false, false, false, true, true, true, true, true, false, false, false, true, true, true, true, true, true, false, false, true, true, true, true, true, false, false, false, true, true, true, true, true, true, false, false, true, true, true, false, true, true, true, false, true, false, true, true, true, false, true, true, false, true, true, true, true, false, false, false, true, true, false, true, true, false, false, false, true, true, true, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, true, false, true, true, false, false, true, true, true, true, true, false, false, false, false, true, true, true, true, true, false, false, true, true, true, true, false, false, false, true, true, true, true, true, true, true, true, false, false, true, false, true, false, true, false, false, true, true, true, true, true, false, false, true, true, false, false, true, true, false, false, false, true, true, true, true, true, true, true, true, true, false,
    [0] = true
  },
  ui_isTipsGuidShownInThisGame = { false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
    [0] = false
  },
  ui_isTipsGuideShownOnce = { false, false, true, false, false, true, false, false, true, false, false, false, false, true, false, false, false, false, false, false, false, false, true, true, true, false, false, false, true, false, false, true, false, true, true, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, true, false, false, true, true, true, false, true, false, false, false, true, false, false, false, true, true, true, true, false, true, false, true, true, true, false, false, false, true, false, false, false, false, false, false, false, false, false, true, true, false, true, false, false, false, true, false, false, true, true, true, false, false, false, false, false, false, true, false, false, false, false, true, true, true, true, true, false, false, false, false, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
    [0] = false
  },
  usingNormalMissionSlot = 1,
  waitLoadingTipsEnd = 1
}
return this