--mvars.lua
--GENERATED by InfDebug.WriteVars
--2023-04-21 06:39:26
--missionCode:40050
--vscode lua extension lib style: runtime vars arrays are indexed from 0
local this={
  FreeHeliRadio_addOptionRadioCount = {},
  ani_isQuestSetup = false,
  ani_questGameObjectIdList = {},
  ani_questTargetList = {},
  dem_demoFlags = {},
  dem_demoFuncs = {},
  dem_demoList = {},
  dem_invDemoList = {},
  dem_invScdDemolist = {},
  dem_isSkipped = {},
  dem_playedList = {},
  dem_resereveEnableInGameFlag = true,
  demo_finishWaitRequestInfo = {},
  demo_playRequestInfo = {
    demoBlock = {},
    missionBlock = {}
  },
  doneSyncNuclearLocalToServer = true,
  ene_cpCount = 0,
  ene_disablePowerSettings = {},
  ene_eliminateTargetList = {},
  ene_isQuestHeli = false,
  ene_isQuestSetup = false,
  ene_maxHeliStateCount = 1,
  ene_maxSoldierStateCount = 160,
  ene_maxWalkerGearStateCount = 4,
  ene_missionRequiresPowerSettings = {},
  ene_missionSoldierPersonalAbilitySettings = {},
  ene_missionSoldierPowerSettings = {},
  ene_noShiftChangeGroupSetting = {},
  ene_questArmorId = 0,
  ene_questBalaclavaId = 0,
  ene_questGetLoadedFaceTable = {},
  ene_questTargetList = {},
  ene_questVehicleList = {},
  ene_routeAnimationGaniPathTable = { { "SoldierLookWatch", "/Assets/tpp/motion/SI_game/fani/bodies/enem/enemasr/enemasr_s_pat_idl_act_a.gani" }, { "SoldierWipeFace", "/Assets/tpp/motion/SI_game/fani/bodies/enem/enemasr/enemasr_s_pat_idl_act_d.gani" }, { "SoldierYawn", "/Assets/tpp/motion/SI_game/fani/bodies/enem/enemasr/enemasr_s_pat_idl_act_f.gani" }, { "SoldierSneeze", "/Assets/tpp/motion/SI_game/fani/bodies/enem/enemasr/enemasr_s_pat_idl_act_g.gani" }, { "SoldierFootStep", "/Assets/tpp/motion/SI_game/fani/bodies/enem/enemasr/enemasr_s_pat_idl_act_h.gani" }, { "SoldierCough", "/Assets/tpp/motion/SI_game/fani/bodies/enem/enemasr/enemasr_s_pat_idl_act_i.gani" }, { "SoldierScratchHead", "/Assets/tpp/motion/SI_game/fani/bodies/enem/enemasr/enemasr_s_pat_idl_act_o.gani" }, { "SoldierHungry", "/Assets/tpp/motion/SI_game/fani/bodies/enem/enemasr/enemasr_s_pat_idl_act_p.gani" } },
  ene_routeSets = {},
  ene_soldier2CommonBlockPackageLabel = "default",
  ene_soldierPersonalAbilitySettings = {},
  ene_soldierPowerSettings = {},
  ene_soldierTypes = {},
  gim_connectLandingZoneTable = {
    banana_aacr001 = { "lz_banana_I0000|lz_banana_I_0000" },
    cliffTown_aacr001 = { "lz_cliffTown_I0000|lz_cliffTown_I_0000" },
    commFacility_aacr001 = { "lz_commFacility_I0000|lz_commFacility_I_0000" },
    diamond_aacr001 = { "lz_diamond_I0000|lz_diamond_I_0000" },
    enemyBase_aacr001 = { "lz_enemyBase_I0000|lz_enemyBase_I_0000" },
    field_aacr001 = { "lz_field_I0000|lz_field_I_0000" },
    flowStation_aacr001 = { "lz_flowStation_I0000|lz_flowStation_I_0000" },
    fort_aacr001 = { "lz_fort_I0000|lz_fort_I_0000" },
    hill_aacr001 = { "lz_hill_I0000|lz_hill_I_0000" },
    pfCamp_aacr001 = { "lz_pfCamp_I0000|lz_pfCamp_I_0000" },
    powerPlant_aacr001 = { "lz_powerPlant_E0000|lz_powerPlant_E_0000" },
    remnants_aacr001 = { "lz_remnants_I0000|lz_remnants_I_0000" },
    savannah_aacr001 = { "lz_savannah_I0000|lz_savannah_I_0000" },
    slopedTown_aacr001 = { "lz_slopedTown_I0000|lz_slopedTown_I_0000" },
    sovietBase_aacr001 = { "lz_sovietBase_E0000|lz_sovietBase_E_0000" },
    swamp_aacr001 = { "lz_swamp_I0000|lz_swamp_I_0000" },
    tent_aacr001 = { "lz_tent_I0000|lz_tent_I_0000" }
  },
  gim_isQuestSetup = false,
  gim_isquestMarkStart = false,
  gim_questMarkCount = 0,
  gim_questMarkSetIndex = 0,
  gim_questMarkTotalCount = 0,
  gim_questTargetList = {},
  gim_shownEspionageBox = true,
  hel_isExistSupportHelicopter = true,
  heliSpace_DisableSelectSortieTimeFromMissionPreparetion = {
    [10020] = true,
    [10080] = true
  },
  heliSpace_NoBuddyMenuFromMissionPreparetion = {
    [10020] = true,
    [10115] = true,
    [30050] = true,
    [30250] = true,
    [50050] = true
  },
  heliSpace_NoVehicleMenuFromMissionPreparetion = {
    [10115] = true,
    [30050] = true,
    [30150] = true,
    [30250] = true,
    [50050] = true
  },
  heliSpace_SkipMissionPreparetion = {
    [10010] = true,
    [10020] = false,
    [10030] = true,
    [10240] = true,
    [10280] = true,
    [11043] = true,
    [11044] = true,
    [30050] = true,
    [30150] = true,
    [30250] = true
  },
  helispacePlayerTransform = {
    pos = { 0, 1197.6850585938, -1.0599999427795 },
    rotY = 0
  },
  isExistSaveData = true,
  ldz_assaultDropLandingZoneTable = {
    [694120472] = true,
    [705202089] = true,
    [1649373165] = true,
    [1708709563] = true,
    [2259452923] = true,
    [2656289118] = true,
    [2691946923] = true,
    [2699722927] = true,
    [2976202158] = true,
    [2980488803] = true,
    [3101903048] = true,
    [3151133361] = true,
    [3353143331] = true,
    [3356266804] = true,
    [3380702832] = true,
    [3667595332] = true,
    [4068701460] = true
  },
  loc_locationBaseTelop = {
    DisableBaseName = <function 1>,
    DispBaseName = <function 2>,
    DispBaseNameNoTelop = <function 3>,
    Messages = <function 4>,
    OnInitialize = <function 5>,
    OnMessage = <function 6>,
    OnReload = <function 7>,
    SetupTypingTextMessages = <function 8>,
    _OnEnterForUpdateFobClearedPlantCount = <function 9>,
    _OnTelop = <function 10>,
    _OnTelopStart = <function 11>,
    _OnTrap = <function 12>,
    _scriptInstanceId = <userdata 1>,
    _scriptPath = "mtbs_baseTelop",
    cpLangIdTable = { { "platform_main", "platform_main", "platform_en_main" }, { "platform_combat", "platform_combat", "platform_en_combat" }, { "platform_RD", "platform_RD", "platform_en_RD" }, { "platform_support", "platform_support", "platform_en_support" }, { "platform_medical", "platform_medical", "platform_en_medical" }, { "platform_intel", "platform_intel", "platform_en_intel" }, { "platform_base_dev", "platform_base_dev", "platform_en_base_dev" }, { "platform_zoo_bird", "platform_zoo_bird", "platform_en_zoo_bird" }, { "platform_zoo_herbivore1", "platform_zoo_herbivore1", "platform_en_zoo_herbivore1" }, { "platform_zoo_canivore", "platform_zoo_canivore", "platform_en_zoo_canivore" }, { "platform_zoo_herbivore2", "platform_zoo_herbivore2", "platform_en_zoo_herbivore2" }, { "platform_isolation", "platform_isolation", "platform_en_isolation" } },
    messageExecTable = {
      [2524903270] = {},
      [3087473413] = {
        [4187264311] = {
          func = <function 11>
        }
      }
    }
  },
  loc_locationCommonTable = {
    OnAllocate = <function 13>,
    OnInitialize = <function 14>,
    OnMessage = <function 15>,
    OnMissionCanStart = <function 16>,
    OnReload = <function 17>,
    _scriptInstanceId = <userdata 2>,
    _scriptPath = "mtbs",
    requires = { "/Assets/tpp/script/location/mtbs/mtbs_enemy.lua", "/Assets/tpp/script/location/mtbs/mtbs_item.lua", "/Assets/tpp/script/location/mtbs/mtbs_cluster.lua", "/Assets/tpp/script/location/mtbs/mtbs_baseTelop.lua", "/Assets/tpp/script/location/mtbs/mtbs_helicopter.lua" }
  },
  mar_searchTargetList = {},
  mbBaseTelop_clusterGrade = 1,
  mbBaseTelop_isTelop = false,
  mbBaseTelop_plntTelopName = "platform_1st",
  mbHelicopter_startClusterId = 1,
  mbHelicopter_startIsHeliport = false,
  mbHelicopter_startPlatformId = 1,
  mis_checkPointList = {},
  mis_helicopterDoorOpenTimerTimeSec = 15,
  mis_ignoreAlertOfMissionArea = true,
  mis_isAlertOutOfMissionArea = false,
  mis_isOutsideOfHotZone = true,
  mis_isOutsideOfMissionArea = false,
  mis_missionName = "h40050",
  mis_missionStateIsNotInGame = false,
  mtbsClst_constructTable = { 4, 4, 4, 4, 4, 4, 4 },
  newGameConfirmResult = 0,
  ply_equipMissionBlockGroupSize = 0,
  ply_maxPickableLocatorCount = 101,
  ply_maxPlacedLocatorCount = 21,
  qst_blockName = "quest_block",
  qst_isQuestNewOpenFlag = false,
  qst_questList = { {
      activeArea = { 117, 135, 130, 151 },
      areaName = "tent",
      infoList = { {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          isStory = true,
          name = "tent_q99040"
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          isStory = true,
          name = "tent_q20910"
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          isStory = true,
          name = "tent_q80010"
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          name = "tent_q99072"
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          name = "quest_q20015"
        }, {
          invokeStepName = "QStep_Start",
          name = "tent_q10010"
        }, {
          invokeStepName = "QStep_Start",
          name = "tent_q11010"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q52030"
        }, {
          invokeStepName = "QStep_Start",
          name = "tent_q11020"
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          name = "tent_q60011"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q52025"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q21005"
        }, {
          invokeStepName = "QStep_Start",
          name = "tent_q71010"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q52085"
        }, {
          invokeStepName = "QStep_Start",
          name = "tent_q71030"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q52140"
        } },
      invokeArea = { 117, 135, 130, 151 },
      loadArea = { 116, 134, 131, 152 },
      locationId = 10
    }, {
      activeArea = { 133, 139, 138, 154 },
      areaName = "field",
      infoList = { {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          isStory = true,
          name = "field_q80020"
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          name = "ruins_q60115"
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          name = "field_q30010"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q20025"
        }, {
          invokeStepName = "QStep_Start",
          name = "field_q10020"
        }, {
          invokeStepName = "QStep_Start",
          name = "field_q71020"
        }, {
          invokeStepName = "QStep_Start",
          name = "field_q71090"
        } },
      invokeArea = { 133, 139, 138, 154 },
      loadArea = { 132, 138, 139, 155 },
      locationId = 10
    }, {
      activeArea = { 141, 139, 147, 153 },
      areaName = "ruins",
      infoList = { {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          isStory = true,
          name = "ruins_q19010"
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          name = "ruins_q60010"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q52010"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q20035"
        }, {
          invokeStepName = "QStep_Start",
          name = "ruins_q10030"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q52135"
        } },
      invokeArea = { 141, 139, 147, 153 },
      loadArea = { 140, 138, 148, 154 },
      locationId = 10
    }, {
      activeArea = { 118, 126, 130, 132 },
      areaName = "waterway",
      infoList = { {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          isStory = true,
          name = "sovietBase_q20912"
        }, {
          invokeStepName = "QStep_Start",
          isOnce = true,
          isStory = true,
          name = "waterway_q99010",
          strictIsOnce = true
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          isStory = true,
          name = "waterway_q99012"
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          isStory = true,
          name = "waterway_q80040"
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          name = "waterway_q39010"
        }, {
          invokeStepName = "QStep_Start",
          name = "waterway_q10040"
        }, {
          invokeStepName = "QStep_Start",
          name = "waterway_q11030"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q52015"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q20045"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q52130"
        }, {
          invokeStepName = "QStep_Start",
          name = "waterway_q71040"
        } },
      invokeArea = { 118, 126, 130, 132 },
      loadArea = { 117, 125, 131, 133 },
      locationId = 10
    }, {
      activeArea = { 133, 121, 140, 136 },
      areaName = "cliffTown",
      infoList = { {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          name = "citadel_q60112"
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          name = "cliffTown_q99080"
        }, {
          invokeStepName = "QStep_Start",
          name = "cliffTown_q10050"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q52035"
        }, {
          invokeStepName = "QStep_Start",
          name = "cliffTown_q11040"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q20055"
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          name = "cliffTown_q60012"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q52080"
        }, {
          invokeStepName = "QStep_Start",
          name = "cliffTown_q71050"
        }, {
          invokeStepName = "QStep_Start",
          name = "cliffTown_q71060"
        } },
      invokeArea = { 133, 121, 140, 136 },
      loadArea = { 132, 120, 141, 137 },
      locationId = 10
    }, {
      activeArea = { 143, 129, 152, 136 },
      areaName = "commFacility",
      infoList = { {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          isStory = true,
          name = "commFacility_q80060"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q20065"
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          isStory = true,
          name = "commFacility_q19013"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q20805"
        }, {
          invokeStepName = "QStep_Start",
          name = "commFacility_q10060"
        }, {
          invokeStepName = "QStep_Start",
          name = "commFacility_q11080"
        } },
      invokeArea = { 143, 129, 152, 136 },
      loadArea = { 142, 128, 153, 137 },
      locationId = 10
    }, {
      activeArea = { 113, 115, 130, 123 },
      areaName = "sovietBase",
      infoList = { {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          isStory = true,
          name = "sovietBase_q99020"
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          isStory = true,
          name = "sovietBase_q99030"
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          name = "sovietBase_q60110"
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          name = "sovietBase_q60111"
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          name = "sovietBase_q99070"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q20075"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q52040"
        }, {
          invokeStepName = "QStep_Start",
          name = "sovietBase_q10070"
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          name = "sovietBase_q60014"
        }, {
          invokeStepName = "QStep_Start",
          name = "sovietBase_q71070"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q52145"
        } },
      invokeArea = { 113, 115, 130, 123 },
      loadArea = { 112, 114, 131, 124 },
      locationId = 10
    }, {
      activeArea = { 143, 117, 152, 126 },
      areaName = "fort",
      infoList = { {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          isStory = true,
          name = "fort_q20911"
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          isStory = true,
          name = "fort_q80080"
        }, {
          invokeStepName = "QStep_Start",
          isOnce = false,
          name = "quest_q20085"
        }, {
          invokeStepName = "QStep_Start",
          name = "fort_q10080"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q20905"
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          name = "fort_q60013"
        }, {
          invokeStepName = "QStep_Start",
          name = "fort_q11060"
        }, {
          invokeStepName = "QStep_Start",
          name = "fort_q11070"
        }, {
          invokeStepName = "QStep_Start",
          name = "fort_q71080"
        } },
      invokeArea = { 143, 117, 152, 126 },
      loadArea = { 142, 116, 153, 127 },
      locationId = 10
    }, {
      activeArea = { 119, 106, 124, 112 },
      areaName = "citadel",
      infoList = { {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          name = "quest_q20095"
        }, {
          invokeStepName = "QStep_Start",
          name = "citadel_q10090"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q22005"
        } },
      invokeArea = { 119, 106, 124, 112 },
      loadArea = { 118, 105, 125, 113 },
      locationId = 10
    }, {
      activeArea = { 122, 125, 131, 149 },
      areaName = "outland",
      infoList = { {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          isStory = true,
          name = "outland_q20913"
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          isStory = true,
          name = "outland_q80100"
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          name = "outland_q60113"
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          name = "outland_q99071"
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          name = "outland_q60024"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q52020"
        }, {
          invokeStepName = "QStep_Start",
          name = "outland_q10100"
        }, {
          invokeStepName = "QStep_Start",
          name = "outland_q11090"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q20105"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q52055"
        }, {
          invokeStepName = "QStep_Start",
          name = "outland_q11100"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q52115"
        }, {
          invokeStepName = "QStep_Start",
          name = "outland_q71200"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q52110"
        } },
      invokeArea = { 122, 125, 131, 149 },
      loadArea = { 121, 124, 132, 150 },
      locationId = 20
    }, {
      activeArea = { 134, 140, 147, 149 },
      areaName = "pfCamp",
      infoList = { {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          isStory = true,
          name = "pfCamp_q80200"
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          name = "pfCamp_q60114"
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          name = "pfCamp_q39012"
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          name = "quest_q20205"
        }, {
          invokeStepName = "QStep_Start",
          name = "pfCamp_q10200"
        }, {
          invokeStepName = "QStep_Start",
          name = "pfCamp_q11200"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q25005"
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          name = "pfCamp_q60020"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q52065"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q52060"
        }, {
          invokeStepName = "QStep_Start",
          name = "savannah_q71300"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q52100"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q52125"
        } },
      invokeArea = { 134, 140, 147, 149 },
      loadArea = { 133, 139, 148, 150 },
      locationId = 20
    }, {
      activeArea = { 134, 130, 144, 137 },
      areaName = "savannah",
      infoList = { {
          invokeStepName = "QStep_Start",
          name = "quest_q20305"
        }, {
          invokeStepName = "QStep_Start",
          name = "savannah_q11400"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q52075"
        }, {
          invokeStepName = "QStep_Start",
          name = "savannah_q10300"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q52050"
        }, {
          invokeStepName = "QStep_Start",
          name = "savannah_q11300"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q52105"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q52120"
        } },
      invokeArea = { 134, 130, 144, 137 },
      loadArea = { 133, 129, 145, 138 },
      locationId = 20
    }, {
      activeArea = { 147, 130, 158, 137 },
      areaName = "hill",
      infoList = { {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          isStory = true,
          name = "hill_q80400"
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          isStory = true,
          name = "hill_q19012"
        }, {
          invokeStepName = "QStep_Start",
          name = "hill_q10400"
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          name = "hill_q60021"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q52070"
        }, {
          invokeStepName = "QStep_Start",
          name = "hill_q11500"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q27005"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q52095"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q20405"
        } },
      invokeArea = { 147, 130, 158, 137 },
      loadArea = { 146, 129, 159, 138 },
      locationId = 20
    }, {
      activeArea = { 134, 111, 140, 127 },
      areaName = "banana",
      infoList = { {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          isStory = true,
          name = "outland_q19011"
        }, {
          invokeStepName = "QStep_Start",
          name = "outland_q40010"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q23005"
        }, {
          invokeStepName = "QStep_Start",
          name = "banana_q10500"
        }, {
          invokeStepName = "QStep_Start",
          name = "banana_q11600"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q20505"
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          name = "banana_q60023"
        }, {
          invokeStepName = "QStep_Start",
          name = "banana_q11700"
        }, {
          invokeStepName = "QStep_Start",
          name = "banana_q71400"
        } },
      invokeArea = { 134, 111, 140, 127 },
      loadArea = { 133, 110, 141, 128 },
      locationId = 20
    }, {
      activeArea = { 143, 111, 148, 127 },
      areaName = "diamond",
      infoList = { {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          isStory = true,
          name = "diamond_q80600"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q20605"
        }, {
          invokeStepName = "QStep_Start",
          name = "diamond_q10600"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q26005"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q52045"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q52090"
        }, {
          invokeStepName = "QStep_Start",
          name = "diamond_q71500"
        } },
      invokeArea = { 143, 111, 148, 127 },
      loadArea = { 142, 110, 149, 128 },
      locationId = 20
    }, {
      activeArea = { 151, 111, 158, 127 },
      areaName = "lab",
      infoList = { {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          isStory = true,
          name = "lab_q20914"
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          isStory = true,
          name = "lab_q80700"
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          name = "lab_q39011"
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          name = "quest_q20705"
        }, {
          invokeStepName = "QStep_Start",
          name = "quest_q24005"
        }, {
          invokeStepName = "QStep_Start",
          name = "cliffTown_q11050"
        }, {
          invokeStepName = "QStep_Start",
          name = "lab_q10700"
        }, {
          invokeStepName = "QStep_Start",
          name = "lab_q71600"
        }, {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          name = "lab_q60022"
        }, {
          invokeStepName = "QStep_Start",
          name = "lab_q71700"
        } },
      invokeArea = { 151, 111, 158, 127 },
      loadArea = { 150, 110, 159, 128 },
      locationId = 20
    }, {
      areaName = "MtbsCommand",
      clusterName = "Command",
      infoList = { {
          invokeStepName = "QStep_Start",
          name = "Mtbs_child_dog",
          strictIsOnce = true
        }, {
          invokeStepName = "QStep_Start",
          name = "mtbs_q42010"
        } },
      locationId = 50
    }, {
      areaName = "MtbsCombat",
      clusterName = "Combat",
      infoList = { {
          invokeStepName = "QStep_Start",
          name = "mtbs_q42070"
        } },
      locationId = 50
    }, {
      areaName = "MtbsDevelop",
      clusterName = "Develop",
      infoList = { {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          isStory = true,
          name = "mtbs_q99050"
        }, {
          invokeStepName = "QStep_Start",
          name = "mtbs_q42020"
        } },
      locationId = 50
    }, {
      areaName = "MtbsMedical",
      clusterName = "Medical",
      infoList = { {
          defaultIsOnce = true,
          invokeStepName = "QStep_Start",
          isOnce = false,
          isStory = true,
          name = "mtbs_q99011"
        }, {
          invokeStepName = "QStep_Start",
          name = "mtbs_q42050"
        } },
      locationId = 50
    }, {
      areaName = "MtbsSupport",
      clusterName = "Support",
      infoList = { {
          invokeStepName = "QStep_Start",
          name = "mtbs_q42030"
        } },
      locationId = 50
    }, {
      areaName = "MtbsSpy",
      clusterName = "Spy",
      infoList = { {
          invokeStepName = "QStep_Start",
          name = "mtbs_q42060"
        } },
      locationId = 50
    }, {
      areaName = "MtbsBaseDev",
      clusterName = "BaseDev",
      infoList = { {
          invokeStepName = "QStep_Start",
          name = "mtbs_q42040"
        } },
      locationId = 50
    }, {
      areaName = "MtbsPaz",
      clusterName = "MedicalPaz",
      infoList = { {
          invokeStepName = "QStep_Start",
          isOnce = true,
          isStory = true,
          name = "mtbs_q99060",
          strictIsOnce = true
        } },
      locationId = 50
    } },
  rad_commonRadioDelayTable = { "long", "long",
    [11] = "mid",
    [12] = "mid",
    [22] = 8,
    [24] = "mid",
    [25] = "mid",
    [27] = "long",
    [28] = "long",
    [32] = "long"
  },
  rad_commonRadioTable = { "f1000_rtrg0100", "f1000_rtrg1550", "f1000_rtrg0110", "f1000_rtrg0116", "f1000_rtrg8050", "f1000_rtrg0010", "f1000_rtrg8040", "f1000_rtrg8030", "f1000_rtrg8060", "f1000_rtrg0030", "f1000_rtrg0120", "f1000_rtrg0130", "f1000_rtrg0050", "f1000_rtrg0070", "f1000_rtrg0060", "f1000_rtrg9050", "f1000_rtrg9040", "f1000_rtrg9030", "f1000_rtrg9020", "f1000_rtrg9010", "f1000_rtrg9010", "f1000_rtrg0690", "f1000_rtrg0060", "f1000_rtrg2120", "f1000_rtrg2171", "f1000_rtrg9020", "f1000_rtrg1640", "f1000_rtrg1640", "f1000_rtrg1680", "f1000_rtrg4440", "f1000_rtrg8050", "f1000_rtrg2020", "f1000_rtrg5020", "f1000_rtrg5021", "f1000_rtrg3780", "f1000_rtrg0090", "f1000_rtrg1940", "f1000_rtrg0080", "f1000_rtrg1050", "f1000_rtrg4520" },
  rad_debugRadioLineTable = {},
  rad_gameOverRadioTable = { "f8000_gmov0010", "f8000_gmov0020", "f8000_gmov0030", "f8000_gmov0040", "f8000_gmov0050", "f8000_gmov0060", "f8000_gmov0110", "f8000_gmov0120", "f8000_gmov0123", "f8000_gmov0230", "f8000_gmov2500",
    [255] = "f8000_gmov9090"
  },
  rad_intelRadioList = {},
  rad_optionalRadioInvList = {
    [3682974642] = "Set_f2000_oprg4010"
  },
  rad_optionalRadioList = { "Set_f2000_oprg4010" },
  rad_optionalRadioPlayOnceList = {
    Set_f2000_oprg4010 = false
  },
  rad_radioInvList = {
    [862208655] = "f2000_rtrg1120",
    [2944459689] = "f2000_rtrg1110",
    [3989105201] = "f2000_rtrg1130"
  },
  rad_radioList = { "f2000_rtrg1110", "f2000_rtrg1120", "f2000_rtrg1130" },
  rad_radioPlayOnceList = {
    f2000_rtrg1110 = false,
    f2000_rtrg1120 = false,
    f2000_rtrg1130 = false
  },
  rad_subScripts = {
    photo = {
      DEBUG_ClearForceShow = <function 18>,
      DEBUG_DumpConditionResult = <function 19>,
      DEBUG_ForceShow = <function 20>,
      DEBUG_IsForceShow = <function 21>,
      GROUP_ID_LIST = { 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2 },
      HideMESH = <function 22>,
      MESH_LIST = {
        [38] = "MESH_38",
        [39] = "MESH_39",
        [40] = "MESH_40",
        [41] = "MESH_41"
      },
      OPEN_CONDITION_LIST = { <function 23>, <function 24>, <function 25>, <function 26>, <function 27>, <function 28>, <function 29>, <function 30>, <function 31>, <function 32>, <function 33>, <function 34>, <function 35>, <function 36>, <function 37>, <function 38>, <function 39>, <function 40>, <function 41>, <function 42>, <function 43>, <function 44>, <function 45>, <function 46>, <function 47>, <function 48>, <function 49>, <function 50>, <function 51>, <function 52>, <function 53>, <function 54>, <function 55>, <function 56>, <function 57>, <function 58>, <function 59>, <function 60>, <function 61>, <function 62>, <function 63>, <function 64> },
      OnBuddyBlockLoad = <function 65>,
      OnRestoreSVars = <function 66>,
      Show = <function 67>,
      ShowMESH = <function 68>,
      UNIT_LIST = { { 0 }, { 1 }, { 0, 2 }, { 0, 2, 3 }, { 0, 2, 3, 4 }, { 1, 5 }, { 1, 5, 6 }, { 0 }, { 1 }, { 2 }, { 3 }, { 4 }, { 5 }, { 6 }, { 7 }, { 8, 9 }, { 10 }, { 11, 12 }, { 13, 14 }, { 15 }, { 16 }, { 17 }, { 0 }, { 1, 2 }, { 3 }, { 4 }, { 5 }, { 6 }, { 7 }, { 8, 9 }, { 10 }, { 11 }, { 12 }, { 12, 13 }, { 12, 14 }, { 12, 15 }, { 12, 16 } },
      _scriptInstanceId = <userdata 3>,
      _scriptPath = "heli_common_photo"
    },
    radio = {
      AddGZStaff = <function 69>,
      InsertToActiveOptionalRadio = <function 70>,
      MissionListGuide00 = <function 71>,
      MissionListGuide10 = <function 72>,
      RemoveToActiveOptionalRadio = <function 73>,
      SetOptionalRadioFromSituation = <function 74>,
      SetOptionalRadioInEmergency = <function 75>,
      _scriptInstanceId = <userdata 4>,
      _scriptPath = "heli_common_radio",
      debugRadioLineTable = {},
      optionalRadioList = { "Set_f2000_oprg4010" },
      radioList = { "f2000_rtrg1110", "f2000_rtrg1120", "f2000_rtrg1130" }
    },
    sequence = {
      ALWAYS_APPLY_TEMPORATY_PLAYER_PARTS_SETTING = true,
      AcquireHelispaceStartCassetteTape = <function 76>,
      AddCommonHeliSpaceMessage = <function 77>,
      AddHeliSpaceDebugMenu = <function 78>,
      ClearMissionListGuidanceLimitation = <function 79>,
      ClearTerminalAttentionIcon = <function 80>,
      CommonBuddyHeliSpaceSetting = <function 81>,
      DEBUG_strCode32List = { "MissionPrep_Start", "MissionPrep_Abort", "MissionPrep_End", "MissionPrep_StartEdit", "MissionPrep_ChangeEditTarget", "MissionPrep_EndEdit", "MissionPrep_StartSlotSelect", "MissionPrep_ChangeSlot", "MissionPrep_EndSlotSelect", "MissionPrep_StartItemSelect", "MissionPrep_ChangeItem", "MissionPrep_EndItemSelect", "MissionPrep_StartModelView", "MissionPrep_EndtModelView", "MissionPrep_FocusTarget_Weapon", "MissionPrep_FocusTarget_PrimaryWeapon", "MissionPrep_FocusTarget_SecondaryWeapon", "MissionPrep_FocusTarget_SupportWeapon", "MissionPrep_FocusTarget_Item", "MissionPrep_FocusTarget_Suit", "MissionPrep_FocusTarget_Player", "MissionPrep_FocusTarget_Buddy", "MissionPrep_FocusTarget_Vehicle", "MissionPrep_FocusTarget_None", "MbDvcActSelectAvatarMenu" },
      DebugUpdate = <function 82>,
      DisableGameStatusFunction = <function 83>,
      DisableGameStatusOnHelispace = <function 84>,
      EQUIP_MISSION_BLOCK_GROUP_SIZE = 0,
      EnableGameStatusFunction = <function 85>,
      GetExceptGameStatusOnSortieMenu = <function 86>,
      GetFobTutorialSequenceName = <function 87>,
      MAX_PICKABLE_LOCATOR_COUNT = 1,
      MAX_PLACED_LOCATOR_COUNT = 1,
      Messages = <function 88>,
      MissionPrepare = <function 89>,
      OnAbortMissionPreparation = <function 90>,
      OnBuddyBlockLoad = <function 91>,
      OnEndFadeOutGoToMGO = <function 92>,
      OnEndFadeOutMissionPreparetionEnd = <function 93>,
      OnEndFadeOutSelectLandingPoint = <function 94>,
      OnEndMissionPrepareSequence = <function 95>,
      OnLoad = <function 96>,
      OnMissionPreparetionEnd = <function 97>,
      OnRestoreSVars = <function 98>,
      OnSelectLandPoint = <function 99>,
      OnStartFobMission = <function 100>,
      OnTerminate = <function 101>,
      OnUpdate = <function 102>,
      OnUpdateChunkInstalling = <function 103>,
      OverrideFadeInGameStatus = <function 104>,
      PlayerHeliSpaceToPrepareSpace = <function 105>,
      PlayerPrepareSpaceToHeliSpace = <function 106>,
      RealizeHeliPilot = <function 107>,
      RestoreClock = <function 108>,
      RestoreWeather = <function 109>,
      SaveCurrentClock = <function 110>,
      SelectGoToMGO = <function 111>,
      SelectPauseMenuOpenStore = <function 112>,
      SetBuddyHeliSpaceSetting = <function 113>,
      SetCameraStageCenter = <function 114>,
      SetCameraStageCenter_Go = <function 115>,
      SetCameraStageCenter_GoOut = <function 116>,
      SetCustomizePreviewPosition = <function 117>,
      SetEditingTimeAndWeather = <function 118>,
      SetMissionPrepPreviewPosition = <function 119>,
      SetMissionPrepPreviewRotation = <function 120>,
      SetPandemicTutorialMbMenuActive = <function 121>,
      SetTerminalAttentionIcon = <function 122>,
      StartPilotMotion = <function 123>,
      StartRain = <function 124>,
      StopRain = <function 125>,
      TitleModeOnEnterFunction = <function 126>,
      UpdateCameraParameter = <function 127>,
      _messageExecTable = {
        [3105039150] = {
          [824988796] = {
            sender = {
              [3704233593] = <function 128>
            },
            senderOption = {
              [3704233593] = {
                [2357387275] = true
              }
            }
          },
          [1201114382] = {
            func = <function 129>
          }
        },
        [4133365783] = {
          [1378767181] = {
            func = <function 130>
          },
          [2878679236] = {
            func = <function 131>
          }
        }
      },
      _scriptInstanceId = <userdata 5>,
      _scriptPath = "heli_common_sequence",
      saveVarsList = {
        showInfoTypingText = false
      }
    }
  },
  res_enablePlayStyle = true,
  res_hitRatioBonusParam = {
    exponetHitRatio = 6,
    hitRatioBaseScoreUnit = 30,
    limitHitRatioBonus = 1000,
    numOfBulletsPerNeutralizeCount = 10,
    perfectBonusBase = 30000
  },
  res_noResult = true,
  res_rankLimitedSetting = {},
  res_rankTable = {
    A = 100000,
    B = 60000,
    C = 30000,
    D = 10000,
    E = 0,
    S = 130000
  },
  res_scoreTable = {
    alertCount = {
      valueToScoreRatio = -5000
    },
    firstSpecialBonus = 5000,
    headShotCount = {
      valueToScoreRatio = 1000
    },
    hostageCount = {
      valueToScoreRatio = 5000
    },
    interrogateCount = {
      valueToScoreRatio = 150
    },
    markingCount = {
      valueToScoreRatio = 30
    },
    neutralizeCount = {
      valueToScoreRatio = 200
    },
    noAlertBonus = 5000,
    noKillBonus = 5000,
    noReflexBonus = 10000,
    noRetryBonus = 5000,
    noTraceBonus = 100000,
    perfectStealthNoKillBonus = 20000,
    rediscoveryCount = {
      valueToScoreRatio = -500
    },
    secondSpecialBonus = 5000,
    tacticalActionPoint = {
      valueToScoreRatio = 1000
    },
    takeHitCount = {
      valueToScoreRatio = -100
    }
  },
  revenge_isEnabledSuperReinforce = true,
  revenge_revengeConfig = {},
  revenge_revengeType = {},
  sbl_currentScriptBlockPackInfo = {},
  sbl_preloadRequestTable = {},
  sbl_scriptBlockPackList = {
    quest_block = {
      Mtbs_SmokingSoldierCombat = <1>{ "/Assets/tpp/pack/mission2/quest/mtbs/Common/quest_smoking.fpk" },
      Mtbs_SmokingSoldierCommand = <2>{ "/Assets/tpp/pack/mission2/quest/mtbs/Common/quest_smoking.fpk" },
      Mtbs_child_dog = <3>{ "/Assets/tpp/pack/mission2/quest/mtbs/Command/quest_child_dog.fpk" },
      Mtbs_ddog_walking = <4>{ "/Assets/tpp/pack/mission2/quest/mtbs/Command/quest_ddog_walking.fpk" },
      banana_q10500 = <5>{ "/Assets/tpp/pack/mission2/quest/mafr/banana/banana_q10500.fpk", 2.8860073590625e+014 },
      banana_q11600 = <6>{ "/Assets/tpp/pack/mission2/quest/mafr/banana/banana_q11600.fpk", 6.9606721518712e+014 },
      banana_q11700 = <7>{ "/Assets/tpp/pack/mission2/quest/mafr/banana/banana_q11700.fpk", 6.9606721518712e+014 },
      banana_q60023 = <8>{ "/Assets/tpp/pack/mission2/quest/mafr/banana/banana_q60023.fpk" },
      banana_q71400 = <9>{ "/Assets/tpp/pack/mission2/quest/mafr/banana/banana_q71400.fpk", 6.9606721518712e+014 },
      citadel_q10090 = <10>{ "/Assets/tpp/pack/mission2/quest/afgh/citadel/citadel_q10090.fpk", 5.0210411593718e+014 },
      citadel_q60112 = <11>{ "/Assets/tpp/pack/mission2/quest/afgh/citadel/citadel_q60112.fpk" },
      cliffTown_q10050 = <12>{ "/Assets/tpp/pack/mission2/quest/afgh/cliffTown/cliffTown_q10050.fpk", 5.0210411593718e+014 },
      cliffTown_q11040 = <13>{ "/Assets/tpp/pack/mission2/quest/afgh/cliffTown/cliffTown_q11040.fpk", 34731772857448 },
      cliffTown_q11050 = <14>{ "/Assets/tpp/pack/mission2/quest/afgh/cliffTown/cliffTown_q11050.fpk", 6.9606721518712e+014 },
      cliffTown_q60012 = <15>{ "/Assets/tpp/pack/mission2/quest/afgh/cliffTown/cliffTown_q60012.fpk" },
      cliffTown_q71050 = <16>{ "/Assets/tpp/pack/mission2/quest/afgh/cliffTown/cliffTown_q71050.fpk" },
      cliffTown_q71060 = <17>{ "/Assets/tpp/pack/mission2/quest/afgh/cliffTown/cliffTown_q71060.fpk", 34731772857448 },
      cliffTown_q99080 = <18>{ "/Assets/tpp/pack/mission2/quest/afgh/cliffTown/cliffTown_q99080.fpk", 6.2666671024702e+014 },
      commFacility_q10060 = <19>{ "/Assets/tpp/pack/mission2/quest/afgh/commFacility/commFacility_q10060.fpk", 5.0210411593718e+014 },
      commFacility_q11080 = <20>{ "/Assets/tpp/pack/mission2/quest/afgh/commFacility/commFacility_q11080.fpk", 34731772857448 },
      commFacility_q19013 = <21>{ "/Assets/tpp/pack/mission2/quest/afgh/commFacility/commFacility_q19013.fpk", 9.2918410367174e+014, 7.4688230893153e+014, 6.6329250328294e+014 },
      commFacility_q80060 = <22>{ "/Assets/tpp/pack/mission2/quest/afgh/commFacility/commFacility_q80060.fpk", 8.3879912050382e+014 },
      diamond_q10600 = <23>{ "/Assets/tpp/pack/mission2/quest/mafr/diamond/diamond_q10600.fpk", 2.8860073590625e+014 },
      diamond_q71500 = <24>{ "/Assets/tpp/pack/mission2/quest/mafr/diamond/diamond_q71500.fpk", 6.9606721518712e+014 },
      diamond_q80600 = <25>{ "/Assets/tpp/pack/mission2/quest/mafr/diamond/diamond_q80600.fpk", 1.0604636849787e+015 },
      field_q10020 = <26>{ "/Assets/tpp/pack/mission2/quest/afgh/field/field_q10020.fpk", 5.0210411593718e+014 },
      field_q30010 = <27>{ "/Assets/tpp/pack/mission2/quest/afgh/field/field_q30010.fpk" },
      field_q71020 = <28>{ "/Assets/tpp/pack/mission2/quest/afgh/field/field_q71020.fpk" },
      field_q71090 = <29>{ "/Assets/tpp/pack/mission2/quest/afgh/field/field_q71090.fpk", 34731772857448 },
      field_q80020 = <30>{ "/Assets/tpp/pack/mission2/quest/afgh/field/field_q80020.fpk", 8.3879912050382e+014 },
      fort_q10080 = <31>{ "/Assets/tpp/pack/mission2/quest/afgh/fort/fort_q10080.fpk", 5.0210411593718e+014 },
      fort_q11060 = <32>{ "/Assets/tpp/pack/mission2/quest/afgh/fort/fort_q11060.fpk", 34731772857448 },
      fort_q11070 = <33>{ "/Assets/tpp/pack/mission2/quest/afgh/fort/fort_q11070.fpk", 34731772857448 },
      fort_q20911 = <34>{ "/Assets/tpp/pack/mission2/quest/afgh/fort/fort_q20911.fpk", 3.1112695686119e+014 },
      fort_q60013 = <35>{ "/Assets/tpp/pack/mission2/quest/afgh/fort/fort_q60013.fpk" },
      fort_q71080 = <36>{ "/Assets/tpp/pack/mission2/quest/afgh/fort/fort_q71080.fpk", 34731772857448 },
      fort_q80080 = <37>{ "/Assets/tpp/pack/mission2/quest/afgh/fort/fort_q80080.fpk", 8.3879912050382e+014 },
      hill_q10400 = <38>{ "/Assets/tpp/pack/mission2/quest/mafr/hill/hill_q10400.fpk", 2.8860073590625e+014 },
      hill_q11500 = <39>{ "/Assets/tpp/pack/mission2/quest/mafr/hill/hill_q11500.fpk", 6.9606721518712e+014 },
      hill_q19012 = <40>{ "/Assets/tpp/pack/mission2/quest/mafr/hill/hill_q19012.fpk", 5.0985957137922e+014, 7.070957317144e+014, 1.0033862142801e+015, 7.5305436131848e+014, 8.8716641795276e+014 },
      hill_q60021 = <41>{ "/Assets/tpp/pack/mission2/quest/mafr/hill/hill_q60021.fpk" },
      hill_q80400 = <42>{ "/Assets/tpp/pack/mission2/quest/mafr/hill/hill_q80400.fpk", 1.0604636849787e+015 },
      lab_q10700 = <43>{ "/Assets/tpp/pack/mission2/quest/mafr/lab/lab_q10700.fpk", 2.8860073590625e+014 },
      lab_q20914 = <44>{ "/Assets/tpp/pack/mission2/quest/mafr/lab/lab_q20914.fpk", 3.1112695686119e+014 },
      lab_q39011 = <45>{ "/Assets/tpp/pack/mission2/quest/mafr/lab/lab_q39011.fpk" },
      lab_q60022 = <46>{ "/Assets/tpp/pack/mission2/quest/mafr/lab/lab_q60022.fpk" },
      lab_q71600 = <47>{ "/Assets/tpp/pack/mission2/quest/mafr/lab/lab_q71600.fpk" },
      lab_q71700 = <48>{ "/Assets/tpp/pack/mission2/quest/mafr/lab/lab_q71700.fpk" },
      lab_q80700 = <49>{ "/Assets/tpp/pack/mission2/quest/mafr/lab/lab_q80700.fpk", 1.0604636849787e+015 },
      mtbs_q101210 = <50>{ "/Assets/tpp/pack/mission2/quest/mtbs/Common/quest_q101210.fpk" },
      mtbs_q101220 = <51>{ "/Assets/tpp/pack/mission2/quest/mtbs/Common/quest_q101220.fpk" },
      mtbs_q42010 = <52>{ "/Assets/tpp/pack/mission2/quest/mtbs/Command/quest_q42010.fpk" },
      mtbs_q42020 = <53>{ "/Assets/tpp/pack/mission2/quest/mtbs/Develop/quest_q42020.fpk" },
      mtbs_q42030 = <54>{ "/Assets/tpp/pack/mission2/quest/mtbs/Support/quest_q42030.fpk" },
      mtbs_q42040 = <55>{ "/Assets/tpp/pack/mission2/quest/mtbs/BaseDev/quest_q42040.fpk" },
      mtbs_q42050 = <56>{ "/Assets/tpp/pack/mission2/quest/mtbs/Medical/quest_q42050.fpk" },
      mtbs_q42060 = <57>{ "/Assets/tpp/pack/mission2/quest/mtbs/Spy/quest_q42060.fpk" },
      mtbs_q42070 = <58>{ "/Assets/tpp/pack/mission2/quest/mtbs/Combat/quest_q42070.fpk" },
      mtbs_q99011 = <59>{ "/Assets/tpp/pack/mission2/quest/mtbs/Medical/quest_visit_quiet.fpk", "/Assets/tpp/pack/mission2/free/f30050/f30050_ocelot.fpk", "/Assets/tpp/pack/mission2/free/f30050/f30050_d400.fpk" },
      mtbs_q99050 = <60>{ "/Assets/tpp/pack/mission2/quest/mtbs/Command/quest_liquid_challenge.fpk", "/Assets/tpp/pack/mission2/free/f30050/f30050_liquid.fpk" },
      mtbs_return_quiet = <61>{ "/Assets/tpp/pack/mission2/quest/mtbs/Common/quest_return_quiet.fpk" },
      mtbs_wait_quiet = <62>{ "/Assets/tpp/pack/mission2/quest/mtbs/Medical/quest_wait_quiet.fpk" },
      outland_q10100 = <63>{ "/Assets/tpp/pack/mission2/quest/mafr/outland/outland_q10100.fpk", 2.8860073590625e+014 },
      outland_q11090 = <64>{ "/Assets/tpp/pack/mission2/quest/mafr/outland/outland_q11090.fpk", 6.9606721518712e+014 },
      outland_q11100 = <65>{ "/Assets/tpp/pack/mission2/quest/mafr/outland/outland_q11100.fpk", 6.9606721518712e+014 },
      outland_q19011 = <66>{ "/Assets/tpp/pack/mission2/quest/mafr/outland/outland_q19011.fpk", 5.7918346525234e+014, 3.6082123670719e+014, 8.0096871326271e+014 },
      outland_q20913 = <67>{ "/Assets/tpp/pack/mission2/quest/mafr/outland/outland_q20913.fpk", 3.1112695686119e+014 },
      outland_q40010 = <68>{ "/Assets/tpp/pack/mission2/quest/mafr/outland/outland_q40010.fpk" },
      outland_q60024 = <69>{ "/Assets/tpp/pack/mission2/quest/mafr/outland/outland_q60024.fpk" },
      outland_q60113 = <70>{ "/Assets/tpp/pack/mission2/quest/mafr/outland/outland_q60113.fpk" },
      outland_q71200 = <71>{ "/Assets/tpp/pack/mission2/quest/mafr/outland/outland_q71200.fpk", 6.9606721518712e+014 },
      outland_q80100 = <72>{ "/Assets/tpp/pack/mission2/quest/mafr/outland/outland_q80100.fpk", 1.0604636849787e+015 },
      outland_q99071 = <73>{ "/Assets/tpp/pack/mission2/quest/mafr/outland/outland_q99071.fpk", 3.6658167206315e+014, 7.8114539169501e+014, 5.2319037036529e+014 },
      pfCamp_q10200 = <74>{ "/Assets/tpp/pack/mission2/quest/mafr/pfCamp/pfCamp_q10200.fpk", 2.8860073590625e+014 },
      pfCamp_q11200 = <75>{ "/Assets/tpp/pack/mission2/quest/mafr/pfCamp/pfCamp_q11200.fpk", 6.9606721518712e+014 },
      pfCamp_q39012 = <76>{ "/Assets/tpp/pack/mission2/quest/mafr/pfCamp/pfCamp_q39012.fpk" },
      pfCamp_q60020 = <77>{ "/Assets/tpp/pack/mission2/quest/mafr/pfCamp/pfCamp_q60020.fpk" },
      pfCamp_q60114 = <78>{ "/Assets/tpp/pack/mission2/quest/mafr/pfCamp/pfCamp_q60114.fpk" },
      pfCamp_q80200 = <79>{ "/Assets/tpp/pack/mission2/quest/mafr/pfCamp/pfCamp_q80200.fpk", 1.0604636849787e+015 },
      quest_q20015 = <80>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q20015.fpk", 1.1117345321653e+015, 1.6749512742102e+014 },
      quest_q20025 = <81>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q20025.fpk", 1.033270344361e+015, 8.3970704667361e+014, 1.1018771882639e+015, 7.0365974738116e+014 },
      quest_q20035 = <82>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q20035.fpk", 2.6513069268585e+014, 8.6122864186633e+014 },
      quest_q20045 = <83>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q20045.fpk", 1.033270344361e+015, 6.8027386235752e+014, 6.2054052620692e+014, 1.8148419662043e+014 },
      quest_q20055 = <84>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q20055.fpk", 9.1551917253887e+014, 19124862124193, 8692552422657, 1.0631960843031e+015 },
      quest_q20065 = <85>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q20065.fpk", 9.1561874880872e+014, 1.0033862142801e+015 },
      quest_q20075 = <86>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q20075.fpk", 1.033270344361e+015, 27918720453105, 8692552422657, 1.0631960843031e+015 },
      quest_q20085 = <87>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q20085.fpk", 4.4831754744976e+014, 1.9923566661958e+014, 1.1117345321653e+015, 1.6749512742102e+014 },
      quest_q20095 = <88>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q20095.fpk", 2.6513069268585e+014, 6.6329250328294e+014, 1.1117345321653e+015, 1.6749512742102e+014 },
      quest_q20105 = <89>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q20105.fpk", 1.0855907727076e+015, 5.8312013212109e+014, 8.9643434154595e+014, 4.9703720741883e+014 },
      quest_q20205 = <90>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q20205.fpk", 7.070957317144e+014, 8.8118923902867e+014, 1.1117345321653e+015, 1.6749512742102e+014 },
      quest_q20305 = <91>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q20305.fpk", 1.033270344361e+015, 27918720453105, 8692552422657, 1.0631960843031e+015 },
      quest_q20405 = <92>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q20405.fpk", 3.3248770241308e+014, 6.8027386235752e+014, 9.9425770117456e+014, 95952797231590 },
      quest_q20505 = <93>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q20505.fpk", 3.1901706824606e+014, 5.8312013212109e+014, 8.9643434154595e+014, 4.9703720741883e+014 },
      quest_q20605 = <94>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q20605.fpk", 8.0615973844348e+014, 8.0096871326271e+014 },
      quest_q20705 = <95>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q20705.fpk", 7.0051011489067e+014, 4.8555974576561e+014, 1.1117345321653e+015, 1.6749512742102e+014 },
      quest_q20805 = <96>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q20805.fpk", 7.7867174989084e+014, 1.0033862142801e+015 },
      quest_q20905 = <97>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q20905.fpk", 7.4941221987663e+014, 6.6329250328294e+014 },
      quest_q21005 = <98>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q21005.fpk", 3.6082123670719e+014, 7.8477247150408e+014 },
      quest_q22005 = <99>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q22005.fpk", 4.2125549261473e+014, 9.0688108450208e+014 },
      quest_q23005 = <100>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q23005.fpk", 2.3466639088604e+014, 4.2185550531638e+014 },
      quest_q24005 = <101>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q24005.fpk", 2.3466639088604e+014, 4.8555974576561e+014 },
      quest_q25005 = <102>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q25005.fpk", 8.9349039417313e+014, 1.0033862142801e+015 },
      quest_q26005 = <103>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q26005.fpk", 7.4688230893153e+014, 1.7370907276487e+014 },
      quest_q27005 = <104>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q27005.fpk", 7.7867174989084e+014, 1.0033862142801e+015 },
      quest_q52010 = <105>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q52010.fpk" },
      quest_q52015 = <106>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q52015.fpk" },
      quest_q52020 = <107>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q52020.fpk" },
      quest_q52025 = <108>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q52025.fpk" },
      quest_q52030 = <109>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q52030.fpk" },
      quest_q52035 = <110>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q52035.fpk" },
      quest_q52040 = <111>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q52040.fpk" },
      quest_q52045 = <112>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q52045.fpk" },
      quest_q52050 = <113>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q52050.fpk" },
      quest_q52055 = <114>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q52055.fpk" },
      quest_q52060 = <115>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q52060.fpk" },
      quest_q52065 = <116>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q52065.fpk" },
      quest_q52070 = <117>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q52070.fpk" },
      quest_q52075 = <118>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q52075.fpk" },
      quest_q52080 = <119>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q52080.fpk" },
      quest_q52085 = <120>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q52085.fpk" },
      quest_q52090 = <121>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q52090.fpk" },
      quest_q52095 = <122>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q52095.fpk" },
      quest_q52100 = <123>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q52100.fpk" },
      quest_q52105 = <124>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q52105.fpk" },
      quest_q52110 = <125>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q52110.fpk" },
      quest_q52115 = <126>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q52115.fpk" },
      quest_q52120 = <127>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q52120.fpk" },
      quest_q52125 = <128>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q52125.fpk" },
      quest_q52130 = <129>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q52130.fpk" },
      quest_q52135 = <130>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q52135.fpk" },
      quest_q52140 = <131>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q52140.fpk" },
      quest_q52145 = <132>{ "/Assets/tpp/pack/mission2/quest/extra/quest_q52145.fpk" },
      ruins_q10030 = <133>{ "/Assets/tpp/pack/mission2/quest/afgh/ruins/ruins_q10030.fpk", 5.0210411593718e+014 },
      ruins_q19010 = <134>{ "/Assets/tpp/pack/mission2/quest/afgh/ruins/ruins_q19010.fpk", 17054529337534, 8.1360779670256e+014, 8.0096871326271e+014 },
      ruins_q60010 = <135>{ "/Assets/tpp/pack/mission2/quest/afgh/ruins/ruins_q60010.fpk" },
      ruins_q60115 = <136>{ "/Assets/tpp/pack/mission2/quest/afgh/ruins/ruins_q60115.fpk" },
      savannah_q10300 = <137>{ "/Assets/tpp/pack/mission2/quest/mafr/savannah/savannah_q10300.fpk", 2.8860073590625e+014 },
      savannah_q11300 = <138>{ "/Assets/tpp/pack/mission2/quest/mafr/savannah/savannah_q11300.fpk", 6.9606721518712e+014 },
      savannah_q11400 = <139>{ "/Assets/tpp/pack/mission2/quest/mafr/savannah/savannah_q11400.fpk", 6.9606721518712e+014 },
      savannah_q71300 = <140>{ "/Assets/tpp/pack/mission2/quest/mafr/savannah/savannah_q71300.fpk" },
      sovietBase_q10070 = <141>{ "/Assets/tpp/pack/mission2/quest/afgh/sovietBase/sovietBase_q10070.fpk", 5.0210411593718e+014 },
      sovietBase_q20912 = <142>{ "/Assets/tpp/pack/mission2/quest/afgh/sovietBase/sovietBase_q20912.fpk", 3.1112695686119e+014 },
      sovietBase_q60014 = <143>{ "/Assets/tpp/pack/mission2/quest/afgh/sovietBase/sovietBase_q60014.fpk" },
      sovietBase_q60110 = <144>{ "/Assets/tpp/pack/mission2/quest/afgh/sovietBase/sovietBase_q60110.fpk" },
      sovietBase_q60111 = <145>{ "/Assets/tpp/pack/mission2/quest/afgh/sovietBase/sovietBase_q60111.fpk" },
      sovietBase_q71070 = <146>{ "/Assets/tpp/pack/mission2/quest/afgh/sovietBase/sovietBase_q71070.fpk" },
      sovietBase_q99020 = <147>{ "/Assets/tpp/pack/mission2/quest/afgh/sovietBase/sovietBase_q99020.fpk" },
      sovietBase_q99030 = <148>{ "/Assets/tpp/pack/mission2/quest/afgh/sovietBase/sovietBase_q99030.fpk" },
      sovietBase_q99070 = <149>{ "/Assets/tpp/pack/mission2/quest/afgh/sovietBase/sovietBase_q99070.fpk", 9.2918410367174e+014, 2.6513069268585e+014, 9.0688108450208e+014 },
      tent_q10010 = <150>{ "/Assets/tpp/pack/mission2/quest/afgh/tent/tent_q10010.fpk", 5.0210411593718e+014 },
      tent_q11010 = <151>{ "/Assets/tpp/pack/mission2/quest/afgh/tent/tent_q11010.fpk", 34731772857448 },
      tent_q11020 = <152>{ "/Assets/tpp/pack/mission2/quest/afgh/tent/tent_q11020.fpk", 34731772857448 },
      tent_q20910 = <153>{ "/Assets/tpp/pack/mission2/quest/afgh/tent/tent_q20910.fpk", 3.1112695686119e+014 },
      tent_q60011 = <154>{ "/Assets/tpp/pack/mission2/quest/afgh/tent/tent_q60011.fpk" },
      tent_q71010 = <155>{ "/Assets/tpp/pack/mission2/quest/afgh/tent/tent_q71010.fpk" },
      tent_q71030 = <156>{ "/Assets/tpp/pack/mission2/quest/afgh/tent/tent_q71030.fpk" },
      tent_q80010 = <157>{ "/Assets/tpp/pack/mission2/quest/afgh/tent/tent_q80010.fpk", 8.3879912050382e+014 },
      tent_q99040 = <158>{ "/Assets/tpp/pack/mission2/quest/afgh/tent/tent_q99040.fpk" },
      tent_q99072 = <159>{ "/Assets/tpp/pack/mission2/quest/afgh/tent/tent_q99072.fpk", 9.2918410367174e+014, 1.6954015565029e+014, 8.8167060310192e+014, 6.1073840684733e+014, 3.2392975404106e+014 },
      waterway_q10040 = <160>{ "/Assets/tpp/pack/mission2/quest/afgh/waterway/waterway_q10040.fpk", 5.0210411593718e+014 },
      waterway_q11030 = <161>{ "/Assets/tpp/pack/mission2/quest/afgh/waterway/waterway_q11030.fpk", 34731772857448 },
      waterway_q39010 = <162>{ "/Assets/tpp/pack/mission2/quest/afgh/waterway/waterway_q39010.fpk" },
      waterway_q71040 = <163>{ "/Assets/tpp/pack/mission2/quest/afgh/waterway/waterway_q71040.fpk", 34731772857448 },
      waterway_q80040 = <164>{ "/Assets/tpp/pack/mission2/quest/afgh/waterway/waterway_q80040.fpk", 8.3879912050382e+014 },
      waterway_q99010 = <165>{ "/Assets/tpp/pack/mission2/quest/battle/bossQuiet/qest_bossQuiet_00.fpk" },
      waterway_q99012 = <166>{ "/Assets/tpp/pack/mission2/quest/afgh/waterway/waterway_q99012.fpk" }
    }
  },
  sbl_scriptBlockState = {},
  sbl_scriptBlockStrCode32PackList = {
    [4294967295] = {
      [8815889] = <table 152>,
      [15298604] = <table 106>,
      [31399358] = <table 128>,
      [61268110] = <table 45>,
      [68767676] = <table 20>,
      [108464869] = <table 114>,
      [116057804] = <table 109>,
      [118147909] = <table 117>,
      [122309485] = <table 1>,
      [122403652] = <table 53>,
      [182061589] = <table 7>,
      [188839195] = <table 108>,
      [222746551] = <table 102>,
      [245529752] = <table 61>,
      [249316755] = <table 156>,
      [288016354] = <table 79>,
      [291609277] = <table 16>,
      [300870656] = <table 150>,
      [306241539] = <table 51>,
      [337705122] = <table 146>,
      [342464951] = <table 127>,
      [349049057] = <table 129>,
      [361128665] = <table 54>,
      [487071618] = <table 44>,
      [496554407] = <table 136>,
      [524819621] = <table 134>,
      [547077843] = <table 112>,
      [574445288] = <table 5>,
      [590706319] = <table 115>,
      [629340864] = <table 27>,
      [651825427] = <table 107>,
      [679133029] = <table 111>,
      [723012577] = <table 143>,
      [741686164] = <table 46>,
      [742956078] = <table 162>,
      [807423984] = <table 42>,
      [818916054] = <table 90>,
      [823329420] = <table 49>,
      [823746985] = <table 164>,
      [861748001] = <table 132>,
      [899976985] = <table 163>,
      [930926900] = <table 78>,
      [947013403] = <table 85>,
      [959289908] = <table 92>,
      [968892307] = <table 33>,
      [992570653] = <table 118>,
      [1000383767] = <table 105>,
      [1031671366] = <table 17>,
      [1098239311] = <table 130>,
      [1179726560] = <table 131>,
      [1195370412] = <table 35>,
      [1221822499] = <table 101>,
      [1234106181] = <table 76>,
      [1255866463] = <table 14>,
      [1256354976] = <table 6>,
      [1300819550] = <table 8>,
      [1325936108] = <table 77>,
      [1339727572] = <table 135>,
      [1350813887] = <table 74>,
      [1359646886] = <table 113>,
      [1377238570] = <table 94>,
      [1407279556] = <table 157>,
      [1461748525] = <table 84>,
      [1486749932] = <table 99>,
      [1508621371] = <table 160>,
      [1543020697] = <table 147>,
      [1567153452] = <table 89>,
      [1590724292] = <table 72>,
      [1603140950] = <table 98>,
      [1622269302] = <table 12>,
      [1656576923] = <table 96>,
      [1672993731] = <table 97>,
      [1690708814] = <table 126>,
      [1727916964] = <table 67>,
      [1767427454] = <table 151>,
      [1774450776] = <table 39>,
      [1786058974] = <table 57>,
      [1790899210] = <table 82>,
      [1824743146] = <table 52>,
      [1825020564] = <table 110>,
      [1866102911] = <table 139>,
      [1872801272] = <table 149>,
      [1940317574] = <table 68>,
      [1952178125] = <table 38>,
      [1964629647] = <table 145>,
      [1965623970] = <table 154>,
      [2000605732] = <table 13>,
      [2015048971] = <table 122>,
      [2042145200] = <table 26>,
      [2052105250] = <table 148>,
      [2079746597] = <table 43>,
      [2107673305] = <table 166>,
      [2114197346] = <table 93>,
      [2167949237] = <table 47>,
      [2241620541] = <table 161>,
      [2287866210] = <table 144>,
      [2297983151] = <table 40>,
      [2304162146] = <table 80>,
      [2342329749] = <table 104>,
      [2403919578] = <table 137>,
      [2405739154] = <table 125>,
      [2483666494] = <table 100>,
      [2484213005] = <table 138>,
      [2494683353] = <table 56>,
      [2555476735] = <table 48>,
      [2583361299] = <table 11>,
      [2619352949] = <table 116>,
      [2644082802] = <table 88>,
      [2652623265] = <table 87>,
      [2666887956] = <table 62>,
      [2681041029] = <table 24>,
      [2698228734] = <table 30>,
      [2724550483] = <table 73>,
      [2725187743] = <table 25>,
      [2728551291] = <table 95>,
      [2735999057] = <table 159>,
      [2749582542] = <table 29>,
      [2753325586] = <table 65>,
      [2762940041] = <table 3>,
      [2871636664] = <table 86>,
      [2901998177] = <table 153>,
      [2970112411] = <table 28>,
      [2984537443] = <table 2>,
      [2992220056] = <table 120>,
      [3037734334] = <table 32>,
      [3068851148] = <table 121>,
      [3108379070] = <table 81>,
      [3140288208] = <table 83>,
      [3214828614] = <table 60>,
      [3216850383] = <table 155>,
      [3219493069] = <table 69>,
      [3229190286] = <table 15>,
      [3241439375] = <table 66>,
      [3260050431] = <table 71>,
      [3287198109] = <table 63>,
      [3300885464] = <table 34>,
      [3319197797] = <table 124>,
      [3336993868] = <table 55>,
      [3337260637] = <table 165>,
      [3356634183] = <table 75>,
      [3365655464] = <table 158>,
      [3382967578] = <table 23>,
      [3406536285] = <table 103>,
      [3412123506] = <table 10>,
      [3426387649] = <table 18>,
      [3519380551] = <table 19>,
      [3565815998] = <table 50>,
      [3627952171] = <table 58>,
      [3681802338] = <table 59>,
      [3774104021] = <table 91>,
      [3824256746] = <table 4>,
      [3863368764] = <table 37>,
      [3874686337] = <table 119>,
      [3942303839] = <table 123>,
      [3945160195] = <table 142>,
      [3958526442] = <table 133>,
      [3973124133] = <table 36>,
      [4001756235] = <table 141>,
      [4016437235] = <table 31>,
      [4055607884] = <table 41>,
      [4081037652] = <table 21>,
      [4107978157] = <table 70>,
      [4120348526] = <table 140>,
      [4120424248] = <table 22>,
      [4208707305] = <table 64>,
      [4250243849] = <table 9>
    },
    quest_block = {}
  },
  seq_canMissionStartWaitStartTime = 30.1300394,
  seq_currentSequence = "Seq_Game_MainGame",
  seq_demoSequneceList = {
    [2] = true,
    [19] = true,
    [20] = true,
    [26] = true,
    [27] = true,
    [28] = true,
    [29] = true,
    [30] = true
  },
  seq_heliStartSequence = 3,
  seq_isHelicopterStart = false,
  seq_missionPrepareState = 7,
  seq_missionStartSequence = 2,
  seq_onEndMissionPrepareFunction = <function 95>,
  seq_sequenceNames = { "Seq_Mission_Prepare", "Seq_Demo_StartHasTitleMission", "Seq_Game_PushStart", "Seq_Game_TitleMenu", "Seq_Game_ChunkLoading", "Seq_Game_ChunkCanceled", "Seq_Game_ChunkInstalled", "Seq_Game_MainGame", "Seq_Game_MainGameToMissionPreparationTop", "Seq_Game_MissionPreparationTop", "Seq_Game_MissionPreparation_SelectItem", "Seq_Game_MissionPreparation_SelectSlot", "Seq_Game_MissionPreparation_SelectDetail", "Seq_Game_MissionPreparationAbort", "Seq_Game_MissionPreparationEnd", "Seq_Game_WeaponCustomize", "Seq_Game_WeaponCustomizeAbort", "Seq_Game_WeaponCustomizeEnd", "Seq_Demo_LoadAvatarEdit", "Seq_Demo_WaitReadyAvatarEdit", "Seq_Game_AvatarEdit", "Seq_Game_AvatarEditEnd", "Seq_Game_PandemicTutorial", "Seq_Game_TutorialIntroductionFobConstruct", "Seq_Game_TutorialFobConstruct", "Seq_Demo_PS3Store", "Seq_Demo_CheckDlc", "Seq_Demo_ShowDlcError", "Seq_Demo_ShowDlcAnnouncePopup", "Seq_Demo_WaitSavingPersonalData",
    Seq_Demo_CheckDlc = 27,
    Seq_Demo_LoadAvatarEdit = 19,
    Seq_Demo_PS3Store = 26,
    Seq_Demo_ShowDlcAnnouncePopup = 29,
    Seq_Demo_ShowDlcError = 28,
    Seq_Demo_StartHasTitleMission = 2,
    Seq_Demo_WaitReadyAvatarEdit = 20,
    Seq_Demo_WaitSavingPersonalData = 30,
    Seq_Game_AvatarEdit = 21,
    Seq_Game_AvatarEditEnd = 22,
    Seq_Game_ChunkCanceled = 6,
    Seq_Game_ChunkInstalled = 7,
    Seq_Game_ChunkLoading = 5,
    Seq_Game_MainGame = 8,
    Seq_Game_MainGameToMissionPreparationTop = 9,
    Seq_Game_MissionPreparationAbort = 14,
    Seq_Game_MissionPreparationEnd = 15,
    Seq_Game_MissionPreparationTop = 10,
    Seq_Game_MissionPreparation_SelectDetail = 13,
    Seq_Game_MissionPreparation_SelectItem = 11,
    Seq_Game_MissionPreparation_SelectSlot = 12,
    Seq_Game_PandemicTutorial = 23,
    Seq_Game_PushStart = 3,
    Seq_Game_TitleMenu = 4,
    Seq_Game_TutorialFobConstruct = 25,
    Seq_Game_TutorialIntroductionFobConstruct = 24,
    Seq_Game_WeaponCustomize = 16,
    Seq_Game_WeaponCustomizeAbort = 17,
    Seq_Game_WeaponCustomizeEnd = 18,
    Seq_Mission_Prepare = 1
  },
  seq_sequenceTable = {
    Seq_Demo_CheckDlc = {
      OnEnter = <function 132>,
      OnUpdate = <function 133>
    },
    Seq_Demo_LoadAvatarEdit = {
      OnEnter = <function 134>
    },
    Seq_Demo_PS3Store = {
      Messages = <function 135>,
      OnEnter = <function 136>,
      OnLeave = <function 137>,
      _messageExecTable = {
        [3105039150] = {
          [618616991] = {
            func = <function 138>
          }
        }
      }
    },
    Seq_Demo_ShowDlcAnnouncePopup = {
      Messages = <function 139>,
      OnEnter = <function 140>,
      OnLeave = <function 141>,
      OnUpdate = <function 142>,
      _messageExecTable = {
        [3105039150] = {
          [2244256200] = {
            func = <function 143>
          }
        }
      }
    },
    Seq_Demo_ShowDlcError = {
      OnEnter = <function 144>
    },
    Seq_Demo_StartHasTitleMission = {
      Messages = <function 145>,
      OnEndShowSplashScreen = <function 146>,
      OnLeave = <function 147>,
      OnUpdate = <function 148>,
      _messageExecTable = {
        [3105039150] = {
          [244265405] = {
            sender = {
              [965318480] = <function 149>
            },
            senderOption = {}
          },
          [682637859] = {
            func = <function 150>
          },
          [1500853894] = {
            func = <function 151>
          },
          [2245450426] = {
            sender = {
              [3261117285] = <function 152>
            },
            senderOption = {}
          },
          [3261117285] = {
            func = <function 153>
          }
        }
      }
    },
    Seq_Demo_WaitReadyAvatarEdit = {
      OnEnter = <function 154>,
      OnUpdate = <function 155>
    },
    Seq_Demo_WaitSavingPersonalData = {
      OnEnter = <function 156>,
      OnUpdate = <function 157>
    },
    Seq_Game_AvatarEdit = {
      Messages = <function 158>,
      OnEnter = <function 159>,
      _messageExecTable = {
        [3105039150] = {
          [190754301] = {
            func = <function 160>
          },
          [824988796] = {
            sender = {
              [2260235480] = <function 161>
            },
            senderOption = {}
          }
        }
      }
    },
    Seq_Game_AvatarEditEnd = {
      OnEnter = <function 162>
    },
    Seq_Game_ChunkCanceled = {
      Messages = <function 163>,
      OnEnter = <function 164>,
      _messageExecTable = {
        [3105039150] = {
          [2566099212] = {
            sender = {
              [7004] = <function 165>
            },
            senderOption = {}
          }
        }
      }
    },
    Seq_Game_ChunkInstalled = {
      Messages = <function 166>,
      OnEndFadeOutSelectContinue = <function 167>,
      OnEndFadeSelectGameStart = <function 168>,
      OnEndFadeSelectMGO = <function 169>,
      OnEnter = <function 170>,
      OnLeave = <function 171>,
      OnSelectContinue = <function 172>,
      OnSelectGameStart = <function 173>,
      OnSelectMGO = <function 174>,
      OnSelectRestartHeli = <function 175>,
      OnUpdate = <function 176>,
      OnUpdateForNewGameLoad = <function 177>,
      OnUpdateSelectMGO = <function 178>,
      _messageExecTable = {
        [3105039150] = {
          [824988796] = {
            sender = {
              [2004033248] = <function 168>,
              [2437061876] = <function 169>,
              [3210797601] = <function 167>
            },
            senderOption = {}
          }
        }
      }
    },
    Seq_Game_ChunkLoading = {
      GetChunkIndex = <function 179>,
      Messages = <function 180>,
      OnEnter = <function 181>,
      OnLeave = <function 182>,
      OnUpdate = <function 183>,
      _messageExecTable = {
        [3105039150] = {
          [2566099212] = {
            sender = {
              [7003] = <function 184>
            },
            senderOption = {}
          }
        }
      },
      chunkIndex = 3
    },
    Seq_Game_MainGame = {
      FinishMissionListGuidance = <function 185>,
      Messages = <function 186>,
      OnEnter = <function 187>,
      OnLeave = <function 188>,
      StartMissionListGuidance = <function 189>,
      StartPandemicTutorialSequence = <function 190>,
      _messageExecTable = {
        [626208720] = {
          [1201378849] = {
            func = <function 100>
          }
        },
        [2612012156] = {
          [1348967482] = {
            func = <function 124>
          },
          [2507861236] = {
            func = <function 125>
          }
        },
        [3105039150] = {
          [244265405] = {
            sender = {
              [2778285041] = <function 191>
            },
            senderOption = {}
          },
          [353985795] = {
            func = <function 111>
          },
          [824988796] = {
            sender = {
              [455681386] = <function 92>,
              [2020326295] = <function 94>,
              [2353634780] = <function 192>,
              [3565063921] = <function 193>
            },
            senderOption = {}
          },
          [1916842388] = {
            func = <function 112>
          },
          [3018079696] = {
            func = <function 194>
          }
        },
        [3333891920] = {
          [2622293891] = {
            func = <function 123>
          }
        },
        [3380938768] = {
          [3709244990] = {
            sender = {
              [3606228666] = <function 123>
            },
            senderOption = {}
          }
        },
        [4113713594] = {
          [3709244990] = {
            func = <function 195>,
            sender = {
              [862208655] = <function 185>,
              [1808171662] = <function 190>
            },
            senderOption = {}
          }
        },
        [4133365783] = {
          [501943985] = {
            func = <function 196>
          },
          [901759391] = {
            func = <function 197>
          },
          [1090157592] = {
            func = <function 198>
          },
          [1378767181] = {
            func = <function 199>
          },
          [1875204800] = {
            func = <function 99>
          }
        }
      }
    },
    Seq_Game_MainGameToMissionPreparationTop = {
      Messages = <function 200>,
      OnEnter = <function 201>,
      OnLeave = <function 202>,
      _messageExecTable = {
        [3380938768] = {
          [3709244990] = {
            sender = {
              [2891404869] = <function 203>
            },
            senderOption = {}
          }
        }
      }
    },
    Seq_Game_MissionPreparationAbort = {
      Messages = <function 204>,
      OnEnter = <function 205>,
      OnLeave = <function 206>,
      OnUpdate = <function 207>,
      _messageExecTable = {
        [3105039150] = {
          [244265405] = {
            sender = {
              [236857777] = <function 208>
            },
            senderOption = {}
          }
        }
      }
    },
    Seq_Game_MissionPreparationEnd = {
      Messages = <function 209>,
      OnEnter = <function 210>,
      OnUpdate = <function 211>,
      _messageExecTable = {
        [3380938768] = {
          [3709244990] = {
            sender = {
              [2354100347] = <function 212>
            },
            senderOption = {}
          }
        }
      }
    },
    Seq_Game_MissionPreparationTop = {
      Messages = <function 213>,
      MissionPreparationCamera = <function 214>,
      OnEnter = <function 215>,
      OnLeave = <function 216>,
      _messageExecTable = {
        [3105039150] = {
          [244265405] = {
            sender = {
              [3515316815] = <function 217>
            },
            senderOption = {}
          },
          [824988796] = {
            sender = {
              [236857777] = <function 218>
            },
            senderOption = {}
          },
          [1976519535] = {
            func = <function 219>,
            option = {
              [2357387275] = true
            }
          },
          [3191390926] = {
            func = <function 220>,
            option = {
              [2357387275] = true
            }
          },
          [4099221502] = {
            func = <function 221>
          }
        }
      }
    },
    Seq_Game_MissionPreparation_SelectDetail = {
      Messages = <function 222>,
      OnEnter = <function 223>,
      OnLeave = <function 224>,
      _messageExecTable = {
        [3105039150] = {
          [824988796] = {
            sender = {
              [236857777] = <function 225>,
              [4214309259] = <function 93>
            },
            senderOption = {}
          },
          [1976519535] = {
            func = <function 97>,
            option = {
              [2357387275] = true
            }
          },
          [2728652853] = {
            func = <function 226>,
            option = {
              [2357387275] = true
            }
          },
          [3191390926] = {
            func = <function 90>,
            option = {
              [2357387275] = true
            }
          },
          [3305868447] = {
            func = <function 227>,
            option = {
              [2357387275] = true
            }
          }
        }
      }
    },
    Seq_Game_MissionPreparation_SelectItem = {
      Messages = <function 228>,
      OnEnter = <function 229>,
      OnLeave = <function 230>,
      _messageExecTable = {
        [3105039150] = {
          [173612413] = {
            func = <function 231>
          },
          [824988796] = {
            sender = {
              [236857777] = <function 232>,
              [4214309259] = <function 93>
            },
            senderOption = {}
          },
          [1160928321] = {
            func = <function 233>,
            option = {
              [2357387275] = true
            }
          },
          [1283061727] = {
            func = <function 234>,
            option = {
              [2357387275] = true
            }
          },
          [1976519535] = {
            func = <function 97>,
            option = {
              [2357387275] = true
            }
          },
          [2277994252] = {
            func = <function 235>,
            option = {
              [2357387275] = true
            }
          },
          [2417945394] = {
            func = <function 236>
          },
          [2623745045] = {
            func = <function 237>,
            option = {
              [2357387275] = true
            }
          },
          [2728652853] = {
            func = <function 238>,
            option = {
              [2357387275] = true
            }
          },
          [3143739147] = {
            func = <function 239>,
            option = {
              [2357387275] = true
            }
          },
          [3191390926] = {
            func = <function 90>,
            option = {
              [2357387275] = true
            }
          },
          [3305868447] = {
            func = <function 240>,
            option = {
              [2357387275] = true
            }
          }
        },
        [3380938768] = {
          [3709244990] = {
            sender = {
              [950810738] = <function 241>
            },
            senderOption = {}
          }
        }
      }
    },
    Seq_Game_MissionPreparation_SelectSlot = {
      Messages = <function 242>,
      OnEnter = <function 243>,
      OnLeave = <function 244>,
      _messageExecTable = {
        [3105039150] = {
          [824988796] = {
            sender = {
              [236857777] = <function 245>,
              [4214309259] = <function 93>
            },
            senderOption = {}
          },
          [1283061727] = {
            func = <function 246>,
            option = {
              [2357387275] = true
            }
          },
          [1976519535] = {
            func = <function 247>,
            option = {
              [2357387275] = true
            }
          },
          [2728652853] = {
            func = <function 248>,
            option = {
              [2357387275] = true
            }
          },
          [3191390926] = {
            func = <function 97>,
            option = {
              [2357387275] = true
            }
          },
          [3658704845] = {
            func = <function 249>,
            option = {
              [2357387275] = true
            }
          }
        }
      }
    },
    Seq_Game_PandemicTutorial = {
      Messages = <function 250>,
      OnEnter = <function 251>,
      OnLeave = <function 252>,
      _messageExecTable = {
        [626208720] = {
          [2189796805] = {
            func = <function 253>
          }
        },
        [2612012156] = {
          [1348967482] = {
            func = <function 124>
          },
          [2507861236] = {
            func = <function 125>
          }
        },
        [3105039150] = {
          [244265405] = {
            sender = {
              [2778285041] = <function 191>
            },
            senderOption = {}
          },
          [353985795] = {
            func = <function 111>
          },
          [824988796] = {
            sender = {
              [455681386] = <function 92>
            },
            senderOption = {}
          },
          [1916842388] = {
            func = <function 112>
          }
        },
        [3333891920] = {
          [2622293891] = {
            func = <function 123>
          }
        },
        [3380938768] = {
          [3709244990] = {
            sender = {
              [3606228666] = <function 123>
            },
            senderOption = {}
          }
        },
        [4133365783] = {
          [1204716134] = {
            func = <function 254>
          },
          [1378767181] = {
            func = <function 255>
          },
          [2878679236] = {
            func = <function 256>
          }
        }
      }
    },
    Seq_Game_PushStart = {
      Messages = <function 257>,
      OnEnter = <function 258>,
      OnLeave = <function 259>,
      OnUpdate = <function 260>,
      StartTitleMenu = <function 261>,
      StartTitleMenuWithNoSavedData = <function 262>,
      _messageExecTable = {
        [3105039150] = {
          [2566099212] = {
            func = <function 263>
          }
        }
      }
    },
    Seq_Game_TitleMenu = {
      Messages = <function 264>,
      OnEnter = <function 265>,
      OnLeave = <function 266>,
      OnSelectContinue = <function 267>,
      OnSelectGameStart = <function 268>,
      OnSelectMGO = <function 269>,
      OnSelectRestartHeli = <function 270>,
      _messageExecTable = {
        [3105039150] = {
          [1091517230] = {
            func = <function 271>
          },
          [1439467306] = {
            func = <function 267>
          },
          [2004033248] = {
            func = <function 268>
          },
          [2245450426] = {
            sender = {
              [1439467306] = <function 267>,
              [2004033248] = <function 268>,
              [2664134208] = <function 270>
            },
            senderOption = {}
          },
          [2805952977] = {
            func = <function 269>
          }
        }
      }
    },
    Seq_Game_TutorialFobConstruct = {
      Messages = <function 272>,
      OnEnter = <function 273>,
      OnLeave = <function 274>,
      _messageExecTable = {
        [2612012156] = {
          [1348967482] = {
            func = <function 124>
          },
          [2507861236] = {
            func = <function 125>
          }
        },
        [3105039150] = {
          [244265405] = {
            sender = {
              [2778285041] = <function 191>
            },
            senderOption = {}
          },
          [353985795] = {
            func = <function 111>
          },
          [824988796] = {
            sender = {
              [455681386] = <function 92>
            },
            senderOption = {}
          },
          [1916842388] = {
            func = <function 112>
          }
        },
        [3333891920] = {
          [2622293891] = {
            func = <function 123>
          }
        },
        [3380938768] = {
          [3709244990] = {
            sender = {
              [3606228666] = <function 123>
            },
            senderOption = {}
          }
        },
        [4133365783] = {
          [1670401158] = {
            sender = {
              [457695265] = <function 275>,
              [2250564499] = <function 276>
            },
            senderOption = {}
          }
        }
      }
    },
    Seq_Game_TutorialIntroductionFobConstruct = {
      Messages = <function 277>,
      OnEnter = <function 278>,
      OnLeave = <function 279>,
      _messageExecTable = {
        [2612012156] = {
          [1348967482] = {
            func = <function 124>
          },
          [2507861236] = {
            func = <function 125>
          }
        },
        [3105039150] = {
          [244265405] = {
            sender = {
              [2778285041] = <function 191>
            },
            senderOption = {}
          },
          [353985795] = {
            func = <function 111>
          },
          [824988796] = {
            sender = {
              [455681386] = <function 92>
            },
            senderOption = {}
          },
          [1916842388] = {
            func = <function 112>
          }
        },
        [3333891920] = {
          [2622293891] = {
            func = <function 123>
          }
        },
        [3380938768] = {
          [3709244990] = {
            sender = {
              [3606228666] = <function 123>
            },
            senderOption = {}
          }
        },
        [4113713594] = {
          [3709244990] = {
            sender = {
              [1089806375] = <function 280>
            },
            senderOption = {}
          }
        }
      }
    },
    Seq_Game_WeaponCustomize = {
      Messages = <function 281>,
      OnEnter = <function 282>,
      OnLeave = <function 283>,
      _messageExecTable = {
        [3105039150] = {
          [244265405] = {
            sender = {
              [1432538151] = <function 284>
            },
            senderOption = {}
          },
          [768076095] = {
            func = <function 285>,
            option = {
              [2357387275] = true
            }
          },
          [824988796] = {
            sender = {
              [589162941] = <function 286>,
              [2903254609] = <function 287>
            },
            senderOption = {}
          },
          [1150862361] = {
            func = <function 288>,
            option = {
              [2357387275] = true
            }
          },
          [3576894342] = {
            func = <function 289>,
            option = {
              [2357387275] = true
            }
          }
        }
      }
    },
    Seq_Game_WeaponCustomizeAbort = {
      Messages = <function 290>,
      OnEnter = <function 291>,
      _messageExecTable = {
        [3105039150] = {
          [244265405] = {
            sender = {
              [589162941] = <function 292>
            },
            senderOption = {}
          }
        }
      }
    },
    Seq_Game_WeaponCustomizeEnd = {
      Messages = <function 293>,
      OnEnter = <function 294>,
      _messageExecTable = {
        [3105039150] = {
          [244265405] = {
            sender = {
              [2903254609] = <function 295>
            },
            senderOption = {}
          }
        }
      }
    },
    Seq_Mission_Prepare = {
      DEBUG_TextPrint = <function 296>,
      FadeInStartOnGameStart = <function 297>,
      HelicopterMoveStart = <function 298>,
      Messages = <function 299>,
      MissionGameStart = <function 300>,
      OnEnter = <function 301>,
      OnLeave = <function 302>,
      OnUpdate = <function 303>,
      SkipTextureLoadingWait = <function 304>,
      _messageExecTable = {
        [3105039150] = {
          [244265405] = {
            sender = {
              [2813368222] = <function 305>
            },
            senderOption = {
              [2813368222] = {
                [1575448960] = true,
                [2357387275] = true,
                [4282425663] = true
              }
            }
          },
          [1143494975] = {
            func = <function 306>,
            option = {
              [1575448960] = true,
              [2357387275] = true,
              [4282425663] = true
            }
          },
          [2461393688] = {
            func = <function 307>,
            option = {
              [1575448960] = true,
              [2357387275] = true,
              [4282425663] = true
            }
          },
          [2874760715] = {
            func = <function 308>,
            option = {
              [1575448960] = true,
              [2357387275] = true,
              [4282425663] = true
            }
          }
        },
        [3380938768] = {
          [3709244990] = {
            sender = {
              [2904893317] = <function 297>,
              [3148858291] = <function 298>,
              [4175515318] = <function 300>
            },
            senderOption = {
              [2904893317] = {
                [1575448960] = true,
                [2357387275] = true,
                [4282425663] = true
              },
              [3148858291] = {
                [1575448960] = true,
                [2357387275] = true,
                [4282425663] = true
              },
              [4175515318] = {
                [1575448960] = true,
                [2357387275] = true,
                [4282425663] = true
              }
            }
          }
        }
      }
    }
  },
  seq_textureLoadWaitStartTime = 40.1233361,
  snd_finishHeliClearJingleName = "Stop_bgm_mission_clear_heli",
  snd_startHeliClearJingleName = "Play_bgm_mission_clear_heli",
  startHasTitileSeqeunce = true,
  startHasTitleSeqeunceMbSyc = true,
  title_disableGameStatusFunction = <function 83>,
  title_enableGameStatusFunction = <function 85>,
  title_hideTitleMenuOnInitialize = false,
  title_missionGameSequenceName = "Seq_Game_MainGame",
  title_selectFlag = 1,
  title_titleModeOnEnterFunction = <function 126>,
  tlp_enemyCombatants = {},
  tlp_guestCharacters = {},
  tlp_levelDesigners = { "staff_tsuyoshi_osada", "staff_satoshi_matsuno" },
  tlp_mainCharacters = { "cast_venom_snake", "cast_sharashka_ocelot", "cast_kazuhira_miller" },
  tlp_specialMechanics = {},
  tlp_writers = { "staff_shuyo_murata" },
  trm_EmblemLocatorIdTable = {
    [2423121] = "front9",
    [2538470] = "front10",
    [4357176] = "front16",
    [5851632] = "front7",
    [6197125] = "front15",
    [10225934] = "front8",
    [11572941] = "front11"
  },
  trm_bluePrintLocatorIdTable = {
    [268918] = 38,
    [594485] = 39,
    [598891] = 34,
    [1041755] = 43,
    [1908443] = 34,
    [2753472] = 37,
    [3145470] = 34,
    [3652642] = 26,
    [3835797] = 34,
    [4009396] = 42,
    [4088341] = 37,
    [4741030] = 27,
    [4970370] = 25,
    [5039367] = 439,
    [5509624] = 24,
    [5591297] = 37,
    [6810011] = 40,
    [6929828] = 41,
    [8397929] = 44,
    [10252721] = 46,
    [10904403] = 33,
    [11023056] = 29,
    [11180997] = 37,
    [11479983] = 29,
    [11519767] = 29,
    [13222182] = 29,
    [14317601] = 31,
    [14540460] = 21,
    [14938090] = 25,
    [15166830] = 31
  },
  trm_fultonInfo = {},
  trm_stopChangeDayTerminalAnnounce = true,
  trm_voiceDisabled = false,
  ui_onEndFadeInOverrideExceptGameStatusTemporary = {
    ActionIcon = false,
    AnnounceLog = false,
    AtTime = false,
    BaseName = false,
    CallMenu = false,
    CqcIcon = false,
    Damage = false,
    EquipHud = false,
    EquipPanel = false,
    GmpInfo = false,
    HeadMarker = false,
    HudText = false,
    InfoTypingText = false,
    Notice = false,
    PauseMenu = false,
    S_DISABLE_NPC = false,
    S_DISABLE_NPC_NOTICE = false,
    S_DISABLE_PLACEMENT = false,
    S_DISABLE_PLAYER_DAMAGE = false,
    S_DISABLE_PLAYER_PAD = false,
    S_DISABLE_TARGET = false,
    S_DISABLE_THROWING = false,
    WorldMarker = false
  }
}
return this