mbdvc_map_location_parameter={
  GetLocationParameter=function(a)
    if a==10 then
      return{stageSize=4096*2,scrollMaxLeftUpPosition=Vector3(-4096,0,-4096),scrollMaxRightDownPosition=Vector3(4096,0,4096),stageRotate=-45,highZoomScale=14.4,middleZoomScale=3,lowZoomScale=1,naviHighZoomScale=14.4,naviMiddleZoomScale=5,locationNameLangId="tpp_loc_afghan",heightMapTexturePath="/Assets/tpp/ui/texture/map/map_afgh/afgh_height_clp_alp.ftex",heightMapTexturePath2="/Assets/tpp/ui/texture/map/map_afgh/afgh_height_b_clp_alp.ftex",heightMapTexturePath3="/Assets/tpp/ui/texture/map/map_afgh/afgh_height_c_clp_alp.ftex",photoRealMapTexturePath="/Assets/tpp/ui/texture/map/map_afgh/afgh_photo_clp_alp.ftex",divideHeightMapTexturePath="/Assets/tpp/ui/texture/map/map_afgh/height_divide/afgh_hgt_dv_%02d_%02d_clp_alp.ftex",divideHeightMapTexturePath2="/Assets/tpp/ui/texture/map/map_afgh/height_divide/afgh_hgt_b_dv_%02d_%02d_clp_alp.ftex",divideHeightMapTexturePath3="/Assets/tpp/ui/texture/map/map_afgh/height_divide/afgh_hgt_c_dv_%02d_%02d_clp_alp.ftex",dividePhotoRealMapTexturePath="/Assets/tpp/ui/texture/map/map_afgh/photo_divide/afgh_pht_dv_%02d_%02d_clp_alp.ftex",uniqueTownTexturePath="/Assets/tpp/ui/texture/map/building_icon/mb_map_bild_icon_afgh_alp_clp.ftex",commonTownTexturePath="/Assets/tpp/ui/texture/map/building_icon/mb_map_bild_icon_cmn_alp_clp.ftex",sectionFuncRankForHeightMap2=3,sectionFuncRankForHeightMap3=5,townParameter={{cpName="",langId="tpp_afghan_en_ruins",cursorLangId="tpp_afghan_ruins",position=Vector3(1459,0,1478.4),radius=75,uShift=.25,vShift=.5,mini=false},
        {cpName="afgh_village_cp",langId="tpp_afghan_en_village",cursorLangId="tpp_afghan_village",position=Vector3(512.3,0,1152.3),radius=200,uShift=.25,vShift=.75,mini=false},
        {cpName="afgh_commFacility_cp",langId="tpp_afghan_en_commFacility",cursorLangId="tpp_afghan_commFacility",position=Vector3(1505.4,0,449.4),radius=200,uShift=.75,vShift=0,mini=false},
        {cpName="afgh_slopedTown_cp",langId="tpp_afghan_en_slopedTown",cursorLangId="tpp_afghan_slopedTown",position=Vector3(511.2,0,64.9),radius=200,uShift=.5,vShift=.5,mini=false},
        {cpName="afgh_enemyBase_cp",langId="tpp_afghan_en_enemyBase",cursorLangId="tpp_afghan_enemyBase",position=Vector3(-569.3,0,518.8),radius=200,uShift=0,vShift=.25,mini=false},
        {cpName="afgh_cliffTown_cp",langId="tpp_afghan_en_cliffTown",cursorLangId="tpp_afghan_cliffTown",position=Vector3(798,0,-1006),radius=200,uShift=.5,vShift=0,mini=false},
        {cpName="afgh_bridge_cp",langId="tpp_afghan_en_bridge",cursorLangId="tpp_afghan_bridge",position=Vector3(1922.2,0,-478.2),radius=200,uShift=0,vShift=0,mini=false},
        {cpName="afgh_remnants_cp",langId="tpp_afghan_en_remnant",cursorLangId="tpp_afghan_remnant",position=Vector3(-782.5,0,1893.8),radius=200,uShift=0,vShift=.5,mini=false},
        {cpName="afgh_tent_cp",langId="tpp_afghan_en_tent",cursorLangId="tpp_afghan_tent",position=Vector3(-1745,0,838),radius=200,uShift=0,vShift=.75,mini=false},
        {cpName="",langId="tpp_afghan_en_waterway",cursorLangId="tpp_afghan_waterway",position=Vector3(-1702.1,0,-397.1),radius=200,uShift=.5,vShift=.75,mini=false},
        {cpName="afgh_powerPlant_cp",langId="tpp_afghan_en_powerPlant",cursorLangId="tpp_afghan_powerPlant",position=Vector3(-712.3,0,-1532.4),radius=300,uShift=.75,vShift=.25,mini=false},
        {cpName="afgh_field_cp",langId="tpp_afghan_en_field",cursorLangId="tpp_afghan_field",position=Vector3(393,0,2150),radius=200,uShift=.25,vShift=.25,mini=false},
        {cpName="afgh_fort_cp",langId="tpp_afghan_en_fort",cursorLangId="tpp_afghan_fort",position=Vector3(2107,0,-1744),radius=300,uShift=.5,vShift=.25,mini=false},
        {cpName="afgh_sovietBase_cp",langId="tpp_afghan_en_sovietBase",cursorLangId="tpp_afghan_sovietBase",position=Vector3(-2209,0,-1573),radius=300,uShift=.75,vShift=.5,mini=false},
        {cpName="afgh_citadel_cp",langId="tpp_afghan_en_citadel",cursorLangId="tpp_afghan_citadel",position=Vector3(-1236,0,-3e3),radius=300,uShift=.25,vShift=0,mini=false},
        {cpName="afgh_commWest_ob",langId="tpp_afghan_commWest_no",cursorLangId="tpp_afghan_commWest",position=Vector3(990.7,0,658.6),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="afgh_villageWest_ob",langId="tpp_afghan_villageWest_no",cursorLangId="tpp_afghan_villageWest",position=Vector3(-249,0,930),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="afgh_ruinsNorth_ob",langId="tpp_afghan_ruinsNorth_no",cursorLangId="tpp_afghan_ruinsNorth",position=Vector3(1630.6,0,1056.2),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="afgh_villageNorth_ob",langId="tpp_afghan_villageNorth_no",cursorLangId="tpp_afghan_villageNorth",position=Vector3(506,0,703),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="afgh_slopedWest_ob",langId="tpp_afghan_slopedWest_no",cursorLangId="tpp_afghan_slopedWest",position=Vector3(100,0,88.4),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="afgh_fieldEast_ob",langId="tpp_afghan_fieldEast_no",cursorLangId="tpp_afghan_fieldEast",position=Vector3(1096.3,0,1833.1),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="afgh_fieldWest_ob",langId="tpp_afghan_fieldWest_no",cursorLangId="tpp_afghan_fieldWest",position=Vector3(10.5,0,1994),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="afgh_remnantsNorth_ob",langId="tpp_afghan_remnantsNorth_no",cursorLangId="tpp_afghan_remnantsNorth",position=Vector3(-1056.3,0,1471.2),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="afgh_tentNorth_ob",langId="tpp_afghan_tentNorth_no",cursorLangId="tpp_afghan_tentNorth",position=Vector3(-1756.6,0,214),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="afgh_slopedEast_ob",langId="tpp_afghan_slopedEast_no",cursorLangId="tpp_afghan_slopedEast",position=Vector3(966,0,-169),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="afgh_villageEast_ob",langId="tpp_afghan_villageEast_no",cursorLangId="tpp_afghan_villageEast",position=Vector3(1048,0,1273),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="afgh_bridgeWest_ob",langId="tpp_afghan_bridgeWest_no",cursorLangId="tpp_afghan_bridgeWest",position=Vector3(1593.2,0,43.3),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="afgh_fortSouth_ob",langId="tpp_afghan_fortSouth_no",cursorLangId="tpp_afghan_fortSouth",position=Vector3(2184.8,0,-1268.3),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="afgh_fortWest_ob",langId="tpp_afghan_fortWest_no",cursorLangId="tpp_afghan_fortWest",position=Vector3(1825.5,0,-1249.7),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="afgh_cliffEast_ob",langId="tpp_afghan_cliffEast_no",cursorLangId="tpp_afghan_cliffEast",position=Vector3(1259,0,-1347.4),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="afgh_cliffSouth_ob",langId="tpp_afghan_cliffSouth_no",cursorLangId="tpp_afghan_cliffSouth",position=Vector3(1046,0,-507),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="afgh_enemyNorth_ob",langId="tpp_afghan_enemyNorth_no",cursorLangId="tpp_afghan_enemyNorth",position=Vector3(-183,0,-466),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="afgh_bridgeNorth_ob",langId="tpp_afghan_bridgeNorth_no",cursorLangId="tpp_afghan_bridgeNorth",position=Vector3(2395.6,0,-507.6),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="afgh_cliffWest_ob",langId="tpp_afghan_cliffWest_no",cursorLangId="tpp_afghan_cliffWest",position=Vector3(299.7,0,-851.1),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="afgh_enemyEast_ob",langId="tpp_afghan_enemyEast_no",cursorLangId="tpp_afghan_enemyEast",position=Vector3(-367,0,120.5),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="afgh_tentEast_ob",langId="tpp_afghan_tentEast_no",cursorLangId="tpp_afghan_tentEast",position=Vector3(-1169.5,0,934.4),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="afgh_sovietSouth_ob",langId="tpp_afghan_sovietSouth_no",cursorLangId="tpp_afghan_sovietSouth",position=Vector3(-1582,0,-1151),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="afgh_plantWest_ob",langId="tpp_afghan_plantWest_no",cursorLangId="tpp_afghan_plantWest",position=Vector3(-1172.4,0,-1405.1),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="afgh_waterwayEast_ob",langId="tpp_afghan_waterWayEast_no",cursorLangId="tpp_afghan_waterWayEast",position=Vector3(-1328.3,0,-741.7),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="afgh_citadelSouth_ob",langId="tpp_afghan_CitadelSouth_no",cursorLangId="tpp_afghan_CitadelSouth",position=Vector3(-1668,0,-2441),radius=75,uShift=0,vShift=0,mini=true}}}
    elseif a==15 then
      return{stageSize=4096*2,scrollMaxLeftUpPosition=Vector3(-4096,0,-4096),scrollMaxRightDownPosition=Vector3(4096,0,4096),stageRotate=-45,highZoomScale=14.4,middleZoomScale=3,lowZoomScale=1,naviHighZoomScale=14.4,naviMiddleZoomScale=5,locationNameLangId="tpp_loc_afghan",heightMapTexturePath="/Assets/ssd/ui/texture/map/stage_01_height_clp_alp.ftex",heightMapTexturePath2="/Assets/ssd/ui/texture/map/stage_01_height_clp_alp.ftex",heightMapTexturePath3="/Assets/ssd/ui/texture/map/stage_01_height_clp_alp.ftex",photoRealMapTexturePath="/Assets/tpp/ui/texture/map/map_afgh/afgh_photo_clp_alp.ftex",divideHeightMapTexturePath="/Assets/tpp/ui/texture/map/map_afgh/height_divide/afgh_hgt_dv_%02d_%02d_clp_alp.ftex",divideHeightMapTexturePath2="/Assets/tpp/ui/texture/map/map_afgh/height_divide/afgh_hgt_b_dv_%02d_%02d_clp_alp.ftex",divideHeightMapTexturePath3="/Assets/tpp/ui/texture/map/map_afgh/height_divide/afgh_hgt_c_dv_%02d_%02d_clp_alp.ftex",dividePhotoRealMapTexturePath="/Assets/tpp/ui/texture/map/map_afgh/photo_divide/afgh_pht_dv_%02d_%02d_clp_alp.ftex",uniqueTownTexturePath="/Assets/tpp/ui/texture/map/building_icon/mb_map_bild_icon_afgh_alp_clp.ftex",commonTownTexturePath="/Assets/tpp/ui/texture/map/building_icon/mb_map_bild_icon_cmn_alp_clp.ftex",sectionFuncRankForHeightMap2=3,sectionFuncRankForHeightMap3=5,townParameter={{cpName="cp_base",langId="",cursorLangId="tpp_loc_mb",position=Vector3(-317,288,2112),radius=23,uShift=.25,vShift=.75,mini=false},
        {cpName="afgh_field_cp",langId="",cursorLangId="",position=Vector3(393,0,2150),radius=200,uShift=.25,vShift=.25,mini=true}}}
    elseif a==20 then
      return{stageSize=4096*2,scrollMaxLeftUpPosition=Vector3(-4096,0,-3804),scrollMaxRightDownPosition=Vector3(1884,0,2172),stageRotate=-45,highZoomScale=14.4,middleZoomScale=3,lowZoomScale=1,naviHighZoomScale=14.4,naviMiddleZoomScale=5,locationNameLangId="tpp_loc_africa",heightMapTexturePath="/Assets/tpp/ui/texture/map/map_mafr/mafr_height_clp_alp.ftex",heightMapTexturePath2="/Assets/tpp/ui/texture/map/map_mafr/mafr_height_b_clp_alp.ftex",heightMapTexturePath3="/Assets/tpp/ui/texture/map/map_mafr/mafr_height_c_clp_alp.ftex",photoRealMapTexturePath="/Assets/tpp/ui/texture/map/map_mafr/mafr_photo_clp_alp.ftex",divideHeightMapTexturePath="/Assets/tpp/ui/texture/map/map_mafr/height_divide/mafr_hgt_dv_%02d_%02d_clp_alp.ftex",divideHeightMapTexturePath2="/Assets/tpp/ui/texture/map/map_mafr/height_divide/mafr_hgt_b_dv_%02d_%02d_clp_alp.ftex",divideHeightMapTexturePath3="/Assets/tpp/ui/texture/map/map_mafr/height_divide/mafr_hgt_c_dv_%02d_%02d_clp_alp.ftex",dividePhotoRealMapTexturePath="/Assets/tpp/ui/texture/map/map_mafr/photo_divide/mafr_pht_dv_%02d_%02d_clp_alp.ftex",uniqueTownTexturePath="/Assets/tpp/ui/texture/map/building_icon/mb_map_bild_icon_mafr_alp_clp.ftex",commonTownTexturePath="/Assets/tpp/ui/texture/map/building_icon/mb_map_bild_icon_cmn_alp_clp.ftex",sectionFuncRankForHeightMap2=5,sectionFuncRankForHeightMap3=7,townParameter={{cpName="mafr_swamp_cp",langId="tpp_africa_en_swamp",cursorLangId="tpp_africa_swamp",position=Vector3(-64.9,0,-.7),radius=200,uShift=.5,vShift=0,mini=false},
        {cpName="mafr_savannah_cp",langId="tpp_africa_en_savannah",cursorLangId="tpp_africa_savannah",position=Vector3(835,0,-130),radius=200,uShift=0,vShift=.25,mini=false},
        {cpName="mafr_banana_cp",langId="tpp_africa_en_banana",cursorLangId="tpp_africa_banana",position=Vector3(283.8,0,-1170.8),radius=200,uShift=.25,vShift=.25,mini=false},
        {cpName="mafr_diamond_cp",langId="tpp_africa_en_diamond",cursorLangId="tpp_africa_diamond",position=Vector3(1326.5,0,-1483),radius=300,uShift=.5,vShift=.25,mini=false},
        {cpName="mafr_factory_cp",langId="tpp_africa_en_factory",cursorLangId="tpp_africa_factory",position=Vector3(2837.5,0,-889.4),radius=300,uShift=0,vShift=.5,mini=false},
        {cpName="mafr_lab_cp",langId="tpp_africa_en_lab",cursorLangId="tpp_africa_lab",position=Vector3(2549.5,0,-2157.9),radius=300,uShift=.25,vShift=.5,mini=false},
        {cpName="mafr_flowStation_cp",langId="tpp_africa_en_flowstation",cursorLangId="tpp_africa_flowstation",position=Vector3(-1023,0,-226),radius=300,uShift=.25,vShift=0,mini=false},
        {cpName="mafr_outland_cp",langId="tpp_africa_en_outland",cursorLangId="tpp_africa_outland",position=Vector3(-615,0,1029),radius=200,uShift=0,vShift=0,mini=false},
        {cpName="mafr_hill_cp",langId="tpp_africa_en_hill",cursorLangId="tpp_africa_hill",position=Vector3(2165.6,0,388.5),radius=300,uShift=.75,vShift=.25,mini=false},
        {cpName="mafr_pfCamp_cp",langId="tpp_africa_en_pfcamp",cursorLangId="tpp_africa_pfcamp",position=Vector3(823,0,993),radius=300,uShift=.75,vShift=0,mini=false},
        {cpName="mafr_outlandNorth_ob",langId="tpp_africa_outlandNorth_no",cursorLangId="tpp_africa_outlandNorth",position=Vector3(-817.8,0,698),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="mafr_swampWest_ob",langId="tpp_africa_swampWest_no",cursorLangId="tpp_africa_swampWest",position=Vector3(-565,0,-188.4),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="mafr_outlandEast_ob",langId="tpp_africa_outlandEast_no",cursorLangId="tpp_africa_outlandEast",position=Vector3(-274,0,736),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="mafr_bananaSouth_ob",langId="tpp_africa_bananaSouth_no",cursorLangId="tpp_africa_bananaSouth",position=Vector3(233.1,0,-659.6),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="mafr_swampSouth_ob",langId="tpp_africa_swampSouth_no",cursorLangId="tpp_africa_swampSouth",position=Vector3(311.3,0,378.8),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="mafr_swampEast_ob",langId="tpp_africa_swampEast_no",cursorLangId="tpp_africa_swampEast",position=Vector3(367.5,0,0),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="mafr_savannahWest_ob",langId="tpp_africa_savannahWest_no",cursorLangId="tpp_africa_savannahWest",position=Vector3(713.2,0,-536.7),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="mafr_bananaEast_ob",langId="tpp_africa_bananaEast_no",cursorLangId="tpp_africa_bananaEast",position=Vector3(570.1,0,-1072.3),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="mafr_savannahNorth_ob",langId="tpp_africa_savannahNorth_no",cursorLangId="tpp_africa_savannahNorth",position=Vector3(711.5,0,-900),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="mafr_diamondWest_ob",langId="tpp_africa_diamondWest_no",cursorLangId="tpp_africa_diamondWest",position=Vector3(1086,0,-1151.5),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="mafr_diamondSouth_ob",langId="tpp_africa_diamondSouth_no",cursorLangId="tpp_africa_diamondSouth",position=Vector3(1451.8,0,-745),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="mafr_hillNorth_ob",langId="tpp_africa_hillNorth_no",cursorLangId="tpp_africa_hillNorth",position=Vector3(1941.5,0,-278.8),radius=200,uShift=0,vShift=0,mini=true},
        {cpName="mafr_hillSouth_ob",langId="tpp_africa_hillSouth_no",cursorLangId="tpp_africa_hillSouth",position=Vector3(2009.6,0,1370.1),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="mafr_savannahEast_ob",langId="tpp_africa_savannahEast_no",cursorLangId="tpp_africa_savannahEast",position=Vector3(1212,0,96.1),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="mafr_hillWest_ob",langId="tpp_africa_hillWest_no",cursorLangId="tpp_africa_hillWest",position=Vector3(1662.2,0,152),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="mafr_hillWestNear_ob",langId="tpp_africa_hillWestNear_no",cursorLangId="tpp_africa_hillWestNear",position=Vector3(1823,0,693.7),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="mafr_pfCampEast_ob",langId="tpp_africa_pfCampEast_no",cursorLangId="tpp_africa_pfCampEast",position=Vector3(1185.2,0,576),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="mafr_pfCampNorth_ob",langId="tpp_africa_pfCampNorth_no",cursorLangId="tpp_africa_pfCampNorth",position=Vector3(933.1,0,370),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="mafr_factorySouth_ob",langId="tpp_africa_factorySouth_no",cursorLangId="tpp_africa_factorySouth",position=Vector3(2366,0,-111.3),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="mafr_factoryWest_ob",langId="tpp_africa_factoryWest_no",cursorLangId="tpp_africa_factoryWest",position=Vector3(2441.2,0,-793.7),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="mafr_diamondNorth_ob",langId="tpp_africa_diamondNorth_no",cursorLangId="tpp_africa_diamondNorth",position=Vector3(1331.8,0,-1907),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="mafr_labWest_ob",langId="tpp_africa_labWest_no",cursorLangId="tpp_africa_labWest",position=Vector3(2155.7,0,-2184.7),radius=75,uShift=0,vShift=0,mini=true},
        {cpName="mafr_chicoVilWest_ob",langId="tpp_africa_chicoVilWest_no",cursorLangId="tpp_africa_chicoVilWest",position=Vector3(1537.1,0,1783),radius=75,uShift=0,vShift=0,mini=true}}}
    elseif a==50 then
      return{stageSize=2048*2,scrollMaxLeftUpPosition=Vector3(-2144,0,-2144),scrollMaxRightDownPosition=Vector3(2144,0,2144),highZoomScale=14.4,middleZoomScale=3.5,lowZoomScale=.5,naviHighZoomScale=14.4,naviMiddleZoomScale=5,locationNameLangId="tpp_loc_mb",uniqueTownTexturePath="/Assets/tpp/ui/texture/map/building_icon/mb_map_bild_icon_mb_alp_clp.ftex",commonTownTexturePath="/Assets/tpp/ui/texture/map/building_icon/mb_map_bild_icon_cmn_alp_clp.ftex",townParameter={{mbId=0,langId="platform_en_main",cursorLangId="platform_main",radius=75,uShift=0,vShift=0},
        {mbId=1,langId="platform_en_combat",cursorLangId="platform_combat",radius=75,uShift=.25,vShift=0},
        {mbId=2,langId="platform_en_RD",cursorLangId="platform_RD",radius=75,uShift=.5,vShift=0},
        {mbId=3,langId="platform_en_base_dev",cursorLangId="platform_base_dev",radius=75,uShift=.5,vShift=.25},
        {mbId=4,langId="platform_en_support",cursorLangId="platform_support",radius=75,uShift=.75,vShift=0},
        {mbId=5,langId="platform_en_intel",cursorLangId="platform_intel",radius=75,uShift=.25,vShift=.25},
        {mbId=6,langId="platform_en_medical",cursorLangId="platform_medical",radius=75,uShift=0,vShift=.25},
        {mbId=10,langId="platform_en_isolation",cursorLangId="platform_isolation",radius=75,uShift=.75,vShift=.25},
        {mbId=20,langId="platform_en_protection",cursorLangId="platform_protection",radius=75,uShift=0,vShift=.5},
        {mbId=21,langId="platform_en_zoo_bird",cursorLangId="platform_zoo_bird",radius=75,uShift=0,vShift=.5},
        {mbId=22,langId="platform_en_zoo_herbivore1",cursorLangId="platform_zoo_herbivore1",radius=75,uShift=0,vShift=.5},
        {mbId=23,langId="platform_en_zoo_herbivore2",cursorLangId="platform_zoo_herbivore2",radius=75,uShift=0,vShift=.5},
        {mbId=24,langId="platform_en_zoo_canivore",cursorLangId="platform_zoo_canivore",radius=75,uShift=0,vShift=.5}}}
    elseif a==55 then
      return{stageSize=37.5*2,scrollMaxLeftUpPosition=Vector3(-12,0,-32),scrollMaxRightDownPosition=Vector3(12,0,8),stageRotate=0,highZoomScale=3.5,middleZoomScale=1.5,lowZoomScale=.5,naviHighZoomScale=3.5,naviMiddleZoomScale=2,locationNameLangId="platform_isolation",heightMapTexturePath="/Assets/tpp/ui/texture/map/map_mtbs/parts/uq_0070_inside_alp.ftex"}
    end
    return{stageSize=4096*2,scrollMaxLeftUpPosition=Vector3(-4096,0,-4096),scrollMaxRightDownPosition=Vector3(4096,0,4096),highZoomScale=4.8,middleZoomScale=2.34,lowZoomScale=.7,naviHighZoomScale=4.8,naviMiddleZoomScale=2.34,heightMapTexturePath="/Assets/tpp/common_source/ui/common_texture/cm_wht_64.ftex",photoRealMapTexturePath="/Assets/tpp/common_source/ui/common_texture/cm_wht_64.ftex",townParameter={{cpName="cp_base",langId="tpp_afghan_en_village",cursorLangId="tpp_loc_mb",position=Vector3(-331.626,287.2856,2017.428),radius=23,uShift=.25,vShift=.75,mini=false},
      {cpName="afgh_field_cp",langId="",cursorLangId="",position=Vector3(393,0,2150),radius=200,uShift=.25,vShift=.25,mini=true}}}
  end,
  GetGlobalLocationParameter=function()
    return{
      {locationId=10,sectionFuncRankForDustBox=2,sectionFuncRankForToilet=2,sectionFuncRankForCrack=4,isSpySearchEnable=true,isHerbSearchEnable=true,spySearchRadiusMeter={40,40,35,30,25,20,15,10},spySearchIntervalSec={420,420,360,300,240,180,120,60},herbSearchRadiusMeter={0,0,10,15,20,25,30,35}},
      {locationId=20,sectionFuncRankForDustBox=4,sectionFuncRankForToilet=4,sectionFuncRankForCrack=6,isSpySearchEnable=true,isHerbSearchEnable=true,spySearchRadiusMeter={40,40,35,30,25,20,15,10},spySearchIntervalSec={420,420,360,300,240,180,120,60},herbSearchRadiusMeter={0,0,10,15,20,25,30,35}},
      {locationId=50,isFobSpySearchEnable=true,spySearchRadiusMeter={84,84,75,65,56,47,38,29},spySearchIntervalSec={700,700,600,500,400,300,200,100}}}
  end,
  GetLocationOfMissions=function()
    local a={}
    for i,t in pairs(TppDefine.LOCATION_HAVE_MISSION_LIST)do
      for e,t in pairs(t)do
        a[t]=TppDefine.LOCATION_ID[i]
      end
    end
    return a
  end}
