this={}
Player.RegisterAppealActions{
  actionCount=41,
  actions={
    {"Salute",
      1.5,--tex NMC time before stop anim?
      0,--tex mirror
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snambud/snambud_s_slt_start_l.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snambud/snambud_s_slt_idl_l.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snambud/snambud_s_slt_ed_l.gani",
      0},

    {"VenomSnake",
      1.5,
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snambud/snambud_s_fst_st.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snambud/snambud_s_fst_idl_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snambud/snambud_s_fst_ed.gani",
      0},

    {"VenomSnakeMirror",
      1.5,
      1,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snambud/snambud_s_fst_st.gani",
      1,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snambud/snambud_s_fst_idl_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      0},

    {"OcelotMirror",
      1.5,
      1,
      "/Assets/mgo/motion/SI_game/fani/bodies/ocep/ocepbud/ocepbud_s_slt_st.gani",
      1,
      "/Assets/mgo/motion/SI_game/fani/bodies/ocep/ocepbud/ocepbud_s_slt_idl_l.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      0},

    {"Ocelot",
      1.5,
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/ocep/ocepbud/ocepbud_s_slt_st.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/ocep/ocepbud/ocepbud_s_slt_idl_l.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/ocep/ocepbud/ocepbud_s_slt_ed.gani",
      0},

    {"QuietThumbsUpGood",
      1,
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/quip/quipnon/quipnon_s_good_st_l.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/quip/quipnon/quipnon_s_good_idl_l.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/quip/quipnon/quipnon_s_good_ed_l.gani",
      0},

    {"QuietThumbsUpGoodMirror",
      1,
      1,
      "/Assets/mgo/motion/SI_game/fani/bodies/quip/quipnon/quipnon_s_good_st_l.gani",
      1,
      "/Assets/mgo/motion/SI_game/fani/bodies/quip/quipnon/quipnon_s_good_idl_l.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      0},

    {"MaruSign",
      1,
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_6_st.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_6_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      1},

    {"BatsuSign",
      1,
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_7_st.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_7_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      1},

    {"DVolunteer",
      1,
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_9_st.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_9_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      1},

    {"DVolunteerMirror",
      1,
      1,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_9_st.gani",
      1,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_9_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      1},

    {"DBow",
      1,
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_8_st.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_8_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      1},

    {"DBowMirror",
      1,
      1,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_8_st.gani",
      1,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_8_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      1},

    {"Push",
      1,
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_23_st.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_23_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      1},

    {"Disappointed",
      1,
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_16_st.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_16_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      1},

    {"StandAttention",
      1,
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_21_st.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_21_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      2},

    {"GratitudeBow",
      1,
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_22_st.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_22_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      2},

    {"Karate",
      1,
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_20_st.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_20_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      2},

    {"KungFu",
      1,
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_18_st.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_18_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      2},

    {"KungFuMirror",
      1,
      1,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_18_st.gani",
      1,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_18_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      2},

    {"BodyBuilderFrontChest",
      1,
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_1_st.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_1_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      2},

    {"BodyBuilderSideChest",
      1,
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_2_st.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_2_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      2},

    {"BodyBuilderSideChestMirror",
      1,
      1,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_2_st.gani",
      1,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_2_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      2},

    {"RollDanceUp",
      1,
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_3_st.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_3_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      3},

    {"RollDanceSide",
      1,
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_4_st.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_4_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      3},

    {"RollDanceSideMirror",
      1,
      1,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_4_st.gani",
      1,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_4_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      3},

    {"RollDanceDown",
      1,
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_5_st.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_5_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      3},

    {"UDanceUp",
      1,
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_25_st.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_25_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      3},

    {"UDanceSide",
      1,
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_26_st.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_26_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      3},

    {"UDanceSideMirror",
      1,
      1,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_26_st.gani",
      1,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_26_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      3},

    {"LDanceUp",
      1,
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_28_st.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_28_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      3},

    {"LDanceUpMirror",
      1,
      1,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_28_st.gani",
      1,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_28_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      3},

    {"LDanceSide",
      1,
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_29_st.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_29_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      3},

    {"LDanceSideMirror",
      1,
      1,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_29_st.gani",
      1,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_29_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      3},

    {"GutsPose",
      1,
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_17_st.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_17_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      4},

    {"GutsPoseMirror",
      1,
      1,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_17_st.gani",
      1,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_17_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      4},

    {"SuperSUp",
      1,
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_10_st.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_10_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      4},

    {"SuperSSide",
      1,
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_11_st.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_11_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      4},

    {"SuperSiSideMirror",
      1,
      1,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_11_st.gani",
      1,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_11_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      4},

    {"PointingMirror",
      1,
      1,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_19_st.gani",
      1,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_19_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      4},

    {"Pointing",
      1,
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_19_st.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_19_lp.gani",
      0,
      "/Assets/mgo/motion/SI_game/fani/bodies/snam/snamidl/snamidl_s_ed.gani",
      4}
  }
}
return this
